### ISSUE TITLE
Missing gradle files

### ISSUE THREAD

**Issue by krt16s** [y20k/transistor#1]
Gradle build files are required for building this app. While you might just use "common" build files by now, when you add more libraries etc. the gradle files are really needed.

Ref: https://f-droid.org/forums/topic/transistor-radio-app/

**Comment by y20k** [comment]
Okay. Thank you for your reply. I now added the missing gradle files. I had them locally but I thought that Android Studio creates missing gradle files automatically and that the Manifest would be sufficient. Another Lesson learned.

If you can spot anything else that is missing, please tell me. There is a "gradle" directory and a "built" directory on my local machine next to the "app" folder. Both are not part of the repo here on GitHub yet.

Best wishes, Christian

![screen shot 2015-11-19 at 11 15 09](https://cloud.githubusercontent.com/assets/9103935/11267987/d6a4ba82-8eae-11e5-9c4a-dcf1a21ae1f7.png)

**Comment by y20k** [comment]
No follow-up. I guess I can close this one.
