### ISSUE TITLE
MPD stream?

### ISSUE THREAD

**Issue by sprnza** [y20k/transistor#100]
Hi there!
Thank you for your app! 
Could you please help me to get a MPD stream link wirking (or just check that it's not possible). Here it is: http://cloud.speran.info:8000 It's the MP3 stream, I've tried to add /mpd.mp3 at the end but Transistor fails to
 add it then.

**Comment by y20k** [comment]
Congratulations. This is Issue #100. :cake: 

I was able to add the stream. Try this: 

- copy the URL http://cloud.speran.info:8000 
- tap the + button
- paste the URL
- done (*)

(*) At least on my phone. If this does not work for you: What does Transistor's error message say?

**Comment by sprnza** [comment]
Thanks! Haha! Lucky numbers.
Yeah, sorry for being incorrect. Yes, the link is being added fine, but Transistor is not able to play it, that's the issue.

**Comment by y20k** [comment]
I did try to play back the stream you posted. I tested it on my phone (Android 6) and it did not have any problems. 

On an emulator running Android 5.1 everything was fine, too. **On another emulator running Android 4.4 the station would not play.** The stream indeed is plain MP3. That is very strange. Some users have had problems with AAC playback, but MP3 was always fine on all platforms. 

Checking the LOGCAT I got an error of type **[MediaPlayer: error (1, -1004)](https://developer.android.com/reference/android/media/MediaPlayer.html#MEDIA_ERROR_IO)** on Android 4.4. I will try to find a solution for it - but no promises :smile_cat:

**Comment by sprnza** [comment]
Yeah, I have 4.4 on my phone. Sorry that forced you to try all versions, I should include the version in my initial post. I hope you will find a way to fix it. I like your app!


From Meizu MX3

-------- Original message --------
Sender: y20k <notifications@github.com>
Time: Sat 7/16 21:45
To: y20k/transistor <transistor@noreply.github.com>
Cc: sprnza <denis@speran.info>,Author <author@noreply.github.com>
 Subject: Re: [y20k/transistor] MPD stream? (#100)

**Comment by pelya** [comment]
This stream works fine on my phone, with Android 5.0.

**Comment by y20k** [comment]
Hey @sprnza,

today I again tried to find the issue that causes the MP3 stream to fail on Android 4.4. No results so far. Do you have control over the streaming server on speran.info? You are running a [blog](http://www.speran.info/pages/about.html) under the same domain, right?

Which kind of streaming server do you use? Maybe there is a certain (uncommon) configuration on the server side that causes the conflict with Android 4.4.

**Comment by sprnza** [comment]
Hey @y20k!
Yep, you are right it's my own server. I run MPD with just a plaing streaming config like this:
```
audio_output {
	type		"httpd"
	name		"Speranza! Radio"
	encoder		"lame"		# optional, vorbis or lame
	port		"8000"
#	bind_to_address	"0.0.0.0"		# optional, IPv4 or IPv6
##	quality		"5.0"			# do not define if bitrate is defined
	bitrate		"128"			# do not define if quality is defined
	format		"44100:16:1"
	max_clients	"0"			# optional 0=no limit
}
```

**Comment by sprnza** [comment]
changing encoder from MP3 to Ogg made Transistor able to play the sream.

**Comment by sprnza** [comment]
Thanks for attention to my problem, btw! :)

**Comment by y20k** [comment]
> I'm not sure if it's a solution though.

It works on my emulator now too. But I guess it is not a solution :-) But since your case is very special I hope that Transistor on Android 4.4 will play most other MP3-stations. 

Reading a bit more about MPD... It comes with its own http-capable server. So there is no possibility to tweak on the server side. 

The only other thing I found was:

From the [Arch-Wiki on MPD / HTTP Streaming](https://wiki.archlinux.org/index.php/Music_Player_Daemon/Tips_and_tricks#HTTP_Streaming):

`You may have to specify the file format of the stream using an appropriate file extension in the URL`

--> http://cloud.speran.info:8000/mpd.ogg works for the currently running OGG stream. If you change the config back to mp3, you could try the URL http://cloud.speran.info:8000/mpd.mp3

I am not very optimistic. But it is worth a try.

**Comment by y20k** [comment]
Sorry that I wasn't able to help you. I will close this issue for now. Best regards.
