### ISSUE TITLE
Back button doesn't work after tapping on Transistor notification

### ISSUE THREAD

**Issue by c00ller** [y20k/transistor#107]
Straightforward to reproduce:
1) Start playing so there is a Transistor notification.
2) Tap on the notification.
3) Press the back button (the phone's back button).
4) It should take me back to the list of stations, but nothing happens.

The only way to return to the station list after tapping on the Transistor notification is to press the upper left back arrow.

Device: Nexus 5X, Android 7.0, Transistor 2.1.

**Comment by y20k** [comment]
Thanks for reporting this. I will look into it. That needs to be fixed.

**Comment by y20k** [comment]
The next version ([v2.1.6](https://github.com/y20k/transistor/releases/tag/v2.1.6)) includes a fix for this issue. Thanks again for reporting!!
