### ISSUE TITLE
Copy directory from Assets to local directory

### ISSUE THREAD

**Issue by MFreeHost** [y20k/transistor#110]
im new in android dev world i want to use your source code to create a personal radio app ,  i add colection folder with pre-build stations in  assets folder but i dont know how to move the  directory from assets to ../android/data/org.y20k..../files/ second issues is force closer under android 7.1 causing by storage permission ,its disebled sorry form my bad english

**Comment by y20k** [comment]
Hi there. 

Sorry for the delayed answer. I was pretty busy the last couple of weeks. 

Transistor does not need a "Storage" permission for playback and station import or station storage: Files stored under /Android/data/org.y20k.transistor/files/Collection can be accessed without any permission - the "org.y20k.transistor" part would be different for your new version of the app.

Android has a method [getExternalFilesDir](https://developer.android.com/reference/android/content/Context.html#getExternalFilesDir(java.lang.String)) to get the path of your directory. I use a variant of that method in [StorageHelper](https://github.com/y20k/transistor/blob/master/app/src/main/java/org/y20k/transistor/helpers/StorageHelper.java).

If you want o use any other location on SD card or external storage you need to [request permission](https://developer.android.com/training/permissions/requesting.html) to do so.

The easiest way to ship the app with a set of stations would be to create a **FirstRunHelper** class that uses the [constructor in Station for URLs](https://github.com/y20k/transistor/blob/master/app/src/main/java/org/y20k/transistor/core/Station.java#L99).

I hope that helps a bit.
Best regards

PS. I you plan to publish your new app. Please use a different name and icon.

**Comment by y20k** [comment]
This one is "resolved", right? I am closing it. Feel free to reopen, if you disagree.
