### ISSUE TITLE
is it not possible to OPEN a m3u file in this app??

### ISSUE THREAD

**Issue by 2SI3NX** [y20k/transistor#111]
im pretty much summing it up in the title. I want to just simply open up a m3u file from a dir, within the m3u file there are various radio stations.  Can you add this feature to simply work with files and not to sit and type the full URL everytime I want a new URL?

**Comment by y20k** [comment]
Hi there. 

Transistor used to have a feature where you can tap on a m3u file and Transistor would offer itself as a file handler. One of the last updates broke that functionality. I did re-add the functionality in the 2.1.7 release.

Thanks for pointing me indirectly to that bug. 

I recognize that this is not a solution to your problem. You want to manually organize your radio stations in a single m3u file. At least that what I figured from your post. I am afraid, but I guess I will not offer that option for now.

Transistor is built around the idea that there is a user accessible folder (/Android/data/org.y20k.transistor/files/Collection) that stores all radio stations and icons in plain files. Theoretically you can delete or modify a station just using a file explorer and a text editor. 

To offer an alternative method to store and manipulate stations (= in a single m3u file) would complicate the app without a pressing reason.

Sorry to disappoint you and thx again for pointing me to the above mentioned bug.
