### ISSUE TITLE
file .pls is very slow can you help me?

### ISSUE THREAD

**Issue by oattoreto** [y20k/transistor#117]
My stream radio is very slow, I don't know why.
When I play radio with .m3u, it is fast and look so good but when I play with .pls is very very slow.(about 20 sec.) Can you help me about this? 
Thank You.

Ps. This is my url : http://111.223.51.7:8005/listen.pls

**Comment by y20k** [comment]
Hi there.

The stream take forever to open on my device, too. 

m3u and pls are two very similar text based container files. Those files contain the "real" streaming URL. (You can open m3u and pls in a text editor). "Your" PLS file contains an AAC stream. :-( I am sorry, but AAC is only partly supported by Transistor. 

In the case that an AAC based stream behaves badly, it is sometimes a good idea to look for a MP3 version of that stream. In your case you could try http://sv2.hostpleng.com:8003/Great93.mp3

On my device the startup time using this mp3 stream is a bit faster, but still not as fast as most of the other streams I listen to.

**Comment by oattoreto** [comment]
Thank you for answer.
I have one question, if I don't have way to fix PLS faster, Can lib has animation or show buffer or something that show to User for waiting to listen radio? (ex. waiting for 94fm...)

Thank You for help again and sorry for my bad english.

**Comment by y20k** [comment]
Hi there,

there is an indicator within the app, that is orange while the stream is preparing, and that should switch to green when Transistor starts to play back the stream.

Did you try the alternative stream version for **COOLfahrenheit 93**: http://sv2.hostpleng.com:8003/Great93.mp3 ? Is it still too slow?

**Comment by oattoreto** [comment]
Its ok faster than old link thank you.

I have new issue about PlayerService, It play multi stream in same time how I fix it?

Thank you.

**Comment by y20k** [comment]
This is a new bug. Please head over to #119 . 

The initial bug is more or less resolved - at least for you and the specific station.
