### ISSUE TITLE
Multiple streams playing simultaneously 

### ISSUE THREAD

**Issue by y20k** [y20k/transistor#119]
In #117 @oattoreto wrote

> I have new issue about PlayerService, It play multi stream in same time how I fix it?

**Comment by y20k** [comment]
Hi @oattoreto

Can you describe me step by step how this bug occurs? If I can reproduce it I can probably fix it.

**Comment by oattoreto** [comment]
In LG Android 7.0 I wait for first radio(it is not come right now), and then I play another radio. It come  same time.

**Comment by y20k** [comment]
Okay. Thanks. I'll look into this.

**Comment by y20k** [comment]
Hi there. I did try to reproduce the problem - but I was not able to. Sorry. Can you post the PLS/M3U of the two streams you tried?

**Comment by oattoreto** [comment]
I workaround by delay click change station, its work. But on Android Kitkat 4.4.2 Galaxy Grand2 its not work some station, error is "Unknown media playback error" and "IO media error."

and this link not work := http://122.155.16.48:8955/listen.pls

**Comment by y20k** [comment]
Hi. 

Today I tried to reproduce the error on an emulated Samsung Galaxy Nexus with 4.4.2. Sadly I was unable to reproduce the problem, where two streams would play play simultaneously.

Also: The link you posted worked without any problem.

I am really sad. But I do not know how to help you. 😞

**Comment by y20k** [comment]
Hi @oattoreto,

are you interested in testing a version of Transistor that uses a new media library ([ExoPlayer](https://developer.android.com/guide/topics/media/exoplayer.html))? This probably / maybe fixes your issue with Android 4.4.2.

If so, please head over to issue #120 and report your findings.

Thanks & take care.

**Comment by y20k** [comment]
[v.2.2.1](https://github.com/y20k/transistor/releases/tag/v2.2.1) is out. It comes with the new playback library  `ExoPlayer`. I hope the issue is fixed. I will close this it for now. Feel free to reopen, if you still got problems.
