### ISSUE TITLE
Switch to ExoPlayer - Beta Testers wanted

### ISSUE THREAD

**Issue by y20k** [y20k/transistor#120]
Hi there,

Transistor traditionally has used [MediaPlayer](https://developer.android.com/guide/topics/media/mediaplayer.html) as its back-end. MedaPlayer for the most part has worked great for me. But there are some issues with AAC and newer adaptive streaming technologies, as well as sometimes a slow start-up time.

In the past I was very hesitant regarding any experiments with the back-end, since the existing one worked most of the time just fine. I argued that Transistor is basically a one-man-part-time-show, and that I needed to keep development sustainable. Therefore I did (and do) not want to experiment with any third-party media libraries.

Enter [ExoPlayer](https://developer.android.com/guide/topics/media/exoplayer.html). ExoPlayer is an open source media library developed by Google. It is used as the back-end of their YouTube app. ExoPlayer promises better codec compatibility. It is probably pretty future proof, since Google uses it in their own apps. 

So after some thinking/considering I decided to give it a try. The results are pretty good so far. It seems that streams start faster than in the past and Transistor still plays back all of my (23) stations.

Switching the back-end is a pretty big thing. So before I roll out the next version of Transistor, **I need YOU to test the playback functionality** of the app. I need to decide if I should continue to pursue the ExoPlayer route, of if I should go back to MediaPlayer.

So if anyone here has time to spare: Please check out the latest beta release.

**Latest beta release (signed)**
* v2.2.1-04: [transistor-app-test-2.2.1-04.apk](https://www.dropbox.com/s/05ej2irmb0g7kax/transistor-app-test-2.2.1-04.apk?dl=0) based on this [code](https://github.com/y20k/transistor/blob/c3b50684800b28f72a3492cce1e67eab94983660/app/src/main/java/org/y20k/transistor/PlayerService.java).

* ~~v2.2.1-03: [transistor-app-test-2.2.1-03.apk](https://www.dropbox.com/s/07bnw8cnvg6dc89/transistor-app-test-2.2.1-03.apk?dl=0) based on this [code](https://github.com/y20k/transistor/blob/76551666e3921f108b13125e9d94790929435ea7/app/src/main/java/org/y20k/transistor/PlayerService.java).~~

* ~~v2.2.1-02: [transistor-app-test-2.2.1-02.apk](https://www.dropbox.com/s/vnclitzexlokast/transistor-app-test-2.2.1-02.apk?dl=0) based on this [code](https://github.com/y20k/transistor/blob/3766c3d14d33c7655c9b0d537061e397b0034506/app/src/main/java/org/y20k/transistor/PlayerService.java).~~

* ~~v2.2.1-01: [transistor-app-test-2.2.1-01.apk](https://www.dropbox.com/s/5rk3zv22mdvpubz/transistor-app-test-2.2.1-01.apk?dl=0) based on this [code](https://github.com/y20k/transistor/blob/10e0a5716cea8a0acdca40f05eb9d019a5c627c4/app/src/main/java/org/y20k/transistor/PlayerService.java).~~

**Known issues**
* ~~120a: No attempt to reconnect after loss of network connection~~
* ~~120b: Now playing (metadata display) is not working~~
* 120c: Playback sometimes just stops (**more info needed**)
* ~~120d: Buffer is not emptied -> When starting playback for a second station the buffer from the first one is still audible~~

**Comment by twouters** [comment]
Playback stops when network connection drops but does not resume when the connection returns.
I don't have any more details yet, but I'll try to find a reproducable test. (Debugging and driving around with my car seems like a bad combo :-))

**Comment by twouters** [comment]
It looks like it's reproducable by just disconnecting from wifi, so at least it's not related to cellular data :-)

**Comment by y20k** [comment]
@twouters Thanks for the observation. 

> It looks like it's reproducable

Yay!

I think this is not ExoPlayer-related - but just a "cabeling" error on my part. I probably did not hook up all the error-callbacks from ExoPlayer correctly. Right now Transistor just stops in the case of an error where it should try to reconnect. 

I will look into that and post a new APK within the next couple of days (depending on my real-life schedule ⚒).

**Comment by twouters** [comment]
https://github.com/y20k/transistor/blob/9d83f6229708f96b5b04875110ed651c508eab69/app/src/main/java/org/y20k/transistor/PlayerService.java#L774-L776

According to the [docs](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/source/ExtractorMediaSource.html#constructor.summary), there's an additional parameter here (`int minLoadableRetryCount` which defaults to `-1`). Changing this to something > 1 might help. Retries happen after a delay of max 5000ms. (It looks like the first retry will be instant, the second gets delayed for 1000ms, the third 2000ms, ... max 5000ms.)
I guess this will need some experimentation.

Don't take my word on the internals here, it's how I understand the ExoPlayer code and I could be very very wrong 😄

**Comment by y20k** [comment]
Thanks for the hint. I did not know this parameter.  I will check what happens if I change this. 

The switch to ExoPlayer surfaced another problem that I was not aware of.  Transistor's MetadataHelper does not handle connection drops gracefully. I will probably temporarily disable Metadata-extraction in the next test-APK.

**Comment by y20k** [comment]
I did implement the `int minLoadableRetryCount` in the current beta APK **v2.2.1-02**. You can download and test it, if you like. An APK link is in the initial comment at the top of the page.

**Comment by twouters** [comment]
The addition of the retrycount has improved the situation for me.
I know that you don't want to add too much additional/bloating functionalities, but the current buffer size is a bit short for my use case. (I don't blame you for this, but my ISP :-p)
I haven't looked at the code to see how this can easily be implemented but I would love an option/a setting to increase the buffer size. MediaPlayer doesn't allow this, but I thought it was an option for ExoPlayer.

**Comment by y20k** [comment]
Regarding the **Metadata**, that in the current beta is not being extracted, there is good news. There is a [patch](https://github.com/Ood-Tsen/ExoPlayer/commit/8ccc99bc5c6428760efd9f1780dd90be9386339e) that has been discussed in the ExoPlayer [issue tracker](https://github.com/google/ExoPlayer/issues/466) that works for AAC **and** MP3. I will try to adapt it for Transistor.

**Comment by y20k** [comment]
Regarding the buffer size: I will look into it. Thanks for the hint.

**Comment by y20k** [comment]
Just a side note: "My" version of the ExoPlayer Demo app that extracts metadata from MP3 (based on the above mentioned patch) can be found [here](https://github.com/y20k/ExoPlayer/commit/0a06c486130dba555fd451690988102e7f12fabc). I had to do almost nothing to get this to work for MP3. 

Problem is that this solution only seems to work with v1 of ExoPlayer. I will probably somehow work with v2, too. But I do not know how to adapt the code. 😞 

Anyway. I added a [comment](https://github.com/google/ExoPlayer/issues/466#issuecomment-289489261) to the (still open) Shoutcast feature request on the GitHub issue tracker.

I will continue to work on other ExoPlayer issues with Transistor for now. Let's wait and see, if Shoutcast support is coming.

**Comment by y20k** [comment]
Update: There is a new a beta APK ([transistor-app-test-2.2.1-03.apk](https://www.dropbox.com/s/07bnw8cnvg6dc89/transistor-app-test-2.2.1-03.apk?dl=0)) based on this [code](https://github.com/y20k/transistor/blob/76551666e3921f108b13125e9d94790929435ea7/app/src/main/java/org/y20k/transistor/PlayerService.java) reflecting the latest changes: 

- re-enabled metadata display
- [increased](https://github.com/y20k/transistor/blob/76551666e3921f108b13125e9d94790929435ea7/app/src/main/java/org/y20k/transistor/PlayerService.java#L607) the buffer size for ExoPlayer

**Comment by twouters** [comment]
Thank you for increasing the buffer size, I notice a huge improvement (though I still have a disconnect somewhere on the road, but I think it's the same on e.g. Tunein)
I have been using the latest version on a daily basis and haven't noticed any specific bugs. The metadata seems to be working fine too.
Anyway, I'm very happy with the results, it's awesome! 👍

**Comment by FionaHagen** [comment]
Hi, I tried out v2.2.1-03 on Android 7.1.1 and experienced much faster load times. Awesome! 😎

I have one stream which does not load in both versions (v2.2.1-03 and [2.2 from Google Play](https://play.google.com/store/apps/details?id=org.y20k.transistor)). It is [http://listen.technobase.fm/dsl.pls](http://listen.technobase.fm/dsl.pls). Here is a screenshot:

![tb](https://cloud.githubusercontent.com/assets/22400585/24952412/a00f4860-1f77-11e7-890a-67a26f995a11.jpg)

Can you check that please? Is it a bug or did I make something wrong? 🤔

Thanks for your awesome app! 🤠

**Comment by y20k** [comment]
Hi @FionaHagen,

Transistor does not rely on file extensions for determining, if a file (or an URL) is "valid". The app checks the source's MIME type. In your case that would be `application/x-scpls`. That mime type is currently not supported (see [Station.java](https://github.com/y20k/transistor/blob/76551666e3921f108b13125e9d94790929435ea7/app/src/main/java/org/y20k/transistor/core/Station.java#L61)). I am not sure, but I think that `application/x-scpls` is not the correct / official MIME type for PLS (see [Wikipedia](https://en.wikipedia.org/wiki/PLS_(file_format))). That would be an explanation why it is not included the current code of the app.

Anyway. I need to consider if it does any harm to include `application/x-scpls` in the next release. In the meantime: (1) You can contact the radio station's admin and ask her/him to correct the MIME type (probably not very practical 😸). (2) You can wait for the next release (3) **you can add this URL manually http://listen.technobase.fm/tunein-mp3-pls** (the address can be found, if you open the PLS in a text editor).

Best regards

**Comment by FionaHagen** [comment]
Thanks for the great explanation @y20k 😎

**Comment by y20k** [comment]
The current code base works great on my devices. Plus: No new bug reports. Time to close this issue. [v.2.2.1 is out](https://github.com/y20k/transistor/releases/tag/v2.2.1) and it comes with ExoPlayer.
