### ISSUE TITLE
Volume very low on all streams since 2.2.2 update

### ISSUE THREAD

**Issue by jfml** [y20k/transistor#125]
I really love this app but since the 2.2.2 update (via F-Droid) all the streams are so low in volume that I can almost not here them (other media players are fine). I'm on Wileyfox Swift, running LineageOS 14.1 / Android 7.1.2

I'd be happy to supply more info if told how to do so ^___^

Thanks again for the great app!

**Comment by jfml** [comment]
Issue fixed wih 2.2.3! My bad, sorry!

**Comment by y20k** [comment]
Okay. I am glad that the issue solved itself. I had otherwise no idea what could have cause this behavior. 😄
