### ISSUE TITLE
Why isn't the newest version on F-Droid?

### ISSUE THREAD

**Issue by e3b** [y20k/transistor#128]
F-Droid has 2.2.3, Google Play 2.2.4. How come? (I'm just curious.)

**Comment by y20k** [comment]
F-Droid builds its apps from source. It detects version changes here in GitHub automatically. Depending on their internal queue that can take a few days. I am not sure if they have to do some of the steps involved manually.

https://gitlab.com/fdroid/fdroiddata/commits/master/metadata/org.y20k.transistor.txt

So I would just wait a couple of days.

PS. Very rarely the build fails. In that case there is a bug in my code, or I forgot to upload a code commit. I think this is not the case for v2.2.4.
