### ISSUE TITLE
Direct play

### ISSUE THREAD

**Issue by gerroon** [y20k/transistor#129]
Hi

It would be nice if a url is shared from another app to Transistor, it starts playi it right away instead of just adding to the list. When I add share a radio from Radiodroid, it only adds to the list but in reality I would like it to play automatically after adding.

thanks

**Comment by y20k** [comment]
Hi @gerroon ,

first of all: Thanks for your suggestion. I need to think about it. 

My first take would be (brain storming): 

* In your use case you would like a recently added station to start playback automatically. I get that. Maybe even a lot of users feel/want the same.
* The `(+)`- icon in the UI suggests another action: Add a new station. You would not expect to start playback.
* You suggest that if you open Transistor from another app, e.g. Chrome, Transistor should behave differently. It should save the station and start playback.

There are a few things to weigh against each other - given the above thoughts:
1. Is it okay that adding a station via `(+)`- icon and via "open in Transistor" result in a different behavior?
2. Isn't there a difference between a media player app like VLC (that definitely should auto-play content) and Transistor
3. Could the new behavior annoy users who do not expect auto-play? If they are on a metered connection or in a silent environment

So my first take would be to say no. But I know me: I say no very often as a first response 😼. So I will let the idea sink in and decide later.

THX & best regards

**Comment by gerroon** [comment]
Hi

I personally never + to add a station, as a user my intention is to use it as a player. The reason I am not interested in managing my playlists in this app because to me it is tedious to add the stations given that no import is avail and it seems like it can onlyy play  a single station from a playlist with bunch of files so like I said I prefer to use it as single click play that can play in the bg. 

You ask what the diff between vlc and this app. I am not sure, vlc can do everything this app can at almost with the same ease and more. The only thing I can see that being a major difference is that this app can only play audio files. I also do not see much different in cpu use.

I understand that you are trying to keep it simple, I respect that. But, to me trying to keep it bare minimum does not always fit in the way Android system functions. Minimal is great, but needing to click multiple times to play something is not so great. If the purpose is minimal, the efforts to do somehting with this app should be minimal too.

I can see three options

- Offer another share action that says "play in Transistor" which is different that just sharing to Transistor which just adds to the curent list.

- Do not offer sharing to Transistor

- Keep the status quo ;)

**Comment by y20k** [comment]
Hi @gerroon from the couple of issues you opened here I get the impression that we have different visions for what Transistor should be. 

>  I am not interested in managing my playlists in this app

I considered adding a "Play in Transistor" option in addition to the exiting "Add to Transistor". This would open Transistor up to be a universal m3u-Stream player. But as I said earlier: I think that role can be filled better and way more competent by VLC. 

Transistor is for you, if you have a set of stations you listen to on regular basis. In that case it makes sense to use the curate the set of stations in Transistor.

There is also a technical reason: It is not possible to offer two actions for one App/Activity. I know that other apps do that but as far as I know that is a hack.

So, sorry to disappoint you. I'll close this issue.
