### ISSUE TITLE
Add all stations in a playlist

### ISSUE THREAD

**Issue by gerroon** [y20k/transistor#130]
Hi

Transistor only adds a single station from a playlist with bunch of stations. It would be nice if one could actually import bunch of stations from a playlist, otherwise it is a bit tedious of work to bring those all in.

One might argue well this is a minimalist app and such, it defeats the purpose of  being a simple radio app, but then as a user I would counter argue that it makes it useless for my purposes because then I will need to use another app to manage all those stations and occasionally give this app another try to see  what is going on with it. 

Here is an m3u
http://www.radio-browser.info/webservice/m3u/stations/bytagexact/jazz

I can see it being useful for clicking some single radio link on the web, but how many times a day do we do that?

**Comment by y20k** [comment]
Hi @gerroon,

Wow. Your example playlist contains 386 stations. That is a use case I have never considered before. I think **Transistor is not fit to handle so many stations**. It would need a search option, a sorting UI etc.

You want Transistor to be a radio browser. To be able to add so many stations at once would just be a tiny step compared to the other stuff it would take to convert it to a good radio browser. I native search would be great and a "preview" feature.

I do not see that kind of change on the horizon for Transistor. I think [RadioDroid](https://github.com/segler-alex/RadioDroid) is probably the app that better fits your needs.

Sorry to disappoint you.

**Comment by gerroon** [comment]
Radiodroid is good for browsing Radio Browser ;) It is fine but it is  a special use case. I gave you the playlist as an example not that I want to import them all.

Radiodroid cant play anything beside RB sites, I mean it is an awesome site with alot of stuff. And RD is great for locating some radios however it is a special purpose player not a general purpose one. 

Anyway I respect you position on how you want to cure your app.

thanks
