### ISSUE TITLE
Slide to delete

### ISSUE THREAD

**Issue by gerroon** [y20k/transistor#131]
Hi

Most apps with item list display support slide to delete an item from the list. It is a standard behavior in Android. It would be nice if this app follows such interaction too.

thanks.

**Comment by y20k** [comment]
Hi @gerroon ,

I considered this option before. Slide-to-delete is great for an email client. But deleting stations is not a very commonly used option - at least in the way I use Transistor myself. Therefore I think  Slide-to-delete is not a fitting UI choice for Transistor.

So sorry to disappoint you. I think I will not implement  Slide-to-delete. 😢 

Best regards

**Comment by gerroon** [comment]
Well trying to click on : to get to delete is not too sexy on a small screen either, As a user I would like an easier way. But it sure is up to you to manage your app and time on how to dev this.

**Comment by y20k** [comment]
Deleting stations is supposed to be not a daily task. That is why I do not think **Slide** is a good fit. I agree that the three dots are not sexy at all.

Starting playback is a often used task. Maybe **Slide** would be a nice shortcut to start radio playback. On the other hand that would be a bit weird. Nobody would expect that shortcut there.

**Comment by y20k** [comment]
Forgot to close this issue. Slide to delete is not a feature I want to have for Transistor. I recognize that opinions on that topic may differ. Thanks for suggesting. Please do not feel discouraged to continue contributing here.
