### ISSUE TITLE
Update in-app documentation to show that Exoplayer makes it possible to play Opus, AAC and AAC+ formats

### ISSUE THREAD

**Issue by Cormak** [y20k/transistor#137]
I just tested Opus, AAC, and AAC+ streams and they all play just fine thanks to the new Exoplayer. 

Can we make it so the app explicitly says it can play these streams and does not show a popup calling them an unsupported format?

This radio player can definitely play all the existing streaming formats so it should tout itself as such. Yes, this is supposed to be a simple player but limiting it to OGG and mp3 was never a good long term solution as OGG is slowly being replaced by Opus and AAC streams are just as common as mp3 streams these days.

**Comment by y20k** [comment]
That is a good point. I will change the parts of the UI. 

1. I think I can delete the short pop-up toast message ([strings.xml'L94](https://github.com/y20k/transistor/blob/75bf7f12d23cd08816d50bc65edea317cd2e6b4f/app/src/main/res/values/strings.xml#L94)):
`Unsupported audio format detected. Playback of stream may not work properly.`

2. The hint that is part of the error message needs to be re-phrased ([strings.xml#L74](https://github.com/y20k/transistor/blob/75bf7f12d23cd08816d50bc65edea317cd2e6b4f/app/src/main/res/values/strings.xml#L74)):
`Hint: Transistor can only process MP3 and OGG encoded streams or URLs ending in .m3u or .pls.`

3. There is a mention of the supported protocols in the About screen ([strings.xml#L119](https://github.com/y20k/transistor/blob/75bf7f12d23cd08816d50bc65edea317cd2e6b4f/app/src/main/res/values/strings.xml#L119)) - also in ([README.md](https://github.com/y20k/transistor/blob/75bf7f12d23cd08816d50bc65edea317cd2e6b4f/README.md)):
`It currently understands streams encoded in MP3 and OGG.`

4. ... and there is a mention in Add dialog ([strings.xml#L57](https://github.com/y20k/transistor/blob/75bf7f12d23cd08816d50bc65edea317cd2e6b4f/app/src/main/res/values/strings.xml#L57)):
`You can add raw audio streams encoded in MP3 and OGG as well as streams encapsulated in PLS or M3U files.`

**Comment by y20k** [comment]
I did some changes in the UI and in the in-app documentation. See this [commit](https://github.com/y20k/transistor/commit/befba4193f67d5ff1a0c81b3b0c51145eba8abb8). Thanks for pointing me to this issue.

**Comment by y20k** [comment]
issue should be addressed in [v2.2.6](https://github.com/y20k/transistor/releases/tag/v2.2.6) ...
