### ISSUE TITLE
Small interuptions (not an "issue" really)

### ISSUE THREAD

**Issue by poet-man** [y20k/transistor#141]
Hope my English is understandable ......
What I see, are small interuptions of my stream, when I get transistor from minimalized status on my samsung tablet. It stops for a second, and goes on streaming.
Not something, I could not live with, in order to have a minimalistic app. Just an information, about an "issue" I run into.

**Comment by y20k** [comment]
Hi there. I am on vacation right now. I will look into this issue probably next week. Best regards.

**Comment by poet-man** [comment]
Guten morgen. Ich schrieb auf Englisch, weil das dort gängige Sprache scheint.
Werde das hier nochmal im Detail auf Deutsch beschreiben. Ist eindeutiger 
und fällt leichter.


Am 29. Juni 2017 22:13:40 schrieb y20k <notifications@github.com>:

**Comment by poet-man** [comment]
Hallo,

ich versuch das mal zu beschreiben. Ev. muss man damit leben, weil 
(minimalistisch) so gewollt und wäre auch kein Problem:
1) Stream läuft, ich drücke den Home-Button, um was anderes zu machen 
(Stream läuft weiter .... alles ok). Tab auf den Taskmanager (wie ich das 
nenne), also die geöffneten Apps links neben der Hometaste, zeigt mir auch 
die Transistor-App an. Tab auf diese, unterbricht den Stream kurzzeitig, 
die Meldung "Lade Stream" erscheint, und erst dann läuft es ohne 
Unterbrechung weiter.
2) Ähnlich verhält es sich, wenn ich auf den Home-Button drücke, mache was 
anderes, ziehe ev. dabei die Benachrichtigungsleiste von oben in den Screen 
(dort wird auch die Transistor-App angezeigt), dort Tab auf den 
Stopp-Button, sprich Stream endet. Ich ziehe dann die Meldung nach rechts 
aus dem Screen, so dass sie nicht mehr in der Benachrichtigungleiste 
enthalten ist. Davon ausgehend, dass die App damit geschlossen, bin ich 
überrascht, dass sie im Taskmanager doch noch enthalten ist (s.o.) ... 
wähle ich die App dort an, gibt es wieder ein kurzes "Lade Stream" und dann 
gehts weiter. Ich hätte gedacht, es wäre logischer, wenn ich im 
Benachrichtigungsbereich den Stream anhalte und aus der Leiste ziehe, dass 
dann die App auch geschlossen ist.

Nur mal so als Gedanken. Vll gibt es ja andere Auffassungen, weswegen das 
so bleiben sollte.

Gruß




Am 29. Juni 2017 10:13:40 nachm. schrieb y20k <notifications@github.com>:

**Comment by poet-man** [comment]
..... ah ja, noch was .....
auf meinem Samsung Tablet mit Nougat kann ich über den Taskbutton alle Apps 
auf einen Schlag beenden (da steht dann "alle beenden") Tab da drauf, und 
alle Apps sind geschlossen. Alle, bis auf Transistor. Die App ist dort 
nicht mehr vorhanden, Stream läuft aber weiter.


Am 29. Juni 2017 22:13:40 schrieb y20k <notifications@github.com>:

**Comment by y20k** [comment]
> Alle, bis auf Transistor. Die App ist dort nicht mehr vorhanden, Stream läuft aber weiter. 

What happens, when you tap `Alle Beenden` when you are playing back some music with the mp3 app of your choice? Does the music stop?

**Comment by poet-man** [comment]
I tried with the built in music app. When I tab on "alle beenden" the app 
closes, but the music goes on. I have to close it in the messages to stop 
music. Seems to be a general behaviour.


Am 6. Juli 2017 12:01:17 schrieb y20k <notifications@github.com>:

**Comment by poet-man** [comment]
Thanks for that!
I agree that it is a common misunderstanding, that App Switcher holds 
currently running apps. I think, that has to do with that button "alle 
beenden" (close all), which (in German) suggests, that running apps will be 
closed.
For test purposes I again installed "audials radio player", which I used 
previous to transistor. If I close all in App Switcher, stream goes on 
there, too. Means, same behaviour as with transistor.
So, this is not an issue at all.
What I would like to suggest, is, that the notification gets an "X" to 
close it. That's what I see in similar apps. So far, I have to stop 
streaming within notification, THEN to be able to swipe notification, and  
to end streaming.

That dropouts really seem to accour only with transistor (so far). I tried 
audials with that issue, and there are no dropouts, when I activate it from 
App Switcher.
Not being able, to fix that with transistor, is no problem. I can live with 
it. Above all, I am very glad, to have an app, which is not a huge packet. 
And maybe, that "problem" has got something to do with samsung, having hand 
on nougat.


Am 6. Juli 2017 13:30:56 schrieb y20k <notifications@github.com>:

**Comment by y20k** [comment]
Sorry. Since I was not able to reproduce this bug, I cannot help you. I am closing this issue for now.
