### ISSUE TITLE
Hard coded stations?

### ISSUE THREAD

**Issue by kopmazfirat** [y20k/transistor#142]
I want to hardcode 2 stations, however i am not able to do that. Could you please help me about this? 

What is the best and easiest way to do that.

Thanks for your time.

Have a good one.

**Comment by y20k** [comment]
Hi there. I am on vacation right now. I will look into this issue probably next week. Hope that is not too late. Best regards.

**Comment by kopmazfirat** [comment]
There is no need to worry. Have a good vacation!

Best regards.

**Comment by y20k** [comment]
Hi there,

we had a similar discussion a while ago. See this [discussion](https://github.com/y20k/transistor/issues/68#issuecomment-216111695) here.

A clean way (not the cleanest - but a way with not a lot to code) would be track the fist time launch of the app via `SharedPreferences`. ... and on first launch write the m3u and png files necessary to the "Collection" folder (get this folder via Transitor's `StorageHelper`). You still need to put those files for distribution of the app somewhere within the app package. I think it is best to store them somewhere in the `res` folder.

Alternative approaches can be found in the above mentioned discussion.

Best regards.

**Comment by y20k** [comment]
Closing this one. Hope I could help you.
