### ISSUE TITLE
Stream changes, when transistor comes up from recently used apps

### ISSUE THREAD

**Issue by poet-man** [y20k/transistor#143]
Maybe, somebody knows how to avoid? Thanks.
1) Open transistor app via shortcut for a stream (lets give it the name "stream1").
2) After some time, stream2 is chosen/started manually in main window of transistor app.
3) Press home-button on tablet to get to home screen, in order to use any app.
4) After finishing these actions, transistor is reactivated from recently used apps.
5) Transistor automatically starts streaming first stream in list/stream1, and doesnot go on with stream2
Regards
Axel

**Comment by y20k** [comment]
Hi there, 

thanks for the bug-report!

I think / I hope, I know what is happening behind the scenes. 

What a shortcut does, is: it is asking the system to start the app with a given set of parameters (the so called intent EXTRAs) - this case URL of station and startPlayback = true.

The task switcher is probably storing the intent and its EXTRAs to recreate the experience. I somehow need to remove the EXTRAs after playbach has started.

**Comment by poet-man** [comment]
interesting to get to know, what happens. Thanks for that.


Am 17. Juli 2017 9:35:11 vorm. schrieb y20k <notifications@github.com>:

**Comment by y20k** [comment]
Hi there,
unless I did something wrong when following your instructions, I think / I hope that the current version of Transistor fixed this bug.
Feel free to re-open this Issue, if the bug still persists.
Best regards
