### ISSUE TITLE
Add more sleeptimer options

### ISSUE THREAD

**Issue by Wiredframe** [y20k/transistor#144]
Would be awesome to be able to select the amount of minutes in the sleeptimer.

**Comment by y20k** [comment]
I wanted to keep the user interface for the sleeptimer as simple as possible. That is why I decided on a fixed length for the initial sleep timer of 15 minutes. If you tap the icon a second time another 15 minutes should be added. This way you can set the sleep timer to 15, 30, 45  etc.

**Comment by y20k** [comment]
I still think that the 15 minute sleep timer with the option do add another 15 minutes is a good solution for a simple app like Transistor.
