### ISSUE TITLE
Opus issue.

### ISSUE THREAD

**Issue by ikocevski** [y20k/transistor#146]
Opus streams won't load on Android 4.4.4. When I press play the status goes to yellow and it says loading stream to no avail. Pasting the same station link in VLC however does play, and aac streams do play so I guess it's the way Opus is implemented.

**Comment by y20k** [comment]
Hi there, thanks for reporting this!! Can you post an Opus URL that is not working for you? Opus should be supported by the audio playback library that Transistor uses (ExoPlayer). I would like to check what kind of error message I get, when I turn on the debugger while trying to play back Opus.

**Comment by ikocevski** [comment]
http://dir.xiph.org/listen/145058/listen.m3u

This is the link I tried.

Log made with MatLog in Verbose mode:
[2017-08-07-16-08-12.txt](https://github.com/y20k/transistor/files/1205060/2017-08-07-16-08-12.txt)

**Comment by y20k** [comment]
Thanks. I fired up an Emulator and I can confirm that the stream you provided does not work in Andoid 4.4. I works in newer versions of Android though.

Here is my explanation:

Transistor relies on ExoPlayer for decoding and playback. ExoPlayer in turn relies on the built-in media decoders of the Android platform. See [sample-formats](https://google.github.io/ExoPlayer/supported-formats.html#sample-formats):

> ...
> By default ExoPlayer uses Android’s platform decoders

The developer pages of Android list the supported audio-formats. See [audio-formats](https://developer.android.com/guide/topics/media/media-formats.html#audio-formats):

> ...
> Opus | Android 5.0+

But it seems that there is a way to extend the default ExoPlayer with additional decoders. Google provides an [OPUS](https://github.com/google/ExoPlayer/tree/release-v2/extensions/opus) software decoder.

I need to check how complicated it is to integrate that extension and how much work it would take to keep it up-to-date.

**Comment by ikocevski** [comment]
@y20k Thank you for looking into this. If it's too tedious to implement it, don't bother. There aren't that many OPUS streams anyway and backward compatibility is what  keeps us using these devices I must admit 😁

**Comment by y20k** [comment]
To be honest. I think "Opus on 4.4." is too much of an edge case. Sorry. I am closing this issue for now.
