### ISSUE TITLE
Kooks/2.3.x on F-Droid

### ISSUE THREAD

**Issue by CryptOwl** [y20k/transistor#147]
It doesn't look like the latest releases haven't been flagged for F-Droid.
https://f-droid.org/wiki/page/org.y20k.transistor

Would like to see the latest releases on F-Droid again.

**Comment by y20k** [comment]
Thanks for the hint. I asked them to update the app manually. There was a problem with the way Transistor stores its version number and version name. 

See [F-Droid issue tracker](https://gitlab.com/fdroid/fdroiddata/issues/855)

**Comment by y20k** [comment]
Turns out that I forgot to upload a couple of files when I updated the ExoPlayer library. F-Droid was not able to build the app. I cannot change that retrospectively. But I published a new version of the app today. That version should find its way into F-Droid automatically.
