### ISSUE TITLE
big volume knob (request)

### ISSUE THREAD

**Issue by nikoss** [y20k/transistor#150]
___

(you can skip this part)

Some brainstorming on the subject.

Let's say I am listening to radio,  with Transistor on the background, and then choose to  play a video on the Youtube. Transistor will stop, the video will be playing, and the first thing I will have to do is adjust the volume on my phone.

Then, if I want to stop the video and wish to go back to listening to the radio, with Transistor, again, I will have to adjust the volume on my phone.

Possibly, the same might need to be done when switching between radio stations.

We could say that the "volume problem" is a common issue on the web media.

Therefore, Transistor should have a volume adjustment (for itself, not for the system).

How would that adjustment look like?
From a practical point of view, it should be  a slider.
But, since this is Transistor, a retro reference might be preferred:
a big volume knob.

----

How big would that knob be?
Simply, while holding your phone with your hands, try to draw a curve or a circle, on the screen, using your thumb, as if you were turning the imaginary knob.

There you have the outline of the "big volume knob".

**Comment by y20k** [comment]
Hi there. 

Thank you for sharing your idea. I think a possible volume control should be part of a broader discussion about the Now Playing screen. I will reference to your suggestion in the issue [Make "Now Playing" screen more modern and info-focused](https://github.com/y20k/transistor/issues/136). 

And i will close this issue.

> How would that adjustment look like?
> From a practical point of view, it should be a slider.
> But, since this is Transistor, a retro reference might be preferred:
> a big volume knob.

I am very open to retro ideas 🚀 - we should discuss if this is a necessary feature given the premise that Transistor is a "bare bones" type app. But as a said maybe in the main issue thread (#136)
