### ISSUE TITLE
Translating the phrase "URL" - suggestions wanted

### ISSUE THREAD

**Issue by franciscot** [y20k/transistor#153]
Please, Can you change the tecnical name "URL" for "link" or similar? (more understandable)

Thanks.

**Comment by y20k** [comment]
I am not a native speaker. I think "streaming link" is maybe a good alternative -> see [commit](https://github.com/y20k/transistor/commit/2b5e11b3ac8cfa6b9dbfed549ab0ec545549e623)

**Comment by franciscot** [comment]
Looks good for me. English is not my fisrt language, maybe some native speaker could help us.
