### ISSUE TITLE
Add support for NextCloud Radio plugin

### ISSUE THREAD

**Issue by pejakm** [y20k/transistor#154]
Info here: https://git.project-insanity.org/onny/nextcloud-app-radio

**Comment by y20k** [comment]
Hi there, 

I am not sure what exactly you are suggesting. 

I guess you would like to use the radio stations from your NextCloud Radio somehow in Transistor, too. Be it in form of a sync feature or in form of an Import/Export feature. 

My initial comment on this would be:
* **Sync** -> probably not going to happen, sync is hard to get right and error prone 
* **Import/Export** -> maybe... depends on the format (if there is a open standard, probably a m3u playlist containing multiple stations)

Or do you want to integrate **radio-browser.info**? There was an Issue about a possible integration a while ago. See #94.  The short summary would be: Transistor will not become a browser app. There are better alternatives out there. An integration of radio-browser.info just for finding stations, is not off the table. Although I am hesitant to make Transistor reliant on third party software/services.
