### ISSUE TITLE
Add an option for Backup

### ISSUE THREAD

**Issue by AhmedNazir** [y20k/transistor#155]
After collecting some good stream url,I am disappointed. There is no backup option.What happened if something goes wrong. Should I again add  stream url one by one and rename it..

thanks for creating such a useful app. but add a backup option so that we can recover all url with edited name.
Thanks again......

**Comment by y20k** [comment]
Hi there and thanks for liking the app :-) ,

the Import/Export feature was requested before. See #126. 

Transistor implements [Auto Backup](https://developer.android.com/guide/topics/data/autobackup.html). Auto Backup should take care of restoring your stations. To be honest I do not trust the Auto Backup system completely. I personally always make a copy of the directory `/Android/data/org.y20k.transistor/files/Collection` before I switch devices.

**Comment by y20k** [comment]
I am probably not going to implement this feature in the near future. But I put it into [CONTRIBUTING.md](https://github.com/y20k/transistor/blob/master/CONTRIBUTING.md) and in [Previous discussions and feature requests](https://github.com/y20k/transistor/issues/48) to encourage an external contribution.

**Comment by AhmedNazir** [comment]
I don't believe that adding this option makes complexity.
Adding this option, we can use cloud for storing.

maximum people don't know about auto backup....

making a physical button can help increasing it's productivity....
