### ISSUE TITLE
Implement track skipping

### ISSUE THREAD

**Issue by Wiredframe** [y20k/transistor#162]
It would be great if you could implement the native track skipping methods to skip the stations in their order with either a bluetooth headset or (via third party apps like Button Mapper) long pressing the volume keys.

**Comment by rizapasha** [comment]
It is live radio bro. :)

**Comment by Wiredframe** [comment]
Thanks but I mean skipping the stations not the tracks of a radio station 😆

**Comment by y20k** [comment]
Okay. I will look into it. We had a discussion about that a couple of month ago. (see #89)

**Comment by betsythefc** [comment]
To keep it radio themed, it could be called 'Tune' or 'Seek' and that moves to the next station

**Comment by y20k** [comment]
I did re-open #89. I will try to implement a station switching via media buttons (Android Auto, Headphone buttons, Wear OS controls). 

But I am sorry, I guess that is not what you want/need. But I am against adding any new on-screen controls for **next station** and **previous station**

**Comment by rizapasha** [comment]
*Sincerely,*
Riza Fadholi Pasha,S.Si.

*Gadjah Mada University*
