### ISSUE TITLE
A couple of streams that work fine, but produce errors

### ISSUE THREAD

**Issue by stokholm** [y20k/transistor#163]
The first one produces the error: "Unsupported audio format detected.", but plays fine nonetheless:
http://drradio1-lh.akamaihd.net/i/p1_9@143503/master.m3u8

The second is a pls file, that is not recognized at all:
http://www.kanalplus.fm/rockkanalen/kp96.pls
But the stream inside (http://stream.kanalplus.fm/kp96) works fine.

**Comment by y20k** [comment]
Hi @stokholm, thanks for filing this issue. I always listen to the same ten stations and they work fine ;). I need feedback like this. I will look into it.

**Comment by jadedgnome** [comment]
this doesn't work for me, it saids "[File probably does not contain a valid streaming URL.]"

http://www.wnyc.org/stream/wnyc-fm939/mp3.pls

**Comment by y20k** [comment]
@jadedgnome 
The https version works.
https://www.wnyc.org/stream/wnyc-fm939/mp3.pls

I will create a new issue / bug report: Transistor should follow 301 redirects to https - which I thought it already did.

**Comment by y20k** [comment]
I removed the "Unsupported audio format detected" in the most recent version.
