### ISSUE TITLE
[REQUEST] design mod (transistor v3)

### ISSUE THREAD

**Issue by ralxxx** [y20k/transistor#165]
I really like the new simplified design (transistor v3), I have just one suggestion:
Especially when you have many radio stations in your list it would be helpful if the radio station that you (pre)select, is underlaid with a color, as the green dot only indicates the station that is currently playing but not indicates the station that is (pre)selected.
Example:
https://www.dropbox.com/s/opvbw8bwfq4626h/screenshotTRANSISTOR.jpg?dl=0

**Comment by y20k** [comment]
Hi there, I am actually already working in this. It took a few days living with the new interface to find out that something is missing.

**Comment by y20k** [comment]
The result looks like this. There are a few little bugs left though.

**Comment by ralxxx** [comment]
Perfect!

**Comment by y20k** [comment]
the next version includes this feature (just published it)
