### ISSUE TITLE
Cannot close player in notification drawer when stopped

### ISSUE THREAD

**Issue by bbo2adwuff** [y20k/transistor#168]
How to reproduce:
1. Start station.
2. Stop station in notification drawer (or lock screen).
3. Click on X in notification drawer to close app.

App is not closing after pressing the X, but when station not stopped (i.e. playing) then X works as expected an app is closing.

OS: Android 4.4.4
(I check old issues, but this here seems like a bug because the X works when a station is playing. So it's not the same as in https://github.com/y20k/transistor/issues/159.)

**Comment by y20k** [comment]
Hi thanks. 
thanks for pointing me to this bug. I did not test this feature under 4.4.. The next version will come with a fix.

**Comment by y20k** [comment]
[v3.0.3](https://github.com/y20k/transistor/releases/tag/v3.0.3) is out (on GitHub and Google Play and soon on F-Droid). The close icon should now work as intended on Android 4.4. Thanks again for reporting this.

**Comment by bbo2adwuff** [comment]
Wow what a quick fix!
Thanks works all as expected :)
