### ISSUE TITLE
Night Mode not Remembered

### ISSUE THREAD

**Issue by stardomains** [y20k/transistor#169]
Night Mode not remembered on restart on 3.0.4

**Comment by y20k** [comment]
Thanks for finding that! 

Night Mode is (yet) not officially supported. 

Depending on the way it is going to be implemented, it is maybe not necessary to remember the setting. If Android 9 gets an official Night Mode, which this [Medium post](https://medium.com/@chrisbanes/appcompat-v23-2-daynight-d10f90c83e94) somewhat suggests, I will probably not offer a user facing trigger for Night Mode. I that case transistor will just check the system settings at startup.

But if I implement a user facing Night Mode switch, you are right: then Transistor should absolutely remember the setting.

Right now I a somewhat stuck on the implementation of the dark menu bar. :-)

![screenshot](https://user-images.githubusercontent.com/9103935/36383803-95af3e54-158d-11e8-9584-fdf28f863146.png)

**Comment by stardomains** [comment]
I went all out on Night Mode. Put it in permanently in onCreate. And did my own AMOLED night mode as seen in pic below. Just messing around with it trying different things. 

![screenshot_20180219-104555](https://user-images.githubusercontent.com/831583/36385991-51fc9380-1562-11e8-8e6f-fd1c73711cf9.jpg)

**Comment by y20k** [comment]
If you find out how to tint the status bar icons white in Night Mode (while leaving them grey in Day Mode), please let me know.

**Comment by y20k** [comment]
I think I will go with an all black background, too. It looks nicer.

I am interested in your opinion. Do you think it is necessary to tone down the red in Night Mode? I would like to keep it the way it is, because it is somewhat part of the brand.

**Comment by y20k** [comment]
see also #172
