### ISSUE TITLE
Restart necessary when adding stations through pls download

### ISSUE THREAD

**Issue by stardomains** [y20k/transistor#170]
Go to https://somafm.com/listen/ in Android browser. 

Select a stream link that downloads pls. Example: 64k ACC on Space Station Soma.

Set Transistor to open the download automatically when prompted.

If you try again on another stream it will not import the next station. You need to close Transistor and have the download happen again.

**Comment by y20k** [comment]
Hi @stardomains 

I was just looking through the open issues tonight. I tried to reproduce the problem you described, but failed. If you find the time: Can you confirm this, too?

Best regards
