### ISSUE TITLE
Timer [bug]

### ISSUE THREAD

**Issue by mrbatcop** [y20k/transistor#173]
Hi!
I found an interesting bug!
1) Start playback
2) Minimize the app // now I can open the app with different ways
3) Open the app with the notification area (I mean below the status bar) and press timer button. 
You will see the message: Please start playback first. // BUG!
BUT, if you will do this thing: 
Open the app with the icon on the home screen and press timer button. // OK, it works!
(However, if you opened the app with the notification area first then it won't work)  
P\S The second step is optional!!!!!!
Good Luck!

**Comment by y20k** [comment]
Thanks! I will investigate.

**Comment by y20k** [comment]
The bug will be fixed in v3.0.4. Thanks again for finding and reporting it.
