### ISSUE TITLE
F-Droid doesn't have v3.0.4

### ISSUE THREAD

**Issue by mrbatcop** [y20k/transistor#177]
Hi!

I read the previous issues and I found this link:
https://gitlab.com/fdroid/fdroiddata/commits/master/metadata/org.y20k.transistor.txt
I'm sorry but I don't understand what does "Transistor: disable 3.0.4 (54)" mean? 
It means an error?

Thanks, and Good Luck!

**Comment by offa** [comment]
It seems the build has been disabled due a missing dependency.

From the [F-Droid build log](https://f-droid.org/wiki/page/org.y20k.transistor/lastbuild):

> :app:compileReleaseJavaWithJavac/home/vagrant/build/org.y20k.transistor/app/src/main/java/org/y20k/transistor/helpers/LogHelper.java:17: error: cannot find symbol
> import android.support.v4.BuildConfig;
>                          ^
>   symbol:   class BuildConfig
>   location: package android.support.v4
> 1 error
>  FAILED
> 
> FAILURE: Build failed with an exception.
>

**Comment by y20k** [comment]
Thanks. I found the problematic line of code. To be honest that looks in hindsight like a wrong selection in code-autoconplete on my part. Uups. The next version will be compile-able again for F-Droid.
