### ISSUE TITLE
App crash when adding a station

### ISSUE THREAD

**Issue by valsou** [y20k/transistor#179]
Hi,

i'm trying to add a station :
http://stream.srg-ssr.ch/couleur3/mp3_128.m3u

Every time the app crashes.
Version used : 3.0.5

**Comment by y20k** [comment]
Thanks!! That is a pretty bad bug. Thankfully it was easy to fix. [v3.0.6](https://github.com/y20k/transistor/releases/tag/v3.0.6) can handle files formatted like the one you reported. That was an important bug to report. Thank you again.
