### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Zagur** [y20k/transistor#18]
How I can translate this app? I can translate to catalan and spanish.

**Comment by y20k** [comment]
That would be wonderful! All the strings that Transistor needs are stored in one strings.xml file per language. For example: [English](https://github.com/y20k/transistor/blob/master/app/src/main/res/values/strings.xml) or [French](https://github.com/y20k/transistor/blob/master/app/src/main/res/values-fr/strings.xml).

The easy way would be: Just send me a Catalan version of that file, and I will incorporate it. 

If you have GIT running the correct way would be to fork the project, add the translation file and then issue a pull request to me.

Either way is fine with me. I am really glad you are offering your help!

**Comment by Zagur** [comment]
Awesome! Ok, I translate "Translation" to Catalan and Spanish when I have free time. And I promise to find more people to translate others languages.

**Comment by y20k** [comment]
Great. Looking forward to it. &#128077;
