### ISSUE TITLE
M3U with 4 addresses are ignored since 3.0.5

### ISSUE THREAD

**Issue by radasbona** [y20k/transistor#180]
In previous Versions the station was shown and played correctly. 
Now the station isn't shown in the list any more.

The m3u file:

http://89.39.189.52:8000/
http://gherlafm.ro:80/eurostil.m3u
http://81.196.122.19:8008/
http://83.170.76.46:8090/
http://83.170.76.46:8092/

**Comment by y20k** [comment]
This the content of the m3u file? Do you have a link? Where is it hosted?

**Comment by y20k** [comment]
I think I found the station you mentioned: http://gherlafm.ro/ If you click on the button [Listen live](http://gherlafm.ro/eurostil.m3u) you get the file http://gherlafm.ro/eurostil.m3u. 

The file contains

```
#EXTM3U
#EXTVLCOPT:network-caching=1000
http://128.gherlafm.ro
#EXTVLCOPT:network-caching=1000
http://64.gherlafm.ro
#EXTVLCOPT:network-caching=1000
http://32aac.gherlafm.ro
#EXTVLCOPT:network-caching=1000
http://96.gherlafm.ro
#EXTVLCOPT:network-caching=1000
http://89.39.189.70:8000/
#EXTVLCOPT:network-caching=1000
http://32.club.gherlafm.ro
```

It works at least on v3.0.6 (to be released today). Maybe your problem is related to #179.

**Comment by radasbona** [comment]
Yes, this is the content of my m3u. 
I've made a second just with http://89.39.189.52:8000/ That works.

All files with more than one address are ignored. 3 Stations in my list are missing.

I wait for v3.0.6. Nevertheless - great app. 👍

**Comment by radasbona** [comment]
Yes, this is the content of my m3u. 
I've made a second just with http://89.39.189.52:8000/ That works.

All files with more than one address are ignored. 3 Stations in my list are missing.

I wait for v3.0.6. Nevertheless - great app. 👍

**Comment by radasbona** [comment]
Issue is still there in v3.0.6. 

I chanced all m3u files to one address files. The missing stations are displayed now again.
Before 3.0.5 multi address files were no problem. 

(for example: the bavarian Rundfunk also offered multi address files to download)

**Comment by y20k** [comment]
Okay. Thanks. I probably have a wrong understanding of the problem. From version 3.0.3 on there is a select dialog for the radio streams contained in an m3u or pls file. That dialog works fine on my testing devices (screenshots below).

Before v3.0.3 Transistor **just took the first stream** it found in an m3u or pls file and ran with it.

I guess both ways of dealing with a m3u or pls playlists are not ideal. Better would be probably if Transistor saved all the addresses in a playlist to keep them as backup in case one ot the streams fais, right?

![screenshot_20180415-143349](https://user-images.githubusercontent.com/9103935/38778546-8c8f887a-40bb-11e8-8ec1-15238b3454c2.jpg)
![screenshot_20180415-143626](https://user-images.githubusercontent.com/9103935/38778547-8ca6c49a-40bb-11e8-952a-19a4a7959b5d.jpg)
