### ISSUE TITLE
Writing to external storage seems to fail, app handles this poorly

### ISSUE THREAD

**Issue by pickx** [y20k/transistor#182]
Underlying issue:
- The app has storage permissions enabled.
- /sdcard1/Android/org.y20k.transistor/files/Collection/ is created. 
- Adding a new station works, either by opening the stream file from a file browser, by opening it from the browser, or by manually inputting the url. That is, a stream is added to the list and can be played. However, no file is created under the /files/Collection/ directory.

I believe this is due to a bug in my device: https://github.com/sonyxperiadev/bug_tracker/issues/125 and that's obviously not Transistor's fault. However I'm opening this bug report due to Transistor's handling of this error:

1. Adding a new stream works. As mentioned, no file is created on the sdcard. The user is not informed that a file was not created.
2. Attempting to change a stream's icon launches the gallery. However, after an image is chosen it is not updated and user is not informed that an error occurred. 
3. Exiting the app via back button, or changing to a different app via multitasking, will result in it launching next time with an empty stream list. User is not warned before app is closed.
4. Refreshing the stream lists via pull-to-refresh will cause the entire stream list to be deleted. User is not informed why streams were deleted. I would argue that even if the refresh finds that some stream files have been removed from the SD card, the user should be warned that they'll be removed from the list.

As an aside, the app's minimal interface makes these issues especially frustrating, as there is no way to understand what's going on and why data keeps getting deleted. I thought the app hasn't even implemented saving the state of the stream library until I read the github page.

Thanks for reading.

**Comment by y20k** [comment]
Hi there,

that is a very interesting bug. Transistor should not need any permissions to be able to store files under the /Android folder. This folder is part of the so-called [External Storage](https://commonsware.com/blog/2014/04/08/storage-situation-external-storage.html). 

The fact that there is a sub-folder `Collection`  means that Transistor is in principle able to write stuff into its /Android subdirectory. Transistor creates the folder [here](https://github.com/y20k/transistor/blob/v3.0.6/app/src/main/java/org/y20k/transistor/helpers/StationListHelper.java#L127). The path to its /Android subdirectory is determined [here](https://github.com/y20k/transistor/blob/v3.0.6/app/src/main/java/org/y20k/transistor/helpers/StorageHelper.java#L58). 

It is interesting on the other hand that Transistor is not able to write the playlist file into the `Collection` folder (done [here](https://github.com/y20k/transistor/blob/v3.0.6/app/src/main/java/org/y20k/transistor/MainActivity.java#L171)). At least your observation / bug description suggests that this is the problem.

I am not sure how that fits in with the observation that the OS on your phone mounts the SD card in a wrong(?) way. Transistor can create a subdirectory, but not a folder? I am not sure on how to start to debug the problem. 

A starting point may be: Transistor creates an empty and hidden file named `.nomedia` into the `Collection` directory (see [here](https://github.com/y20k/transistor/blob/v3.0.6/app/src/main/java/org/y20k/transistor/helpers/StationListHelper.java#L133)). It would be interesting to see it it succeeded in doing so on your device.

**Comment by pickx** [comment]
It did not, the Collection directory is empty. Apparently this is a known problem with custom ROMs on this phone. Though I haven't tried it, users on XDA have reported only being able to save 0kb files, even with "popular" apps like Spotify. I have yet to try this on anything other than Transistor.

**Comment by y20k** [comment]
So if understand the problem correctly, Transistor should work as expected, if no sd-card is inserted. Because in that case the OS should offer a part of its normal storage as External Storage, right?

I wonder if Transistor's [method](https://github.com/y20k/transistor/blob/v3.0.6/app/src/main/java/org/y20k/transistor/helpers/StorageHelper.java#L58) that gets the path to the external storage could be modified. Maybe the Android method [getExternalFilesDirs()](https://developer.android.com/reference/android/content/Context.html#getExternalFilesDirs(java.lang.String)), will surface multiple External Storage choices, the one from the sd card and the one from internal storage? 

All that is hard to test without your particular kind of phone at hand.

What I can and should do is: make simple [check](https://developer.android.com/training/data-storage/files#CheckExternalAvail) if the `Collection` folder is writable and warn the user if not.

**Comment by y20k** [comment]
Sorry since I do not get a feedback from the OS that the SD is not mounted in your special case, I am not sure on what to do. That is why I closed the issue.
