### ISSUE TITLE
Could it be possible to automatically play a radio when Transistor starts ?

### ISSUE THREAD

**Issue by yellowiscool** [y20k/transistor#183]
I would like to have a default radio that automatically plays when the application is started. So I can ask my phone to start Transistor using Google Assistant or similar.

Is it something possible or does Android have a limitation against that ? I tried a few Radio apps and I didn't find any doing that except the Radio France apps such as France Inter (but these apps display ads at startup sometimes, requiring an action…).

**Comment by y20k** [comment]
Sorry, but I don't see Transistor getting an option like this.

But try the option `Place on Home screen` with you favorite station within Transistor. It should work the way you invisioned, if you can get you the Assistant to start a Home screen shortcut somehow. If you can get this to work, I would be interested in how you did it. I don't have Assistant on my phone right now.

**Comment by yellowiscool** [comment]
Hei,

Yes from what I saw, the assistant can start Transistor, but not the home screen shortcut. It's not a huge issue for me. Thanks for this app that doesn't contain ads and trackers.
