### ISSUE TITLE
Show last played station when opening Transistor on Android Auto

### ISSUE THREAD

**Issue by c00ller** [y20k/transistor#186]
When opening Transistor in Android Auto, we get the screen that says, "To play something, open the menu at the top left." Instead, how about showing the last played station, with the play button ready to press? This would be consistent with the standalone app UI and other music apps in Android Auto. I think this would be the final polish needed for the Android Auto experience.

**Comment by y20k** [comment]
You are right. Let's see if there is an easy way to implement this. :-)

**Comment by y20k** [comment]
It took a while but this will be implemented (see #285). I am closing this issue here in favor of the newer one.
