### ISSUE TITLE
Accented characters in title/artists show as �

### ISSUE THREAD

**Issue by nowster** [y20k/transistor#188]
Accented characters (eg. á, ç) in titles and artist names are showing up as � (U+FFFD) in the display.

I'm using Icecast2 2.4.3 fed by liquidsoap 1.1.1. They are being sent UTF-8 encoded metadata strings.

Other players (eg. XiaaLive, deadbeef) show the accented characters in the title/artist correctly.

VLC just ignores any metadata that's not plain ASCII.

The mojibake we'd get from a UTF-8 string being interpreted as ISO-8859-1 would start with "Â", so this doesn't look as if it's the problem.

**Comment by y20k** [comment]
I will look into that. I think that the [IcyInputStream](https://github.com/y20k/transistor/blob/master/app/src/main/java/org/y20k/transistor/helpers/IcyInputStream.java) class, that I use, [constructs](https://docs.oracle.com/javase/6/docs/api/java/lang/String.html#String(byte[],%20int,%20int,%20java.lang.String)) the metadata string not using any encoding info.
I am not sure how to detect the correct encoding. But that is probably just a Google search away.

**Comment by y20k** [comment]
@nowster can you post a publicly accessible stream for me to test solutions? THX.

**Comment by nowster** [comment]
Apologies for the noise.

Icecast2 defaults to using Latin1 (ISO-8859-1) and so does liquidsoap when talking to Icecast2, even if you give it UTF-8 input.

**Comment by y20k** [comment]
Sorry. I am confused. Does that mean Transistor is basically doing the right thing?

**Comment by nowster** [comment]
There's no signalling of which charset is in use in the ICY metadata protocol. Icecast1 defaulted to UTF-8. Icecast2 changed its default to Latin1 (even when the incoming metadata is UTF-8) unless configured otherwise, due to historic compatibility problems with some players.

Transistor is handling UTF-8 correctly. However, the majority of Icecast servers will be sending Latin1.

Perhaps if a UTF-8 validation fails on the artist/title fields, it should attempt a charset translation from iso-8859-1 to UTF-8?

**Comment by y20k** [comment]
Do you know of a stream that is **definitely and always** Latin1? I need a test case.

**Comment by nowster** [comment]
I've set up one temporarily: http://icecast.nowster.org.uk:8000/test.aac

Artist is "Bïttên bÿ a Møøße ©Ãrtist"
Title is "Déjà Vu Ç°"

The last word in each field contains a false UTF-8 trigger.

**Comment by y20k** [comment]
Wow. Thank you. That is very helpful! My fist [approach](https://github.com/y20k/transistor/commit/223c3ad9d8e36ff2f3878b76d4fe7cd16dc19f6f) did not solve the problem though :-)

**Comment by nowster** [comment]
You're probably best wrapping a try-catch round something that tries to validate the string as UTF-8, then falling back to Latin1 in the exception handling.

**Comment by y20k** [comment]
I tried to use [juniversalchardet](https://github.com/albfernandez/juniversalchardet) at first. But I try to keep external dependencies to a minimum. So I [opted](https://github.com/y20k/transistor/commit/14d9a2a35c53c1fc9574d6865b89836fcbe42e8b) for the approach you suggested.

> something that tries to validate the string as UTF-8

It works for the test-stream you set up. I will ship the Latin1-fallback with the next version of Transistor.

**Comment by y20k** [comment]
If you want to test the solution, here is a test APK:

- [transistor-app-test-3.0.9-01.apk](https://www.dropbox.com/s/zrs5ek7xkmqegfa/transistor-app-test-3.0.9-01.apk?dl=0)

**Comment by y20k** [comment]
... and a test APK with the simplified UTF-8 check

- [transistor-app-test-3.0.9-02.apk](https://www.dropbox.com/s/o3ewtfk0by4ugt6/transistor-app-test-3.0.9-02.apk?dl=0)

**Comment by y20k** [comment]
> Shall I change the stream to use UTF-8 now?

Yes. Good idea.

**Comment by nowster** [comment]
Done. The stream is now UTF-8, and it seems to be working fine with the test .apk.

**Comment by y20k** [comment]
Summertime. I totally forgot to publish an updated version of Transistor that includes the Latin1 fix. Today I remembered....

* [v3.0.9](https://github.com/y20k/transistor/releases/tag/v3.0.9) is out

Time to close this issue. Thanks for helping me out here!!
