### ISSUE TITLE
Audio is not routed through AudioFX on LOS 15.1

### ISSUE THREAD

**Issue by cyberbix** [y20k/transistor#189]
On my Samsung A320FL (inofficial) LOS 15.1, audio seems not to be routed through AudioFX equalizer.

**Comment by y20k** [comment]
Sorry. But I do not know how to achieve that. I marked this issue as "help wanted".

**Comment by cyberbix** [comment]
Hello y20k,

thanks for getting back and thanks for your great work delivering a minimalistic stream player. Excellent !

I found this https://github.com/therealahrion/Audio-Compatibility-Patch.

I didn´t test it yet with Magisk, but I will give you results when done.

Regards
Peter


Von: y20k <notifications@github.com>
Gesendet: Mittwoch, 19. September 2018 21:35
An: y20k/transistor <transistor@noreply.github.com>
Cc: cyberbix <peter@cyberbix.de>; Author <author@noreply.github.com>
Betreff: Re: [y20k/transistor] Audio is not routed through AudioFX on LOS 15.1 (#189)


Sorry. But I do not know how to achieve that. I marked this issue as "help wanted".

**Comment by y20k** [comment]
I upgraded my phone to Lineage OS - and now I am able to test the AudioFX integration. I think I found a solution. Are you interested in testing?

* [transistor-app-testing-3.1.1-001.apk](https://drive.google.com/file/d/1D7zQtxafNmR11PkpGI_E0KNgEVFuDO0y/view?usp=sharing)

PS. Happy New Year 🎆

**Comment by cyberbix** [comment]
Great! I'll try and give you feedback.

Greets.
Peter


________________________________
Von: y20k <notifications@github.com>
Gesendet: Mittwoch, 2. Januar 2019 17:42
An: y20k/transistor
Cc: cyberbix; Author
Betreff: Re: [y20k/transistor] Audio is not routed through AudioFX on LOS 15.1 (#189)


I upgraded my phone to Lineage OS - and now I am able to test the AudioFX integration. I think I found a solution. Are you interested in testing?

  *   transistor-app-testing-3.1.1-001.apk<https://drive.google.com/file/d/1D7zQtxafNmR11PkpGI_E0KNgEVFuDO0y/view?usp=sharing>

PS. Happy New Year 🎆

**Comment by y20k** [comment]
Hi. 

Me again. I found a bug in my AudioFX integration. The app crashes after playback has been stopped - you need to wait a couple of minutes. This version here should prevent the crash.

* [transistor-app-testing-3.1.1-002.apk](https://drive.google.com/file/d/1ihaBsfrMoFimuOsOa9EqSftg4PSl2tdH/view?usp=sharing)

**Comment by cyberbix** [comment]
Tested on LOS 15. Works like a charme. Great job.


________________________________
Von: y20k <notifications@github.com>
Gesendet: Donnerstag, 3. Januar 2019 10:46
An: y20k/transistor
Cc: cyberbix; Author
Betreff: Re: [y20k/transistor] Audio is not routed through AudioFX on LOS 15.1 (#189)


Hi.

Me again. I found a bug in my AudioFX integration. The app crashes after playback has been stopped - you need to wait a couple of minutes. This version here should prevent the crash.

  *   transistor-app-testing-3.1.1-002.apk<https://drive.google.com/file/d/1ihaBsfrMoFimuOsOa9EqSftg4PSl2tdH/view?usp=sharing>

**Comment by y20k** [comment]
@cyberbix thankyou for testing! I think I will wait a couple of days before I publish a new version in the Play Store. I would like to make sure that no new bug was introduced. If you find anything unusual in the next few days please drop me a note.

**Comment by y20k** [comment]
@cyberbix is the test version still running fine? if so, I think I can publish the changes.

**Comment by cyberbix** [comment]
Run´s almost every day, audio routing still goes through AudioFX !

Great work. Thanks again.

Von: y20k <notifications@github.com>
Gesendet: Dienstag, 15. Januar 2019 12:59
An: y20k/transistor <transistor@noreply.github.com>
Cc: cyberbix <peter@cyberbix.de>; Mention <mention@noreply.github.com>
Betreff: Re: [y20k/transistor] Audio is not routed through AudioFX on LOS 15.1 (#189)


@cyberbix<https://github.com/cyberbix> is the test version still running fine? if so, I think I can publish the changes.

**Comment by y20k** [comment]
I published a new version ([v3.1.1](https://github.com/y20k/transistor/releases/tag/v3.1.1)) of Transistor earlier today that includes the new feature. It is available on Google Play and will be on F-Droid soon (It may take up to a few days until F-Droid will pick up and process the changes.). I think this issue can be closed.
