### ISSUE TITLE
Balance size of icon at top of screen

### ISSUE THREAD

**Issue by PanderMusubi** [y20k/transistor#194]
Please, balance size of icon at top of screen. Tune it be in better relation to other icons there.

See screenshot for proposal.

![screenshot_20181002-091710](https://user-images.githubusercontent.com/198964/47224799-b8a60300-d3bc-11e8-86e3-ae2c43522314.jpg)

**Comment by y20k** [comment]
Thank you for reporting this. It has been a while since I touched the status bar icon. I thought I did everything correct. I re-read the [dev guidelines](https://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar#size11). They state:

> You can also include a few pixels of padding in status bar icons to maintain a consistent visual weight with adjacent icons. For example, a 48 x 48 pixel xhdpi status bar icon can contain a 44 x 44 pixel shape with 2 pixels on each side for padding.

The [current icon](https://github.com/y20k/transistor/blob/master/app/src/main/res/drawable-xxxhdpi/ic_notification_app_icon_white_24dp.png) fills the room it has without padding. I probably overlooked this, when I created the icon. Now I need to find the original illustrator file and shrink the icon a bit.

**Comment by PanderMusubi** [comment]
Yes, if you resize the icon, it will also get proportionally a bet less wide, which is good.

**Comment by Riotous** [comment]
@y20k I like the new icon, but don't you think the radio is a bit too small for the blue squircle it is inside? Perhaps make it a little bigger?

**Comment by y20k** [comment]
Hi @Riotous,

the icon is not final. I create the icon set using Android Studio. There you need to scale the [foreground](https://github.com/y20k/transistor/blob/master/assets/transistor-app-icon-current-without-background.png) to match a background (color 3C98DB). The resulting icon are created automatically using this scale factor.

Here a few screenshots of different percent settings:

**67 percent**
(the current setting, as far as I remember)
![67-percent](https://user-images.githubusercontent.com/9103935/47990741-90badd00-e0e8-11e8-8307-eb4dced39959.png)

**72 percent**
![72-percent](https://user-images.githubusercontent.com/9103935/47990753-9a444500-e0e8-11e8-9a63-e7479a1e30de.png)

**80 percent**
![80-percent](https://user-images.githubusercontent.com/9103935/47990764-a3cdad00-e0e8-11e8-9f13-6153171b316e.png)

**And this is how the current icon looks in comparison**
![screenshot_20181105-082830-50](https://user-images.githubusercontent.com/9103935/47990882-f73ffb00-e0e8-11e8-8c78-b57a0249118d.png)

**Comment by Riotous** [comment]
@y20k I think 72% looks good. Not too big, not too small. 67% leaves a lot of empty space between the radio and the squircle/circle, especially in the Play Store icon, where many people will get their first impression. 80% is definitely too big. Somewhere around 72 -75% is the sweet spot.

**Comment by y20k** [comment]
@Riotous FYI: The current version of the icon is scaled to 75%

**Comment by y20k** [comment]
[v3.1.0](https://github.com/y20k/transistor/releases/tag/v3.1.0) is out. It has a new icon. Problem should be resolved. Please open a new issue, if the problem persists.
