### ISSUE TITLE
Offer Transistor as a music playing application when headphones are plugged in

### ISSUE THREAD

**Issue by steelman** [y20k/transistor#205]
Android offers users a choice of application to start when headphones are plugged in. AFAIK no code is required, just proper [configuration](https://github.com/vanilla-music/vanilla/issues/325). Please configure Transistor to appear on the list.

BTW. This is a fine app. Thank you.

**Comment by y20k** [comment]
Hi @steelman ,

Thanks for suggesting this feature. As far as I can see in the [commit](https://github.com/vanilla-music/vanilla/commit/a7bc9c7cc4225a20d06fda3ec87372722db016e8) you mentioned, I would need add CATEGORY_APP_MUSIC in the app manifest. Apps with CATEGORY_APP_MUSIC will show up, when headphones are plugged in (depending on the OS, I think). 

Anyway. The [API reference](https://developer.android.com/reference/android/content/Intent.html#CATEGORY_APP_MUSIC) says: 
`Used with ACTION_MAIN to launch the music application. The activity should be able to play, browse, or manipulate music files stored on the device. `

I am not completely sure if Transistor qualifies.

**Comment by steelman** [comment]
Transistor can be considered a "music application". If we consider how [RFC 2119](https://tools.ietf.org/html/rfc2119) defines "SHOULD", Transistor meets the conditions described in the API reference. And users are still free to choose other applications.

Anyway, as a user I think this way of launching "listening apps" is very convenient.

**Comment by y20k** [comment]
I added `CATEGORY_APP_MUSIC` to the manifest. There is a test-version of upcoming v3.1.1 release. If you find the time I would be interested if this provides the feature you requested. On my phone (OnePlus 5) there is no feature that prompts the user after a headphone has been plugged in.

* [transistor-app-testing-3.1.1-001.apk](https://www.dropbox.com/s/ayr6sznaudl807j/transistor-app-testing-3.1.1-001.apk?dl=0)

**Comment by steelman** [comment]
I am afraid it doesn't work as expected.  I've got only Vanill and the default Music on the screen :-(

**Comment by y20k** [comment]
Yep. That is the next thing I going to try. I just wanted to make sure not to add unnecessary stuff :smiley:

**Comment by y20k** [comment]
here an APK in which I also added `<category android:name="android.intent.category.DEFAULT" />`

* [transistor-app-testing-3.1.1-002.apk](https://www.dropbox.com/s/h1vlkf8591kmd0a/transistor-app-testing-3.1.1-002.apk?dl=0)

**Comment by steelman** [comment]
:1st_place_medal:

**Comment by y20k** [comment]
I published a new version ([v3.1.1](https://github.com/y20k/transistor/releases/tag/v3.1.1)) of Transistor earlier today that includes the new feature. It is available on Google Play and will be on F-Droid soon (It may take up to a few days until F-Droid will pick up and process the changes.). I think this issue can be closed.
