### ISSUE TITLE
ugly stream icons

### ISSUE THREAD

**Issue by 532910** [y20k/transistor#210]
A lot of space is eaten with a useless grey outline:

![screenshot_20190128-191743_transistor](https://user-images.githubusercontent.com/14617699/51849971-d70f8900-2331-11e9-8bdf-00c1725a7679.png)

**Comment by y20k** [comment]
Hi @c-e-p-x-u-o ,

Transistor tries to grab favicons (for example this [one](https://www.radiobremen.de/favicon.ico)). The current size seemed to be the maximum to which a standard 16x16 favicon can be resized.

You can change the station icon manually. In that case you most definitely will have a larger icon. So I could treat larger icons differently. That in turn would lead to a confusing / ugly user interface - imagine smaller favicon icons with a grey border and larger icons side by side. That I definitely do not want that.

I could give up-scaling favicons another try. If I can make 16x16 icons look decent on 172x172, I should change to a layout without the grey border.

**Comment by y20k** [comment]
I still have no idea how to solve this problem. 16x16 is just too small for larger icons. I am adding this issue to [Previous discussions and feature requests #readmefirst](https://github.com/y20k/transistor/issues/48). Maybe another contributor wants to give a try.

**Comment by 532910** [comment]
> You can change the station icon manually. In that case you most definitely will have a larger icon.

All station images on the screenshot are manually defined and are 400x400 px size.

**Comment by 532910** [comment]
Please reopen untill fixed.

**Comment by y20k** [comment]
**Okayokay :-) Let me give it a second try.** 

My main concern are NOT the manually added icons, but the default 16x16 icons that Transistor gets from the Webserver. They look pretty bad when blown up.

Anyway. Since you are so insisting, I thought I could give the idea at least a try. And I must say that I kind of like the results. They definitely look nice with high-res station images.

Interested in a test? Here is a preview APK.

- [transistor-app-testing-3.1.3-001.apk](https://drive.google.com/file/d/1m_RklJONlnhd5YAtk_Bk3vGvMuZs867d/view?usp=sharing)

### Screenshots v3.1.3
<a href="https://user-images.githubusercontent.com/9103935/57163433-80629100-6df1-11e9-82b5-e67c5e4b1c54.png"><img src="https://user-images.githubusercontent.com/9103935/57163433-80629100-6df1-11e9-82b5-e67c5e4b1c54.png" width="300" /></a><a href="https://user-images.githubusercontent.com/9103935/57163435-80629100-6df1-11e9-9830-5568a853fd0b.png"><img src="https://user-images.githubusercontent.com/9103935/57163435-80629100-6df1-11e9-9830-5568a853fd0b.png" width="300" /></a>

**Comment by 532910** [comment]
Awesome!
![image](https://user-images.githubusercontent.com/14617699/57165302-5748fd00-6dff-11e9-9d9a-8204c9b4d533.png)

**Comment by 532910** [comment]
Home screen icons become adaptive, without useless gray radio background, but still ugly:

![image](https://user-images.githubusercontent.com/14617699/57165389-9d05c580-6dff-11e9-8632-d12d17101a71.png)

**Comment by y20k** [comment]
I did not optimize the home screen icons yet. I will drop the radio icon background to see what this would look like. I will drop you a note, when I am done with that.

**Comment by Pentaphon** [comment]
Thank god. This looks so much better now.

**Comment by y20k** [comment]
I did change the way home screen icons are composed. They are now just the station icon with the app icon overlayed by the system.

* [transistor-app-testing-3.1.3-002.apk](https://drive.google.com/file/d/1uDXLrXz2l7rbIUt0NAMDLsd-qy3-CuTg/view?usp=sharing)

Also: Station icons now have slightly rounded corners.

**Comment by 532910** [comment]
> I did change the way home screen icons are composed. They are now just the station icon with the app icon overlayed by the system.

I see no difference with 3.1.3-001

> Station icons now have slightly rounded corners.

Looks fine.

**Comment by y20k** [comment]
Which version of Android are you using? I will try to replicate the behavior in an Emulator (setting new shortcuts works on my phone as described). Cheers

**Comment by y20k** [comment]
Just a short note: I can reproduce to incorrect behavior of the create shortcut feature now too. I am on it.

**Comment by 532910** [comment]
LineageOS 16.0 Android 9

**Comment by y20k** [comment]
> LineageOS 16.0 Android 9

Same here. I made a screen recording on my phone. I think it works now as intended. Here is an updated APK:

* [transistor-app-testing-3.1.3-003.apk](https://drive.google.com/file/d/1T9s1lnZ8XrV40ag4jdDtmU82UAPMwWeo/view?usp=sharing)

You may need to uninstall and re-install the test app.

![create-shortcut](https://user-images.githubusercontent.com/9103935/57303808-69b48680-70de-11e9-90cb-e059db28108a.gif)

**Comment by 532910** [comment]
Unfortunately no:
![image](https://user-images.githubusercontent.com/14617699/57304390-eac44b80-70e7-11e9-9443-4505f6dcae2d.png)

**Comment by y20k** [comment]
:-(

If you closely compare the screenshot you sent today with the one you sent yesterday, you can see that yesterday the old radio icon was still on a layer behind the station icon. The grey antenna was peeking out from behind.

The strange thing is that there is a white border around the station icon. That maybe a feature of the LOS launcher (I am using Nova Launcher). Not sure if I can do anything about that. I will investigate.

**Comment by 532910** [comment]
> If you closely compare the screenshot you sent today with the one you sent yesterday, you can see that yesterday the old radio icon was still on a layer behind the station icon. The grey antenna was peeking out from behind.

Yes, I've noted this. 3.1.3-003 looks better than 3.1.3-001

> The strange thing is that there is a white border around the station icon. That maybe a feature of the LOS launcher (I am using Nova Launcher). Not sure if I can do anything about that. I will investigate.

It's definitely not a Trebuchet (LOS launcher) problem as contact shortcuts has no white border at all:

![image](https://user-images.githubusercontent.com/14617699/57306331-4e9c4380-70eb-11e9-923c-ed82a473cb74.png)

**Comment by y20k** [comment]
Just a question. Those contact icons are cropped, right? Should Transistor crop the station icons as well?

**Comment by y20k** [comment]
Pointing me to the LOS Contacts app helped. I found out what they are doing differently. The contacts app uses [`IconCompat.createWithAdaptiveBitmap(icon)`](https://github.com/LineageOS/android_packages_apps_Contacts/blob/cd6ccaff99386a173bbbe1814274bc297e352b60/src/com/android/contacts/ShortcutIntentBuilder.java#L302). 

Anyway. I compiled an APK using this method. What do you think? Better? The icons now get cropped to fit the adaptive icon shape - in your case that would be "squircle".

- [transistor-app-testing-3.1.3-004.apk](https://drive.google.com/file/d/1Wxt7v6KxWpHacc0M4g-Iq3ThZ-jLVBWB/view?usp=sharing)

**Comment by y20k** [comment]
Note to self: I should add 25% colored padding to the station icons, when used as home screen shortcuts, to not have them cropped. See: https://source.android.com/devices/tech/display/adaptive-icons#known-issues

**Comment by 532910** [comment]
Wow! You are reading my mind! Yesterday I thought how it should look in my ideal world and how to describe it and today you've implemented this. Awesome!

![image](https://user-images.githubusercontent.com/14617699/57405347-e29f0580-71e6-11e9-9563-bef0aa67d014.png)

**Comment by 532910** [comment]
Wow! You are reading my mind! Yesterday I thought how it should look in my ideal world and how to describe it and today you've implemented this. Awesome!

![image](https://user-images.githubusercontent.com/14617699/57405347-e29f0580-71e6-11e9-9563-bef0aa67d014.png)

**Comment by 532910** [comment]
Wow! You are reading my mind! Yesterday I thought how it should look in my ideal world and how to describe it and today you've implemented this. Awesome!

![image](https://user-images.githubusercontent.com/14617699/57405347-e29f0580-71e6-11e9-9563-bef0aa67d014.png)
