### ISSUE TITLE
ugly shortcut icons

### ISSUE THREAD

**Issue by 532910** [y20k/transistor#211]
1. The icon is not oreo-adaptive.
2. The stream picture is too small.
3. Useless grey radio background. The small blue transistor sticker is enough to understand what the app is it.

![image](https://user-images.githubusercontent.com/14617699/51850355-9f551100-2332-11e9-8a5e-8815cef8c93d.png)

**Comment by y20k** [comment]
This issue is related to #210. I will change the shortcut icons, if there is a good solution for larger icons without the grey back in the main app.

**Comment by 532910** [comment]
No, this issue is mainly about to remove grey radio background and making icon adaptive shape.
