### ISSUE TITLE
Feature Request: Add a fine grained volume control

### ISSUE THREAD

**Issue by martinstingl** [y20k/transistor#213]
The buillt in volume adjustment in Android is very coarse. Often too coarse, especially when listening at low listening volumes you often want to have intermediate steps.

According to https://android.stackexchange.com/questions/46979/ there is no easy way to get a finer resolution within Android.

It would be fine if transistor had its own fine grained volume control.

**Comment by y20k** [comment]
Hi @martinstingl Thanks for suggesting this feature! I thought about it. I in general understand the problem, but I came to the conclusion that this feature would not be a good fit for Transistor. Transistor is supposed to be a very bare bones app with as few features as possible. In my point of view a custom volume control is not part of the basic core functionality a radio app should offer. Additionally I think volume control really is a system-wide feature. 
PS. Don't feel bad I often reject feature requests. 🙂

**Comment by martinstingl** [comment]
I understand your point. But because the operating system Transistor is running on is lacking this very basic feature, currently I have to use another loudness app which is not a very "bare bone" user experience.
