### ISSUE TITLE
Play password protected streams

### ISSUE THREAD

**Issue by hosewiejacke** [y20k/transistor#217]
First of all: thanks for this app! :thumbsup:

One of the streams I'd like to add to Transistor is password protected. It has this form: `http://USERNAME:PASSWORD@example.com/stream`. Is there a trick how to convince Transistor to add (and play) such a URL?

**Comment by y20k** [comment]
@hosewiejacke I am curious. Did it work?

**Comment by hosewiejacke** [comment]
@y20k, thanks for asking! Sorry for not giving you a feedback earlier.

Unfortunately, the trick didn't work for me. It seems my device (running LineageOS) uses `/data/data/` instead of `/Android/data`. So I created the file `/data/data/org.y20k.transistor/files/Collection/test.m3u`. But Transistor didn't show the station.

After some looking around I found `/data/data/org.y20k.transistor/shared_prefs/org.y20k.transistor_preferences.xml` which contained the last (public) station I
listened to. Manually editing this file didn't work either: the URL just got overwritten.

If you have the time to take a closer look (which I would appreciate), here is a station, that just replays music from YouTube:

    http://test.bscomp.xyz/yt
    Username: git
    Password: hub

(Please be aware that is old classical music from german artists. Hopefully you can stand it a little bit...)

**Comment by y20k** [comment]
I totally forgot to answer. I tried out this stream, but I could not get it to work. That is not to say that this is not possible. Authentication is not rocket science. But I am very short on time and this is an edge case feature. That is why I am closing this issue. 

I am adding it to the issue [Previous discussions and feature requests #readmefirst](https://github.com/y20k/transistor/issues/48). Maybe another contributor to the project wants to implement this.

**Comment by hosewiejacke** [comment]
I totaly understand. Thanks for taking a look at it!
