### ISSUE TITLE
only show or update currently playing 

### ISSUE THREAD

**Issue by HoWilgh** [y20k/transistor#218]
Hi, 
I sometimes use transistor to find out which song is currently playing on my favorite radio station (when listening via Fm).
I suggest the possibility to update the "currently playing" entry without starting to play the stream. 
It's this easily possible? 
BR, 
Howil

**Comment by y20k** [comment]
> I sometimes use transistor to find out which song is currently playing on my favorite radio station (when listening via Fm).

I know exactly what you mean :-). 

Anyway. The metadata is embedded in the stream. I would need to start a "silent" stream each time a station is selected. That is way too much network-load for such a feature. So I think I will offer such a feature. Sorry. But I like the idea. 😃

**Comment by HoWilgh** [comment]
I suggest to add an update button which gives a hint when used the first time. The used data should be in the 100kb range??
You are right that an update for each stream when selecting it would generate to much traffic.
