### ISSUE TITLE
Making own app based on Transistor

### ISSUE THREAD

**Issue by ivellios1988** [y20k/transistor#221]
Sorry if this question is a little stupid. Can users create their own apps based on Transistor? I'm looking for a solution to create an official app for my web radio and, so far, Transistor seems to be the only app that suits my needs (simplicity, ability to play OPUS streams with no problems, etc.). Can I use the source code of Transistor for my own app?

**Comment by y20k** [comment]
Sure - go ahead. You should change the name of the app and give it a new icon. Have fun
