### ISSUE TITLE
wrong sample rate

### ISSUE THREAD

**Issue by 532910** [y20k/transistor#223]
```
% mpv http://ice4.somafm.com/fluid-128-aac
Playing: http://ice4.somafm.com/fluid-128-aac
 (+) Audio --aid=1 (aac 2ch 44100Hz)
AO: [pulse] 44100Hz stereo 2ch float
```

![image](https://user-images.githubusercontent.com/14617699/59465581-e9e3af80-8e33-11e9-8d12-158c667fcd3f.png)

**Comment by y20k** [comment]
Thanks for reporting this error!!

Transistor gets the information about the sample rate of a stream from the library ExoPlayer, that the app uses for playback. There is not much I can do here. I could file a bug upstream I guess.

**Comment by 532910** [comment]
You should hide sample rate to not confuse users untill it correct.

**Comment by y20k** [comment]
The upcoming v4 does not display "MIME type", "Channel count", "Sample rate" anymore. That "solves" this issue. I know that seems like cheating

Reason for the removal: For me the only interesting metric was bitrate - and that is not that easy to get (see #121). To I decided for the v4 redesign (#251) to drop the codec info section altogether.

**Comment by 532910** [comment]
It's definitely better to display nothing, than display wrong values.
