### ISSUE TITLE
Playback stops after each song with MPD + opustags

### ISSUE THREAD

**Issue by tastytea** [y20k/transistor#224]
Transistor version: 3.1.2 (F-Droid)  
MPD version: 0.21.10

I stream music via MPD's httpd-output. When `opustags` is set to "no", transistor is playing it fine. When `opustags` is set to "yes", transistor stops after each track but the dot is still green. I believe the issue may be that [“With opustags yes, MPD needs to start a new Ogg stream after each song change, because only a new stream is allowed to send tags”](https://github.com/MusicPlayerDaemon/MPD/issues/592#issuecomment-506022851).

**Comment by y20k** [comment]
I am not sure, but this problem maybe related to the following issue:

* [Certain OPUS streams do not show "artist - title" and stop playing on song change](https://github.com/y20k/transistor/issues/158)

Just an observation. I am not sure, if I know, how to fix it, though.

**Comment by tastytea** [comment]
I think I've found the cause. I had `tags` and `opustags` both set to "yes" in the MPD config. I guess it sent 2 different kind of tags.

It works if I set `tags` to "yes" and `opustags` to "no" or `opustags` to "yes" and `tags` to "no", both with 3.1.2 and the testing release.
