### ISSUE TITLE
.pls link does not open when paste, but same .pls file opens correctly when opened with Transistor

### ISSUE THREAD

**Issue by Pentaphon** [y20k/transistor#228]
This is Transistor 3.2.1 on an Android 7.1.2 device. 

When pasting the following link: https://streams.infowars.com/listen.pls

I get the following message:
![snap](https://user-images.githubusercontent.com/49374058/62465179-256b6d80-b743-11e9-9f58-e118d8f622e6.jpg)

However, when I download the listen.pls to my phone and open the listen.pls with a file manager, using Transistor as the app to "open with", the stream opens successfully. 

It's great that opening the file from a file manager works well, but if Transistor can't open that .pls file from a pasted link, as directed by Transistor, then it's probably very confusing to users. Please find out why the pasted link doesn't work while the raw listen.pls file works fine. Thanks.

**Comment by y20k** [comment]
There seems to be something wrong with the ssl cert of that server. I get the following error message on the console: `javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

Transistor could ignore those kinds of security errors, but I think that would be bad practice.

Adding http://streams.infowars.com/listen.pls works, btw.

**Comment by Pentaphon** [comment]
Fair enough. Thanks for looking into it.
