### ISSUE TITLE
Translation Updates

### ISSUE THREAD

**Issue by y20k** [y20k/transistor#23]
This is an internal thread where I would like to announce changes and additions to the text strings used in transistor: [strings.xml](https://github.com/y20k/transistor/blob/master/app/src/main/res/values/strings.xml)

Translators can subscribe to this issue to stay up-to-date.

**Comment by y20k** [comment]
Hi Translators.

Today I added a few new strings to [strings.xml](https://github.com/y20k/transistor/blob/master/app/src/main/res/values/strings.xml).

You can see the changes in this [commit](https://github.com/y20k/transistor/commit/23f44ba40e4e78a6ef777c7e0a7c85bdeaea63c1). 

I plan to release a new APK on Monday, so any changes in the translations up to Monday will make it into v1.1.6. But please do not feel pressured. There will be definitely a v1.1.7.

Best wishes

PS. This is issue #23, nice! Coincidence?

**Comment by y20k** [comment]
Hi Team,

the next release is planned for Wednesday. Very minor changes: Long press now can start/stop playback. There are two new strings to translate:

- toastmessage_long_press_playback_stopped
- toastmessage_long_press_playback_started

Again: Please do not feel pressured. The next release (probably bug fixes) will come soon ^o^. Translations can be updated later, too.

Best wishes & Thanks for the great work so far!

**Comment by y20k** [comment]
... I added another short string to explain, why Transistor needs the permission VIBRATE. 
- html_about

**Comment by pejakm** [comment]
May I suggest free and open source [Weblate](https://hosted.weblate.org/) translation platform?

**Comment by y20k** [comment]
Yeah, why not. I do not know this service, but it sounds nice. What do the other translators say? 

**Let's vote on this: Should we use [Weblate](https://hosted.weblate.org/)?**

What do you think M2ck, Boris and burunduk?

**Comment by btimofeev** [comment]
I agree.

**Comment by burunduk** [comment]
Yes! It is good.

**Comment by y20k** [comment]
Okay. Let's try Weblate. I asked them if they want to host Transistor. I will post a notice here, as soon as you can start using it.

**Comment by y20k** [comment]
Oh. I totally forgot. @M2ck suggested a while ago using https://crowdin.com/ - this might be an alternative

**Comment by M2ck** [comment]
Both are very good :)

**Comment by y20k** [comment]
Hi Tranlators (@btimofeev @M2ck @burunduk @pejakm),

Transistor is now hosted on Weblate and the whole thing is configured to be in sync. Changes on GitHub will be pushed to Weblate and changes on Weblate will be automatically brought back in here - at least in theory ;-)

Happy translating
https://hosted.weblate.org/projects/transistor/

**Comment by y20k** [comment]
Hi Translators,

Weblate seems to alter the structure of the HTML-strings within strings.xml. I corrected that for the last release in one of the recent [commits](https://github.com/y20k/transistor/commit/5573a7ea7226573ffc6827a42fb57f4b779abfd0). 

Is there anything I can do to prevent that? Or is this a problem at all, since the project built just fine even with the strangely formatted strings?

**Comment by y20k** [comment]
Since we moved the translation over to Weblate I am thinking of closing this issue. Or maybe I will reuse it, since it is number 23 ;)
