### ISSUE TITLE
tracks history list (recently played tracks)

### ISSUE THREAD

**Issue by moskytos** [y20k/transistor#231]
Hi,

It would be great if the app could automatically generate recently played tracks/songs history list and possibly if user can then mark some of tracks as favorite. 

Please consider this and thanks a lot for this great app.

**Comment by y20k** [comment]
Hi there. Thanks for the feature suggestion. I too found myself wanting to know which song it was, that was playing before the one currently playing. Problem is that I am a bit short on time right now. I will flag this issue as `help wanted`.

**Comment by y20k** [comment]
The upcoming release (Transistor v4) has a metadata history feature.

<a href="https://raw.githubusercontent.com/y20k/transistor/v4.0.0/metadata/en-US/phoneScreenshots/03-player-sheet-oneplus5.png"><img src="https://raw.githubusercontent.com/y20k/transistor/v4.0.0/metadata/en-US/phoneScreenshots/03-player-sheet-oneplus5.png" width="360" /></a>
