### ISSUE TITLE
rename a station failed when cancel a deletion

### ISSUE THREAD

**Issue by tingsu** [y20k/transistor#234]
Thanks for developing this awesome app! I have found an issue and list the details as follows.

- I have searched the history issue list, and have not found similar issues. 

- The issue was found in the latest release version 3.2.2 from Google Play (this version is also the latest code commit), and were reproduciable on both a Google Plxel 3 and an Android emulator 6.0 device.

- Reproduction steps:  

1. Start an station, e.g., ``4540-hi-mp3`` in my case

2. Rename the station name, e.g., from ``4540-hi-mp3`` to ``4540-h`` (the result is correct)

3. Select the delete option but cancel it.  Now the station's name return back to ``4540-hi-mp3`` (this is incorrect).

I feel it seems a view refresh issue?

- Reproducing Video

![20191020_230059](https://user-images.githubusercontent.com/3156978/67166408-5432d080-f38f-11e9-9111-dadef3efdef9.gif)

**Comment by tingsu** [comment]
I noted this issue #164 (i.e., ``SCENARIO 3``), which may be related to the issue I reported here. 

But I followed a different usage scenario (try to delete the station but cancale it). I found the station's name will be the changed back if I close and restart the app. Is this issue caused by view refresh issue?

**Comment by y20k** [comment]
Hi. Thanks for this bug report. I will look into it.

**Comment by tingsu** [comment]
Thanks @y20k ! I observe this issue affects several functionalities around it. It is more serious than the other ones I reported. If you need more info, just let me know. Thanks for coming up this nice app! Hope it will get better.

**Comment by tingsu** [comment]
Any plan to fix this issue :) ? Really hope to see this functioality can be corrected.

**Comment by y20k** [comment]
Sure this needs to be fixed. You need to  be aware that Transistor is a hobby project that I am working on in my free time, which is rare at the moment. Additionally the bug seems also be a result of the architectural problems the apps has (mentioned in another recent issue). So.. I plan to fix the problem. But probably not as soon as you probably would like :grin:

**Comment by tingsu** [comment]
Thanks, totally understand what you said :)

**Comment by tingsu** [comment]
This issue was already fixed by the latest master, but the latest Google Play version (v3.2.4) still has this bug (the apk will be updated later).
