### ISSUE TITLE
duplicate playback indicator appears on two stations

### ISSUE THREAD

**Issue by tingsu** [y20k/transistor#236]
- I have searched the history issue list, and have not found similar issues. 

- The issue was found in the latest release version 3.2.2 from Google Play (this version is also the latest code commit), and were reproduciable on both a Google Plxel 3 and an Android emulator 6.0 device.

- Issue description

1. import two stations (e.g., ``A`` and ``B``), 

2. long press the station ``A`` to start the playing and rename it.

3. long press the station ``A`` to stop it

4. long press the other station ``B`` to start it. Now we can see both stations both ``A`` and ``B`` are annotated with playback indicators.

- Reproducing video (with two different usage scenarios)

![20191021_114049](https://user-images.githubusercontent.com/3156978/67195004-77de3100-f3f8-11e9-8e0c-72cd3bc19249.gif)

![20191021_113053](https://user-images.githubusercontent.com/3156978/67195058-8f1d1e80-f3f8-11e9-916c-c1c366417bac.gif)

**Comment by y20k** [comment]
Hi there. Thank you for the bug report. That is ugly. I will look into this.

**Comment by tingsu** [comment]
Thanks @y20k ! Let me know if you need more info from my end.

**Comment by y20k** [comment]
You bug report is excellent. No need for further assistance for now. THX.

**Comment by tingsu** [comment]
This issue was already fixed by the latest master, but the latest Google Play version (v3.2.4) still has this bug (the apk will be updated later).
