### ISSUE TITLE
App crashes when stopped from Android Auto

### ISSUE THREAD

**Issue by y20k** [y20k/transistor#237]
This one came in via email -> App crashes when stopped from Android Auto

Steps to reproduce:

1. make sure Transistor is closed (swipe it off in the app switcher)
2. open Android Auto
3. start playback for a station
4. leave and quit Android Auto while playing
5. Transistor crashes

Expected behavior: The Transistor should continue to playback the stream.

**Comment by y20k** [comment]
If anyone wants to test the fix for this. Here is a signed APK;

* [transistor-app-testing-3.2.3-001.apk](https://drive.google.com/file/d/1gzGt82xY8V8QOq0mQIXaF6kVdyWg-nAv/view?usp=sharing)

**Comment by Bolsderac** [comment]
Hi, more generally, transistor application crashes as soon as another application tries to start or automatically (via bluetooth connection)

**Comment by y20k** [comment]
Hi @Bolsderac Have you tried the testing APK above? I have not published the v3.2.3. Maybe I should. It has been a while :-)

**Comment by Bolsderac** [comment]
Hi, yes, this the version i installed since you publish it on github. Arnaud

**Comment by y20k** [comment]
And the app **still** crashes, when following the steps I listed above? Or is there now a new set of steps I need to take to re-create the crash?

**Comment by Bolsderac** [comment]
I test again and come back to you

**Comment by Bolsderac** [comment]
Hi, it's not really a crash. Transistor app is stopped by Android auto user closing. Other music app continue playing.

**Comment by y20k** [comment]
Current version of Transistor does not crash anymore and it continues playing when Android Auto is exited.
