### ISSUE TITLE
cannot delete a radio program

### ISSUE THREAD

**Issue by tingsu** [y20k/transistor#239]
- I have searched the history issue list, and have not found similar issues. 

- The issue was found in the latest version 3.2.2 in the master (also exists in the latest released version on Google Play). The issue were reproduciable on both a Google Plxel 3 and an Android emulator 6.0 device.

- Reproduction steps:  

1. Start a radio program, e.g., ``212-hi-mp3`` in my case

2. Rename the program, e.g., from ``212-hi-mp3`` to ``212-h`` 

3. pause the program

3. try to delete this radio program, but cannot be deleted.

But, without Step 3, the radio program can be successfully deleted. In other words, **Step 3** is the critical step to manifest this issue.

- Reproducing Video

![20191113_124151](https://user-images.githubusercontent.com/3156978/68761205-de2f2b80-0613-11ea-8fb4-45fffb2f4147.gif)

**Comment by tingsu** [comment]
Hi @y20k , can I know whether this is an issue?

**Comment by y20k** [comment]
This is another one of those issues related to the way Transistor handles stations internally. You found a bunch of those. All of them are not trivial to fix. I am in the process or rewriting one of my other apps (Trackbook) from scratch right now. This is quite time consuming. I will do that eventually with Transistor, too. I do not intent to fix this issue right now. Without a rewrite this would end in a bunch of nasty hacks. The only bugs I am fixing right now are those that relate to the core functionality of the app. Playback. Sorry. No good I have no satisfying answer for you right now.

**Comment by tingsu** [comment]
Thanks for your reply. I understand. That's fine. Trackbook looks a nice app. I also note you are developing Escapepod. You are really productive to lead these projects at the same time :)  I may look into these two new apps, and see whether I can contribute something.

**Comment by tingsu** [comment]
This issue was already fixed by the latest master, but the latest Google Play version (v3.2.4) still has this bug (the apk will be updated later).
