### ISSUE TITLE
Allow streams with .m3u8 extension

### ISSUE THREAD

**Issue by e-lime** [y20k/transistor#240]
Steams ending with the .m3u8 extension cannot be added because the extension is unknown by Transistor. See for example https://d34pj260kw1xmk.cloudfront.net/live/l1/radio/index.m3u8 which is a playable stream with mimetype application/x-mpegurl.

**Comment by y20k** [comment]
Hi @e-lime 

Thank you for reporting this issue. Transistor performs a mime-type check before it proceeds to add a station from the internet. The stream you were trying to add is a HLS stream (`application/vnd.apple.mpegurl`). It wrongly advertises itself though as `application/x-mpegurl`. Both mime-types are generally supported, although there have been some instances of HLS streams that refusd to work.

Anyway. Transistor cannot handle streams that advertise themselves with an incorrect mime-type. 

There are two solutions.

1. Not a joke :-) -> You could drop the publishers of the stream a note that the stream is not configured correctly.

2. Circumvent the mime-type check and add the stream manually. You will need to create an m3u file (`Test.m3u`) and drop it manually in the folder `/Android/data/org.y20k.transistor/files/Collection`. The content of this file would be:
```
#EXTM3U

#EXTINF:-1,Test
https://d34pj260kw1xmk.cloudfront.net/live/l1/radio/index.m3u8
```
If you would like to test this right now, you could download a copy of such a file [here](https://drive.google.com/open?id=13wulqeqnssVlH1O6lyaZ7P_EjM9_abPY).

**Comment by e-lime** [comment]
Thanks for yout response! I am trying both solutions. Number 2 already works good :)
