### ISSUE TITLE
Support HTML-encoded unicode characters in metadata

### ISSUE THREAD

**Issue by xeals** [y20k/transistor#242]
Thank you for your work on transistor! It's fantastic having an open-source radio aggregator.

I've added a Japanese pop station ([LISTEN.moe](https://listen.moe)) and am having some issues with fetching metadata.

The docs for the stream claim the Vorbis stream ([link](https://listen.moe/stream)) sends metadata but if it is, transistor isn't picking it up. That aside, the fallback MP3 stream ([link](https://listen.moe/fallback)) does send metadata that is read, but non-Latin characters are HTML-encoded.

![Screenshot for reference](https://user-images.githubusercontent.com/21125058/71702119-c01ac600-2e21-11ea-8ab4-aed24da799e7.jpg)

Is it possible to support decoding of the HTML to proper unicode characters?

**Comment by y20k** [comment]
Hi @xeals,

thanks for the bug report! Transistor currently does not support Ogg metadata (see #222). But there maybe a simple fix for the HTML formatted metadata in the fallback stream you mentioned - see [commit](https://github.com/y20k/transistor/commit/58fd483fbf32fc57c623709f0eb3c0bb90310f83). 

If you are interested to test this, here is a signed APK:
- [transistor-app-testing-3.2.3-002.apk](https://drive.google.com/open?id=1vKOIZ5NLM4X_MYm8zlkA8h8CwmSt5LEV)

The fix will be part of the next release - probably in late January.

**Comment by y20k** [comment]
The mentioned commit is part of the latest release
