### ISSUE TITLE
HTTP redirects in stream URLs don't work

### ISSUE THREAD

**Issue by Martinique** [y20k/transistor#247]
When radio stations change their streaming services, they often use HTTP redirects to automatically send clients to new playlist addresses. Unfortunately Transistor doesn't seem to understand them and says "Unable to connect. Device does not have an internet connection or stream may be outdated." This also prevents using URL shorteners.

It's not a showstopper issue, because one can always see the redirects with `curl -vL`, for example, and enter the new URL, but this shouldn't be hard to fix either. I spotted some redirect handling code in Station.java, so I wonder why it's not working.

Here's an example for testing (redirects twice, first to switch to HTTPS, and then to a M3U8): http\://tiny.cc/s581jz

**Comment by y20k** [comment]
Thanks!!! You are right the current solution only follows one redirects. I have adapted the connection code to follow up to five redirects.

**Comment by Martinique** [comment]
That's great!

Another issue with redirects is the automatic icon finding, because the correct one may be in any of the hosts that the redirects go through, most likely the first or the last. Personally I don't care about icons, though.

**Comment by y20k** [comment]
Playback does not work for me at the moment for the example station. The DataSource needs to to support redirects, too. I will have a look into this. https://stackoverflow.com/questions/41517440/exoplayer2-how-can-i-make-a-http-301-redirect-work

**Comment by y20k** [comment]
The new version of Transistor plays back http://tiny.cc/s581jz (the old one probably did too after the fix from Feb 21 :smile: ).
