### ISSUE TITLE
Kotlin-Rewrite

### ISSUE THREAD

**Issue by y20k** [y20k/transistor#251]
Back in 2015 Transistor was the first Android app, I have ever developed. Looking at the "architecture" and code this shows: Some bugs are hard to fix without resorting to hacks or without rewriting whole parts of the app. 

That is why I decided to rewrite the whole app from scratch. I just recently rewrote one of my other apps ([Trackbook](https://github.com/y20k/trackbook/issues/66)) in Kotlin, which turned out nicely.

So that is the plan: I will re-implement the app in Kotlin. In the process minSdkVersion will be bumped to 25 (Android 7.1) to make further development easier. Depending on the user demand, I might keep a fork of the old Transistor around, since it supports older devices (Android 4.4 and newer).

I will make screenshots and beta versions available here, when there is anything to show. Do not expect too much from it. Basically I want to get Transistor to a point, where it is easier to support it and to fix bugs.

PS. The new Transistor will feature a simple search, that uses [api.radio-browser.info](https://api.radio-browser.info/) (#94)

**Comment by tingsu** [comment]
Are there any new update on this Kotlin rewrite? Hoping to see the new app :)

**Comment by y20k** [comment]
As of today some new and working code is here on GitHub. See: [commit](https://github.com/y20k/transistor/commit/198ef828f9ae9e5b51a70ed4ab5ca03b21daeba5)

**Comment by y20k** [comment]
As of today some new and working code is here on GitHub. See: [commit](https://github.com/y20k/transistor/commit/198ef828f9ae9e5b51a70ed4ab5ca03b21daeba5)

**Comment by tiborroald** [comment]
Can  you share the build environment? I cannot get to the point to build it in an usable form. I have a device with Android 6.0 (API 23).
To have it successfully build I had to disable lint.
 ./gradlew --stacktrace build

But it fail during APK install. Yeah, is generic ("APK not installed")

**Comment by urayoanm** [comment]
Hello. I think your problem is the minSdk in the build grade config. The new version requires API 25

**Comment by tiborroald** [comment]
I hacked the app/build.gradle to have it compiled and also an installable APK on Android 6.0

    defaultConfig {
        applicationId 'org.y20k.transistor'
        minSdkVersion 23
        targetSdkVersion 23
        versionCode 72
        versionName '4.0.0'
        resConfigs "en"
    }

**Comment by y20k** [comment]
:+1: It is maybe better to just change `minSdkVersion` if you are experimenting with older Android versions.

**Comment by y20k** [comment]
If anyone is interested: Here is an early test built of the upcoming Transistor version. Remember not all features of the previous versions are implemented yet. The app is stable for me. I am already running it as my main radio app on my phone.

**Please note:** Before you install the test APK, please make a copy of your radio station collection. Backup the contents of this folder:
`/Android/data/org.y20k.transistor/files/Collection`

**Test APK**
... based on code up to and including the commit [9a0bafe8c3](https://github.com/y20k/transistor/tree/9a0bafe8c3d9f859ecefd56996b142a40c88827b)
- [transistor-app-testing-4.0.0-001.apk](https://drive.google.com/open?id=1ITm8QLq9NDUtrUfTInW3YkOIRrjxUy5T)

**Comment by tingsu** [comment]
Thanks @y20k ! The new version looks good! It seems everything works perfect. I checked one previous issue #249, which was reported byme. That issue still exist...  waiting to be fixed :)

**Comment by tiborroald** [comment]
pkg: /data/local/tmp/transistor-app-testing-4.0.0-001.apk
Failure [INSTALL_FAILED_OLDER_SDK]

Do you plan to have a release  for Android 6.0? 
The 3.2.4 release still works on my old tablet.

**Comment by tingsu** [comment]
I checked with the new apk, which works on Android 25 above. Yes, it would be good if it can still work on Android 6.0. Maybe @y20k has some consideration here. Not sure ...

**Comment by y20k** [comment]
I currently do not plan to support Android versions older than 7.1. I had this discussion a couple of times in other circumstances before - [here](https://github.com/y20k/transistor/issues/38) and [here](https://github.com/y20k/escapepod/issues/2) for example.

There are always older devices out there. My reasoning basically is: 
- I am a hobby developer with very few time to spare
- I am maintaining three [apps](https://github.com/y20k)

==> Therefore I need a clean and easy to handle code base. (That was the rationale behind the whole rewrite - the old code was too hard to maintain.) Supporting older OS versions is a time sink. And even the app in its current state would compile under SDK 23, sticking to and supporting Android 6 will most definitely will cause problems in the future. My other apps all have minSdkVersion 25, which makes it easy to share code between them.

Depending on the demand, I am considering to maintain a fork of the old Transistor called [Transistor One](https://github.com/y20k/transistorone). Transistor One will only get "security" updates. For example it could get updated when new versions of libraries that Transistor One uses (like Exoplayer). Not sure though if that is worth the effort.

**Comment by y20k** [comment]
**New APK**
... based on code up to and including the commit [3729728](https://github.com/y20k/transistor/tree/37297280e0a0b42fcb8f08a1518e70dcb10a583a)

- [transistor-app-testing-4.0.0-002.apk](https://drive.google.com/open?id=1TOK8vieXv8XArrKxI7CXVHdCh1qbmY_9)

**Comment by tingsu** [comment]
Can you also fix the issue #249 in the next version ? It was still there in this new version.

**Comment by y20k** [comment]
The app is still full of papercut bugs like #249. 249 will definitely be fixed before the official release of the app. Cannot give any promises beyond that :smiley:

**Comment by y20k** [comment]
:facepalm: I just found out that the APKs, I had published earlier, had a bug: Station search was broken (it worked in debug builds). So here is another APK. Since I am not planning to work on Transistor in the next couple of days, I hope its the last one for I while. (I am actually on vacation.)

**New APK**
... based on code up to and including the commit [5856f98](https://github.com/y20k/transistor/tree/5856f98cb384e22a520cfab124dd30ea7a30ce42)

- [transistor-app-testing-4.0.0-003.apk](https://drive.google.com/open?id=1um-NxG4szEYcpvbRrsJEYdiYWumLU_pW)

**Please note:** Backup your old collection `/Android/data/org.y20k.transistor/files/Collection`. This is a test build anything can happen.

**Comment by y20k** [comment]
**New APK**
... based on code up to and including the commit [5de608c](https://github.com/y20k/transistor/tree/5de608c1517b95c4013d0ca187a91e38a1f0c2d1)

- [transistor-app-testing-4.0.0-004.apk](https://drive.google.com/open?id=1hJ19tY4iwrWxytdvrZ-VTncQdHk_xe6L)

**Please note:** Backup your old collection `/Android/data/org.y20k.transistor/files/Collection`. This is a test build anything can happen.

**Comment by ralxxx** [comment]
Hi, can I install the testing version just next to an existing 3x version?

**Comment by y20k** [comment]
> install the testing version just next to an existing 3x

This is not possible. Both are versions of the same app. You will have to switch between both versions. 

If you really want to use both versions side by side, you could consider installing [Transistor One](https://github.com/y20k/transistorone/releases), which is a fork of Transistor v3.2.x.

In any case be careful and backup your old collection `/Android/data/org.y20k.transistor/files/Collection`.

**Comment by y20k** [comment]
**New APK**
... based on code up to and including the commit [c425ca2](https://github.com/y20k/transistor/tree/c425ca20d9d668173afdd445df96c0517ebe4a5a)

- [transistor-app-testing-4.0.0-005.apk](https://drive.google.com/file/d/1kQ6fMGN6bYoRmyLoxCkqPJcMz8YMtIpn/view?usp=sharing)

**Please note:** Backup your old collection `/Android/data/org.y20k.transistor/files/Collection`. This is a test build. Anything can happen.

**Comment by jpds** [comment]
I installed the `-005` APK above and found that I could not add the MP3 streams found here: https://www.koelncampus.com/sender/livestream/ - the OGG stream works fine but no error is shown for the MP3 ones.

I think it would be good to display the version number of the app in the settings area too.

**Comment by y20k** [comment]
Hi @jpds 

Transistor uses the official Android [DownloadManager](https://developer.android.com/reference/kotlin/android/app/DownloadManager) to fetch M3U station files. 

A quick look into the logs reveals, that DownloadManager fails with ERROR_CANNOT_RESUME (1008). I am not sure what the problem is, since Chrome and wget download the file without any problems.

If it helps. The built in search finds a stream if you type in **KölnCampus**.

**Comment by y20k** [comment]
Hi @jpds 

I am totally out of my depth here, since I am not web developer. 

But here is what I think might be the issue. `DownloadManager` might need `Content-Length` information in the response header from the server to work properly. If `Content-Length` is not available `Cache-Control` information might do the trick, too

I puzzled my speculation together by scanning stackoverflow posts and by comparing the response header of successful downloads with the unsuccessful one from [Kölncampus](http://koelncampus.uni-koeln.de/hq.m3u), which only provides minimal information:

```
HTTP/1.0 200 OK
Content-Type: audio/x-mpegurl
```

Just for comparison http://www.byte.fm/stream/bytefm.m3u works with DownloadManager/Transistor and returns
```
HTTP/1.1 200 OK
Date: Tue, 16 Jun 2020 15:20:23 GMT
Content-Type: audio/x-mpegurl
Content-Length: 106
Connection: keep-alive
Server: Apache/2.4.29 (Ubuntu)
Last-Modified: Tue, 13 Aug 2019 07:52:42 GMT
X-Frame-Options: SAMEORIGIN
```

In any case since Transistor uses the Android DownloadManager. I cannot change anything here. Maybe, if you happen to know the Kölncampus administrator, you could consider dropping him/her a note.

**Comment by jpds** [comment]
So, I'm a new user to Transistor as of a week ago - was excited to see the rewrite in process and hence jumped in here.

> If it helps. The built in search finds a stream if you type in KölnCampus.

I had no idea that there was a built-in search. It seems that it's only triggered after adding a space - perhaps it should start after the user starts typing instead for discoverability?

> if you happen to know the Kölncampus administrator, you could consider dropping him/her a note.

I don't actually know them, but I think the UX issue here is that there's no error feedback from Transistor - it just silently ignores the request.

**Comment by y20k** [comment]
> built-in search. It seems that it's only triggered after adding a space

Currently it is triggered after 4 characters - to prevent unnecessary network request. I should probably lower the number to ~ two

> no error feedback from Transistor 

I implemented a simple feedback if a download error occurs. [[1]](https://github.com/y20k/transistor/commit/2a664f23cdb62d2b93a153dc108de140867a4749#diff-5503086e6902ff8c6ba0bf8e19606325R98) [[2]](https://github.com/y20k/transistor/commit/f20fedad18ca19d24dbf4810049c785fc99c2ce7#diff-5503086e6902ff8c6ba0bf8e19606325R110)

**Comment by y20k** [comment]
**New APK**
... based on code up to and including the commit [76a4c68](https://github.com/y20k/transistor/tree/76a4c68b06be35fde35a5d87b71834869408777c)

- [transistor-app-testing-4.0.0-006.apk](https://drive.google.com/file/d/1KVPDFm3H59tanwqdNTzUgvR9_17978TG/view?usp=sharing)

**Please note:** Backup your old collection `/Android/data/org.y20k.transistor/files/Collection`. This is a test build. Anything can happen.

**Comment by y20k** [comment]
Transistor v4 is finally ready to be published. It took a while, but: This has been a re-write from scratch and Transistor is only a one-person hobby project. Anyway. I submitted the [update](https://github.com/y20k/transistor/releases/tag/v4.0.0) to PlayStore and F-Droid today. Time to close this issue. Bugs/issues should be filed as new issues in the issue tracker - not here anymore. **Thank you everyone for participating!!**

**Comment by yateendra** [comment]
In the latest version there is no option to delete a channel.

**Comment by y20k** [comment]
You should be able to swipe a station, like in an email app.
