### ISSUE TITLE
storage permition request not shown?

### ISSUE THREAD

**Issue by voipworld** [y20k/transistor#252]
hey developers,
 i downloaded transistor from playstore, then built it using android studio also, getting source from github.
i listened to my prefaired stations, working perfectly and smoothly
but, it didnt save it, till i go to settings & apps & permitions and enable all perms for transistor.
why the transistor app dont ask for the permition up on adding a channel?

**Comment by y20k** [comment]
Transistor does not need this Storage permission to save stations. Stations are stored in the app's own directory (`/Android/data/org.y20k.transistor/files/Collection`). Hope that answers your question.

Storage permission is only required, if you want to change the image of a station, or if you want to open an m3u station file that sits - for example - in the Downloads folder.
