### ISSUE TITLE
[Feature] Remote Playlists

### ISSUE THREAD

**Issue by SebiderSushi** [y20k/transistor#253]
As it seems, Transistor is downloading/extracting the playlist if given an .m3u8 file URL.

As the purpose of these playlists is to provide a stable link to a resource while its content might change at any time, the desired behavior here could be to just save the playlist link instead of fetching its content at just one point in time.

**Comment by y20k** [comment]
The upcoming version has also a new data structure that allows updating a station. Basically the app remembers the m3u/pls url (or the radio-browser.info uuid), that was used to add it to Transistor.

The new datastructure can be found here: [Station.kt](https://github.com/y20k/transistor/blob/198ef828f9ae9e5b51a70ed4ab5ca03b21daeba5/app/src/main/java/org/y20k/transistor/core/Station.kt)

It may take a while until the new version is finished, though.

**Comment by y20k** [comment]
Transistor v4 has an update feature that uses the playlist file url to fetch the most current version of the stream. The update need to be triggered manually though
