### ISSUE TITLE
A Display Bug

### ISSUE THREAD

**Issue by franklinbill** [y20k/transistor#254]
Dear developer
In the process of using, I found a bug in layout / display. As shown in the figure, the bottom part of the text "on a velvet afternoon" at the bottom of the home page is blocked, which may be an adaptation problem.
App version is 3.2.4, my mobile phone is Google nexus 6, screen resolution setting is 1440 * 2560, font size is the largest, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
![image](https://user-images.githubusercontent.com/18572115/79258943-80528880-7ebe-11ea-9d6b-bc64d78dcad8.png)

**Comment by y20k** [comment]
Hi @franklinbill Thanks for reporting this bug. I am trying to reproduce the problem. Do you have somehow changed the font size settings?

**Comment by y20k** [comment]
found the bug ==> see [commit](https://github.com/y20k/transistor/commit/301fc54c1065f468eb5699b20de7a1c313bd850d#diff-6caa92f7635a2d7325dc3de65a3b26bc)
