### ISSUE TITLE
Bug: Add http:// station stream - mission impossible

### ISSUE THREAD

**Issue by tiborroald** [y20k/transistor#258]
On the add station dialog when you enter http, then imediatelly the keyboard close.
Add ":", again close. Add "//" and then the dialog close alltogether.

Probably because it combine a search dialog with add stream entry line.

**Comment by y20k** [comment]
Hi @tiborroald,
Thanks for pointing out that bug. I originally added the hide keyboard feature assuming the user would use copy&paste to add whole stream URLs. But given your description I think it is necessary to disable the feature.

**Comment by y20k** [comment]
bug should be fixed

**Comment by y20k** [comment]
I am not sure on how to handle bugs in the unreleased version 4 of Transistor. The current codebase app is probably full of papercuts like this.
