### ISSUE TITLE
Bug: lost collection after app remove

### ISSUE THREAD

**Issue by tiborroald** [y20k/transistor#259]
When you remove the app, the collection is also
lost.   So if you by mistake install app, then you need
to redo all your configuration work.

**Comment by tiborroald** [comment]
Probably because of my custom build?

**Comment by y20k** [comment]
Transistor stores its stations in an app specific directory (/Android/data/org.y20k.transistor/) that gets removed when the app gets uninstalled. This is actually pretty common - maybe not for traditional music players, though. Anyway. To be able to survive an un/re-install Transistor would need to ask for Storage permissions and store stations in a system-wide readable folder. I do not want to do this. So I think I will not change the app's behavior here.
