### ISSUE TITLE
Bug: STREAM_URI - Player not started if already in front

### ISSUE THREAD

**Issue by tiborroald** [y20k/transistor#261]
Starting 

adb shell am start -n "org.y20k.transistor/org.y20k.transistor.MainActivity" -a "org.y20k.transistor.action.START_PLAYER_SERVICE" --es "STREAM_URI" "https://myhost.mydomain:8000/stream64"

If Transistor is already in front, then running intent will not start the player.

If Transistor app is stopped, then it will work.

**Comment by y20k** [comment]
for me it seems to work. not sure if the added intent-filter (see #256) helped.

**Comment by y20k** [comment]
I am closing this issue since we are discussing it in #256
