### ISSUE TITLE
Bug: not fatal, but logic flaw

### ISSUE THREAD

**Issue by tiborroald** [y20k/transistor#262]
Related to my effort to start Transistor play from Takser I think you have a logic error.
If you don't want to take the effort, please close it...

The tip is that:
05-14 18:45:31.350  6316  6316 D transistor_PlayerFragment: THIS_IS_MY_MARKER: Intent action =
05-14 18:45:31.350  6316  6316 D transistor_PlayerFragment: THIS_IS_MY_MARKER: Number of intent extras Bundle[{STREAM_URI=https://myhost.mydomain:8000/stream64}]

You handle start intent from "observeCollectionViewModel". Triggered from onConnected.

At application startup you have first handleStartPlayer EXTRA_STREAM_URI for
Intent action = org.y20k.transistor.action.START_PLAYER_SERVICE
Then a spurious run of handleStartIntent after "Reading collection...".
Intent is empty string, but EXTRA remain unchanged and correct.

On "transistor_PlayerService: Stopping Playback" as above.

And, on valid org.y20k.transistor.action.START_PLAYER_SERVICE intent receiving (from Tasker), the code path is going on onConnected(), observeCollectionViewModel() and
finally on handleStartPlayer(). But with empty intent and correct EXTRA fields.

**Comment by y20k** [comment]
I cannot pursue this issue. Sorry. The related issue #256 already did cost me too much time. 

Short note, if you want to pursue this issue by yourself. 

`handleStartIntent()` needs to wait at least for an stablished connection to PlayerService, which is in `onConnected()` the case. I placed it in `observeCollectionViewModel()`, to make that the all the stations have been loaded. Calling `handleStartIntent()` earlier - for example in `onResume()` - may cause crashes. At least I think so.

And with that: I am out :vulcan_salute:
