### ISSUE TITLE
v4 station icon bug

### ISSUE THREAD

**Issue by JonnyTech** [y20k/transistor#263]
I have about 20 stations all with different icons in v4 beta. If I change an icon for one then they all change. All image files in all folders are replaced. Luckily I have backups. Can you replicate the bug?

**Comment by y20k** [comment]
Yes. There is at least one bug in the replace image feature, I know of. Maybe/hopefully it is related to this one. I will investigate and see to get this issue fixed before release. Thank you for reporting.
