### ISSUE TITLE
Rounded Corners

### ISSUE THREAD

**Issue by jamal2362** [y20k/transistor#264]
Hello,
I once compiled the app and I noticed that the round corners are gone.
Would it be possible to insert this again, like in this picture?
![Screenshot_20200620-153148](https://user-images.githubusercontent.com/15986930/85203050-309f9b80-b30b-11ea-81a2-dc7df39f46dc.jpg)

**Comment by y20k** [comment]
Actually I changed the rounded corners to straight corners intentionally. :smiley: 

The new Transistor station list uses "cards" to present the stations. Cards have rounded corners themselves. The player at the bottom has rounded corner. I felt having station icons rounded too would be a bit too much. I guess this is a question of personal preference. I understand that you like it better the way your screenshot shows.

**Comment by jamal2362** [comment]
All right :)
I like it better rounded.
I am so used to it from the old app :D
