### ISSUE TITLE
Wrong height

### ISSUE THREAD

**Issue by jamal2362** [y20k/transistor#265]
If you use the app with the navigation bar you will see a wrong height.
![Screenshot_20200620-152755__01](https://user-images.githubusercontent.com/15986930/85202978-b7a04400-b30a-11ea-97c2-bd4d1c7740d6.jpg)

In landscape everything looks good
![Screenshot_20200620-152914](https://user-images.githubusercontent.com/15986930/85203009-f209e100-b30a-11ea-8743-6e1647cc2ec3.jpg)

**Comment by y20k** [comment]
Oh. This is an interesting bug. Thanks for reporting this. 

I cannot reproduce the problem on my two test devices. Any idea what I can do? Were you able to produce the bug in the emulator? If so which system image did you use.

**Comment by jamal2362** [comment]
I can't test it on Android Emulator because no internet connection.

I use the OnePlus 8 Pro with Android 10.
When I turn off the navigation bar everything looks fine.
![Screenshot_20200620-160635](https://user-images.githubusercontent.com/15986930/85203747-0c928900-b310-11ea-8123-ed8e3581d84a.jpg)

When I turn the navigation bar back on the height is wrong again.

![Screenshot_20200620-152755__01](https://user-images.githubusercontent.com/15986930/85203758-23d17680-b310-11ea-9556-6bca5b87eb84.jpg)

**Comment by y20k** [comment]
and this bug is persistent even if you close and reopen Transistor?

**Comment by jamal2362** [comment]
Yes the bug remains.
Unfortunately restarting the app does not help.

**Comment by y20k** [comment]
and the old transistor behaves differently?

**Comment by jamal2362** [comment]
In the old app the height fits
![Screenshot_20200620-162036](https://user-images.githubusercontent.com/15986930/85204044-13220000-b312-11ea-9818-97a4f2a9a32d.jpg)

**Comment by y20k** [comment]
Okay. Thank you. That is very helpful. I need to check how I implemented the height calculation in the past then :-)

**Comment by jamal2362** [comment]
All right.
Thanks a lot :)

**Comment by jamal2362** [comment]
I found the Bug.
when i change this from

implementation "com.google.android.material:material:1.1.0-beta01"
to
implementation "com.google.android.material:material:1.2.0-beta01"

then comes this mistake.
Any idea how i can fix it when i use the 1.2.0-beta01 ?

**Comment by y20k** [comment]
I was poking around and also found the way to reproduce. A newer version of material components will introduce the bug, as you wrote.

There is a bug report describing the issue and a [suggested solution](https://github.com/material-components/material-components-android/issues/1219#issuecomment-617337002).

You need to add `app:gestureInsetBottomIgnored="true"` in `bottom_sheet` in `bottom_sheet_playback_controls.xml`

Not 100% sure it works. I does seem to work in the emulator.

**Comment by jamal2362** [comment]
Thanks a lot it worked.
I think we can make it here!

app:gestureInsetBottomIgnored="true" in bottom_sheet_playback_controls.xml
has worked perfectly :)

![Screenshot_20200620-232922](https://user-images.githubusercontent.com/15986930/85211925-1935d200-b34e-11ea-9e07-fc3737004f03.jpg)
