### ISSUE TITLE
Snackbar instead Toastmessages

### ISSUE THREAD

**Issue by jamal2362** [y20k/transistor#266]
Is it possible to replace the toast messages with snackbar?
That would fit the new theme.

Here an Example:
![Screenshot_20200624-172804](https://user-images.githubusercontent.com/15986930/85585301-2b5e8b80-b640-11ea-974f-6b9e15164c0e.jpg)

**Comment by y20k** [comment]
I too think that Snackbar messages look more pleasant than Toast messages. As far as I know a Snackbar needs window reference. So Toast messages fired from a Service cannot be replaced easily. 

But for the Toast messages in Fragments it should be possible. 

Do you now how to handle the positioning of Snackbar messages? 

I have impression in the back of my head that Snackbar messages do not play well together with BottomSheets (= the player interface). As far as I remember they overlap each other.

**Comment by jamal2362** [comment]
Unfortunately I haven't been able to do this at URL Radio yet.
I don't know what the reason is.

I have another android app project here at Github which includes the snackbar.
And it works.
See screenshot.

If you want I can invite you to the App and you can see how it is implemented and use it for URL Radio.

**Comment by y20k** [comment]
I will try something like this

```
fun displaySnackbar(contextView: View, anchorView: View, text: Int) {
        Snackbar.make(contextView, text, Snackbar.LENGTH_SHORT)
                .setAnchorView(anchorView)
                .show()
    }
```

**Comment by jamal2362** [comment]
I can try this code out later.

**Comment by y20k** [comment]
For test purposes I added a [Snackbar response](https://github.com/y20k/transistor/commit/b71f51704214c7910ec7896d4ea5d2fc0afbe7e3#diff-8b4ff5fd54e2e9d1dac5b6074f022898R279), if you enter a wrong station URL - like https://www.google.com - in the station search dialog.

Not sure yet, if Snackbar is really better than Toast. I probably need to sleep over this.

In general it is probably wise to come up with rules for when to use Snackbar and when to use Toast. The Snackbar can be made [permanent](https://material.io/develop/android/components/snackbars/) with a dismiss button. Probably interesting for messages that one want the user to acknowledge.

**Comment by jamal2362** [comment]
Wow this looks fresh.
![1](https://user-images.githubusercontent.com/15986930/85609425-581d9d80-b656-11ea-819e-f4c1cb58cb74.PNG)
![2](https://user-images.githubusercontent.com/15986930/85609435-5a7ff780-b656-11ea-94da-a301af2892e4.PNG)

**Comment by jamal2362** [comment]
Unfortunately I was not able to use the snackbar everywhere which was only possible in the PlayerFragment.kt

![Screenshot_20200625-075603](https://user-images.githubusercontent.com/15986930/85663443-6355e500-b6b9-11ea-9340-ed953ddc7a45.jpg)

![Screenshot_20200625-075613](https://user-images.githubusercontent.com/15986930/85663462-681a9900-b6b9-11ea-8939-16fdc95429c5.jpg)

**Comment by y20k** [comment]
I added a [requireConfirmation](https://github.com/y20k/transistor/blob/76a4c68b06be35fde35a5d87b71834869408777c/app/src/main/java/org/y20k/transistor/helpers/UiHelper.kt#L67) parameter. If set to true the Snackbar stays visible until the user taps on OK. This can be used for Snackbars that convey an important message that a user needs to acknowledge. For example for the message `Grant "Read Storage" permission to open this file.`. 

I am still not sure on when to use Snackbars. 

And they behave a little awkward. Try this: Use set the new parameter `requireConfirmation` to true and anchor the Snackbar to the play/stop button. Let the Snackbar display - and then drag up the play sheet. The snackbar does not move with the sheet. It stays at its previously anchored position.

Anyway. There is probably a way to adjust this behavior. 

And the main hurdle for me at the moment is that I cannot decide when/where use them and where not. Still some thinking time needed :-)
