### ISSUE TITLE
v4: feedback link

### ISSUE THREAD

**Issue by JonnyTech** [y20k/transistor#268]
Can you add an option in settings to link to this repo for reporting bugs or to leave feedback? Currently have to remember to search github or fdroid to get here.

**Comment by y20k** [comment]
Good idea.

**Comment by y20k** [comment]
<a href="https://user-images.githubusercontent.com/9103935/86475263-a6acf500-bd44-11ea-910b-f25f0aca8de1.png"><img src="https://user-images.githubusercontent.com/9103935/86475263-a6acf500-bd44-11ea-910b-f25f0aca8de1.png" width=360 /></a>
