### ISSUE TITLE
Stations not sorted?

### ISSUE THREAD

**Issue by Improver2000** [y20k/transistor#269]
The update is nice and the app awesome :-D!!

In the old version,  I sorted the apps by putting '!' in the beginning of the station name. Now the stations are completely mixed and not sorted in any way?! Favourite feature Bruce, but the rest stayed not sorted?

**Comment by Improver2000** [comment]
Oh, adding a new station returns the alphabetical sorting :-D.

**Comment by y20k** [comment]
I will look into this. Thanks for reporting this bug.

**Comment by y20k** [comment]
I published a quick bugfix update - [v4.0.1](https://github.com/y20k/transistor/releases/tag/v4.0.1). It solves the issue and should appear on Google Play and F-Droid soon.
