### ISSUE TITLE
Tags and android auto

### ISSUE THREAD

**Issue by Bolsderac** [y20k/transistor#275]
From v4.0, no more tags on android auto app.
Thanks you.

**Comment by y20k** [comment]
Hi @Bolsderac 

I don't have a car and I am not using Android Auto. I need external input like yours to improve this feature. Could you go a bit more in detail? What kind of tags are you missing?

**Comment by Bolsderac** [comment]
Hi,
I use android auto on smartphone screen, not on car screen.
You can test it with 'android auto' app + 'android auto for mobile' app
shortcut on play store (android 10).
Regards
Arnaud

**Comment by y20k** [comment]
Hi. I am aware of the Android Auto app. What exactly is the problem you have? You mentioned Tags. What do you mean? And what would be the "expected behavior" of Transistor in this case?
Cheers

**Comment by Bolsderac** [comment]
Android app show only the radio name. Not artist and not song name (tags
sent by the radio).

**Comment by Bolsderac** [comment]
Le lun. 6 juil. 2020 à 16:19, Famille Redslob <bolsderac@gmail.com> a
écrit :

> Android app show only the radio name. Not artist and not song name (tags
> sent by the radio).
>

**Comment by Bolsderac** [comment]
With other app

Le lun. 6 juil. 2020 à 16:20, Famille Redslob <bolsderac@gmail.com> a
écrit :

>
> Le lun. 6 juil. 2020 à 16:19, Famille Redslob <bolsderac@gmail.com> a
> écrit :
>
>> Android app show only the radio name. Not artist and not song name (tags
>> sent by the radio).
>>

**Comment by Bolsderac** [comment]
Is it possible to split song name and artist name on two lines?

Le lun. 6 juil. 2020 à 16:21, Famille Redslob <bolsderac@gmail.com> a
écrit :

> With other app
>
> Le lun. 6 juil. 2020 à 16:20, Famille Redslob <bolsderac@gmail.com> a
> écrit :
>
>>
>> Le lun. 6 juil. 2020 à 16:19, Famille Redslob <bolsderac@gmail.com> a
>> écrit :
>>
>>> Android app show only the radio name. Not artist and not song name (tags
>>> sent by the radio).
>>>

**Comment by y20k** [comment]
Okay. Understood the problem. I am looking into it.

**Comment by y20k** [comment]
@Bolsderac  Metadata will return to the Android Auto display with the next update.

<a href="https://user-images.githubusercontent.com/9103935/86742906-c1c77f80-c038-11ea-94f1-a52122927a20.png"><img src="https://user-images.githubusercontent.com/9103935/86742906-c1c77f80-c038-11ea-94f1-a52122927a20.png" width="480" /></a>

<a href ="https://user-images.githubusercontent.com/9103935/86742917-c429d980-c038-11ea-81e4-4a5482f5c371.png"><img src="https://user-images.githubusercontent.com/9103935/86742917-c429d980-c038-11ea-81e4-4a5482f5c371.png" width="480" /></a>

**Comment by Bolsderac** [comment]
Perfect. Thank you!

**Comment by Bolsderac** [comment]
When do you plan to publish the new release on play store ?

**Comment by y20k** [comment]
Probably before the weekend.

**Comment by y20k** [comment]
v4.0.2 fixes the issue. It is now available in the Play Store.

**Comment by Bolsderac** [comment]
Hi,
Just a small remark.
When android auto restart, transistor automatically play first found
station in his list, not the last played.
Arnaud
