### ISSUE TITLE
bookmarks are broken

### ISSUE THREAD

**Issue by 532910** [y20k/transistor#276]
After update to 4.0.1, desktop shortcuts just open Transistor, but it doesn't start play.

**Comment by 532910** [comment]
Newly created shortcuts work fine.

**Comment by JonnyTech** [comment]
Duplicate of #270

**Comment by 532910** [comment]
Indeed, but I don't agree to recreate them.

**Comment by y20k** [comment]
The home screen shortcuts work a bit differently than before. They open the app in background. The problem is: They also are now constructed differently to achieve that behavior. 

To be able to have the old shortcuts working with the new Transistor, I would have to write an Importer or Converter. The problem here: I am not aware of (1) a way to search the home screen for existing shortcuts and (2) a way to delete existing shortcuts.

**Comment by 532910** [comment]
ok, I'll recreate them ):

**Comment by y20k** [comment]
Sorry that there was no better answer :smirk:

**Comment by 532910** [comment]
I've recreated all shortcuts, but they don't work.
I don't know how to reproduce this, but suppose they were created from transistor opened with an old shortcut.

**Comment by y20k** [comment]
Do they still just open the app without starting the stream?

**Comment by 532910** [comment]
Yep, exactly.

**Comment by 532910** [comment]
Looks like the old shortcut must be removed, before creating the new one.

**Comment by y20k** [comment]
A short screencast of how it is supposed to work. (Playback starts in background)

<a href="https://user-images.githubusercontent.com/9103935/86926331-37fbdd00-c132-11ea-97d0-7e50710ec2a9.gif"><img src="https://user-images.githubusercontent.com/9103935/86926879-e738b400-c132-11ea-9207-27540a317a09.gif" /></a>

**Comment by 532910** [comment]
> how it is supposed to work

yep, newly created shortcuts works fine and I love new behavior to start stream in the background

**Comment by 532910** [comment]
I think there should be a note displayed after upgrade, that will explain these changes and how to re-create shortcuts.

**Comment by y20k** [comment]
That or maybe only if a user tries to open an older shortcut. (I should be able to detect that.)
