### ISSUE TITLE
Import Playlist

### ISSUE THREAD

**Issue by jamal2362** [y20k/transistor#281]
It would be really cool if you could select a .zip file which you could then easily import a playlist.

Currently you always have to do this manually:
Copy the two folders "collection" and "images" into the "Internal Storage/Android/data/org.y20k.transistor/files/".

Here is a playlist .zip as an example which I made with over 100 stations
[Transistor_Playlist_v1.0.zip](https://github.com/y20k/transistor/files/4895948/Transistor_Playlist_v1.0.zip)

**Comment by y20k** [comment]
This is probably a duplicate - #126

**Comment by y20k** [comment]
Closing this issue. See #126 for explanation.

In short: Nice feature, I probably will not find the time to implement it.
