### ISSUE TITLE
all stations disappeared

### ISSUE THREAD

**Issue by puzzlled** [y20k/transistor#283]
I spent a fair bit of time compiling a list of stations, complete with images. These were working just a short time ago but when I opened the app recently all stations were gone. Fortunately I had made a backup copy of the directory to make setting it up on other devices a breeze. However, when I repopulate the mysteriously empty directory no stations appear in the app. I had thought perhaps things had been wiped out by an upgrade but now I don't know what's wrong or how to restore my stations. It would be nice if there was an import function so a person could import the m3u and PNG files.
Any suggestions?
Thanks

**Describe the bug**
Description of what the bug is.

**To Reproduce**
2. Tap on '....'

**Expected behavior**
Description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain.

**Device:**
 - Device: [e.g. OnePlus 5]
 - OS: [e.g. Lineage OS 16.0]
 - Version [e.g. v4.0]

**Additional context**

**Comment by jamal2362** [comment]
That all Stations sometimes disappear as soon as you press a station, but the stations come back after a second.

How does that happen?
I have over 100 station and if you have selected about 40 station, this happens quite often.
Device: OnePlus 8 Pro / Latest OOS.

The feature with importing playlists I already suggested but it was unfortunately rejected.

**Comment by y20k** [comment]
@puzzlled 

That is a worst case bug. I am terribly sorry that you permanently lost all your stations. I do not have any idea how that could happen.

Depending on the kind of backup you have, there might be a way to get back your stations. **If you have a backup copied over from Transistor v3 (= multiple m3u files)**, you could do the following to trigger the import again.

1. Uninstall Transistor
2. Install v3.2.4: [Play Store / GitHub](https://github.com/y20k/transistor/releases/tag/v3.2.4) or [F-Droid](https://f-droid.org/repo/org.y20k.transistor_71.apk)
3. Start the app once
4. Copy over your Backup
5. (Without an uninstall) update to the most recent version [Play Store / GitHub](https://github.com/y20k/transistor/releases/latest) or [F-Droid](https://f-droid.org/packages/org.y20k.transistor/)
6. Open the app and wait for the import to finish.

I have a question about your particular case. Did the upgrade from v3 to v4 work and the stations disappeared some time (hours/days) later? That would point to a problem with the way v4 is storing data. Or did the upgrade from v3 to v4 not work at all (no stations after update)?

In any case: if you have an idea, how I could reproduce the bug, that would be a HUGE help.

**Comment by easyKL** [comment]
Same here.
Update from 3.2.4 to 4.0.X and when I open the app the data wasn't there anymore.
Also the App Theme went back to light instead the one I had chosen.
I had a backup of playlists and PNG, and not that many stations, so add them wasn't painful at all.
Unfortunately I cannot provide any other info to reproduce the bug :(

**Comment by y20k** [comment]
Does the suggested "solution" work?

**Comment by puzzlled** [comment]
I haven't tried it yet. Maybe today.
By the way, my 'backup' was just me copying the entire 'Collection' folder.
I thought if I placed it on anothrr device it would just work, but I
haven't tried that yet either.

**Comment by puzzlled** [comment]
Apparently not. When I reverted to v3 all of my stations were there and it worked. When I updated to v4 no stations appeared and the directory was also emptied, which is bad. So I reverted to v3 and copied things back and it works again.

On July 12, 2020 11:37:35 AM MDT, y20k <notifications@github.com> wrote:
>Does the suggested "solution" work?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/y20k/transistor/issues/283#issuecomment-657253293

-- Sent from /e/ Mail.

**Comment by y20k** [comment]
@puzzlled I know that this is probably not helping in your case, but here is a screencast illustrating how the import from v3 to v4 should have worked. Note: The import takes a while.


<a href="https://user-images.githubusercontent.com/9103935/87429939-c7970500-c5e4-11ea-9c80-b57141e88a98.gif"><img src="https://user-images.githubusercontent.com/9103935/87429939-c7970500-c5e4-11ea-9c80-b57141e88a98.gif" width="360"></a>

**Comment by y20k** [comment]
@jamal2362 

> That all Stations sometimes disappear as soon as you press a station, but the stations come back after a second.
> ...
> I have over 100 station and if you have selected about 40 station, this happens quite often.

I have never tested Transistor with more than 20 stations. There must be a performance bottleneck somewhere. Over at my other project Escapepod a user found that the use of `View.setImageURI` might be problematic (see related [Issue](https://github.com/y20k/escapepod/issues/39)).

I adapted the solution found there to Transistor - see [commit](https://github.com/y20k/transistor/commit/c846c73b01fe6c4c40cde5aa014b680b0a1ae693). I hope that fixes some of the performance issues you seem to have.

**Comment by jamal2362** [comment]
**@y20k** 
> I have never tested Transistor with more than 20 stations. There must be a performance bottleneck somewhere. Over at my other project Escapepod a user found that the use of `View.setImageURI` might be problematic (see related [Issue](https://github.com/y20k/escapepod/issues/39)).
> 
> I adapted the solution found there to Transistor - see [commit](https://github.com/y20k/transistor/commit/c846c73b01fe6c4c40cde5aa014b680b0a1ae693). I hope that fixes some of the performance issues you seem to have.

This fixed the issue.
Thank you!
No disappear anymore, tested with 400 Stations for test purposes

**Comment by y20k** [comment]
400 stations. wow. :+1:

**Comment by y20k** [comment]
#294 deals with disappearing stations too - closing this one.
