### ISSUE TITLE
Playback behavior in Android Auto App

### ISSUE THREAD

**Issue by y20k** [y20k/transistor#285]
@Bolsderac brought up some problems with the playback behavior in the Android Auto App (see #284)

My current test version of Transistor exhibits the following behavior. Can anyone (@Bolsderac ?) tell me if that is normal behavior? I am not a a User of Android Auto myself. I find it strange, that playback continues no matter what (=> Scenario 1)-

### Scenario 1

1. User has selected Transistor in Android Auto
2. User starts playback of station no. 2 in Android Auto
3. User stops playback in Android Auto
4. User swipes away the playback card in Android Auto (!)
5. User exits Android Auto
6. User force stops Transistor (Information > Force Stop) - just too make sure that Transistor is not running anymore
7. User starts Android Auto
8. Android Auto automatically starts playback of station no. 2

### Scenario 2

1. User opens Transistor
2. User starts playback of station no. 3 in Transistor
3. User stops playback in Transistor
4. User force stops Transistor (Information > Force Stop) - just too make sure that Transistor is not running anymore
5. User starts Android Auto
6. Android Auto automatically starts playback of station no. 3

### Scenario 3

1. User starts Android Auto
2. Android Auto automatically starts playback of last station
3. User exits Android Auto
4. Transistor playback continues in Notification

**Comment by Bolsderac** [comment]
Scenario 1, 2 and 3 are OK for me

**Comment by y20k** [comment]
The new version of Transistor ([v4.0.3](https://github.com/y20k/transistor/releases/tag/v4.0.3)) will continue playback of last played station in Android Auto. It should be soon available in F-Droid and in the Play Store.

**Comment by Bolsderac** [comment]
Thanks 👍
