### ISSUE TITLE
playback should continue after closing the app

### ISSUE THREAD

**Issue by 532910** [y20k/transistor#286]
I believe that an old behavior was correct: if you close the app swipeing it up, the playback should continue. Check SoundCloud and VLC to example.

**Comment by y20k** [comment]
I am not sure what the best behavior is. Spotify and [UAMP](https://github.com/android/uamp/) (the official audio player sample app  from Google) both stop playback, when the app is killed via the task switcher.

**Comment by 532910** [comment]
I believe that closing all windows must have the same behavior.

While now it differs for the playback started from a shortcut and from the app.

**Comment by y20k** [comment]
Not sure if I understood your last comment correctly.

I made a short screencast illustrating how UAMP behaves: 

- closing UAMP via task switcher, stops playback and removes playback notification.

<a href="https://user-images.githubusercontent.com/9103935/87666255-93e4e800-c768-11ea-86fb-0445054030ed.gif"><img src="https://user-images.githubusercontent.com/9103935/87666255-93e4e800-c768-11ea-86fb-0445054030ed.gif" width="260" /></a>

UAMP is Googles reference implementation for audio playback. So I think Transistor is behaving correctly. **BUT** in this case there may be good arguments for continuing playback after the app is closed. Not sure how to decide, whats best.

**Comment by 532910** [comment]
> Not sure if I understood your last comment correctly.

When you start playback from a shortcut it doesn't open the window, so closing all windows doesn't affect playback.

When you start playback from the app and do the same action (close all windows): playback will stop.

Under "close all windows" I mean close all windows button that closes all windows (:

![image](https://user-images.githubusercontent.com/14617699/87669951-897e1a80-c777-11ea-9691-7cbedba97bd3.png)

**Comment by y20k** [comment]
> Is it clear now?

Yes. Thanks. That button basically swipes all apps from the task switcher.

**Comment by 532910** [comment]
Yes. And I believe the behavior must be the same regardless of how the playback was started.

**Comment by y20k** [comment]
Okay. Close all windows and manual swipe result in different outcomes?

**Comment by y20k** [comment]
PS. I understand that it is strange that when playback started from a shortcut the "close all windows" button has a different effect that when playback started by the app.

**Comment by 532910** [comment]
> Close all windows and manual swipe result in different outcomes?

Nope, result is the same.

**Comment by 532910** [comment]
> I understand that it is strange

Do not you agree now to not stop playback closing the app?

More side effects:
1. If you expect that app closing stops playback you can't do this if it was started from a shortcut (as there was no window).
2. Start playback from shortcut, open transistor app, close it. Playback will stop, but this is an unexpected event!

**Comment by 532910** [comment]
The most annoying thing:
1. start playback via shortcut
2. tap notification to open app and copy track name
3. close just opened app

**Comment by y20k** [comment]
The new version of Transistor ([v4.0.3](https://github.com/y20k/transistor/releases/tag/v4.0.3)) will continue playing even when the app was swiped away in the app switcher. It should be soon available in F-Droid and in the Play Store.

**Comment by 532910** [comment]
Thank you!
