### ISSUE TITLE
"Add New Station" search returns nothing

### ISSUE THREAD

**Issue by nognir** [y20k/transistor#287]
**Describe the bug**
Searching for a station through the "Add New Station" button returns no found station, just keeps searching.

**To Reproduce**
1. Go to app's home screen.
2. Tap on 'Add New Station'
3. Write down a station's name
4. Wait forever for matching stations

**Expected behavior**
A list of matching stations

**Screenshots**
![Screenshot_2020-07-27-00-53-15-735_org y20k transistor](https://user-images.githubusercontent.com/3681224/88490332-9da9ef00-cfa3-11ea-86ae-3cb31b2b99d2.jpg)

**Device:**
 - Device: Xiaomi Pocophone F1
 - OS: Android 10
 - Version: MIUI Global 11.0.9

**Additional context**
www.radio-browser.info alerts about its API change, explaining:
"""If you still use the api at
www.radio-browser.info/webservice you should switch as soon as possible to the new one at
api.radio-browser.info. The old one is not supported anymore and will not receive any more updates on the software side. The new one is in place and stronger than ever (multiple servers). The api endpoints at www.radio-browser.info/webservice will be taken down at August 1. of 2020."""

**Comment by y20k** [comment]
@nognir 

Transistor is using the "new" API. That should not be the cause of the problem, you are experiencing. I am am not able to reproduce the bug. It works / should work like this:
<a href ="https://user-images.githubusercontent.com/9103935/88516224-3b75dc00-cfed-11ea-8d40-8ff6c1c195a6.gif)"><img src="https://user-images.githubusercontent.com/9103935/88516224-3b75dc00-cfed-11ea-8d40-8ff6c1c195a6.gif" width="320" /></a>

Not sure what to do now... The [Radio Browser API](https://api.radio-browser.info/) works like this:

1. Transistor request a random radio-browser server from https://api.radio-browser.info/
2. Transistor hands over the search input (example "BBC RADIO") to the server received in (1)

If you are still experiencing the problem, you could try replicate step 2 in a web browser: Just follow this link:
https://de1.api.radio-browser.info/json/stations/search?name=BBC%20RADIO (maybe you need to adjust the search term).

You could manually try out other radio browser servers, too.
https://fr1.api.radio-browser.info/json/stations/search?name=BBC%20RADIO
https://nl1.api.radio-browser.info/json/stations/search?name=BBC%20RADIO

**Comment by nognir** [comment]
The manual URLs did work, the app did not. The issue, surprisingly, lied with the system language, which uses a non-latin character set (Greek). Changing language to English made the search function work properly. Should the search be dependent on it for proper operation?

**Comment by y20k** [comment]
I found the problem. Transistor was using the application name as `User-Agent` for the request. radio-browser seems to have problems with non-latin characters for user agents.

**Comment by Long-FA** [comment]
I would like to reopen this issue because I am getting the same problem. I get infinite loop when trying to search anything in the search bar. I can still manually paste a station address and play it, but there is no station icon. Radio2 by Sergey Alex works fine on my phone so it's probably something related to the way Transistor communicates with Radio-browser API.

**Comment by y20k** [comment]
@Long-FA 
Do you still experience the problem? Search works on my phone without any issues. But the version on my phone is a dev version that differs slightly from the official one. But also when installing the current version on a fresh Android Emulator I am not able to reproduce the problem. Are you doing anything special on your device? Which language is your Android system set to?

**Comment by Long-FA** [comment]
I am using LineageOS 18.1. Language is set to English (US), I tried changing to English (UK) but it doesn't work either. App version is 4.0.14 on F-Droid. I'll try to dig around to see what i can find.

-------- Original Message --------

**Comment by Long-FA** [comment]
So after a few days I reinstalled Transistor and it magically worked, despite the fact that i tried reinstalling multiple times before to no avail. Nothing changed on my phone, it just suddenly works. I know it sounds stupid but it's just like that.

**Comment by y20k** [comment]
I am glad that search works for you again :+1:
