### ISSUE TITLE
Enable multiple streams for the same radio station

### ISSUE THREAD

**Issue by DOFfactory** [y20k/transistor#292]
**Is your feature request related to a problem? Please describe.**
No problem, but it would be great to be able to choose between various bitrates of the same radio station. A good example is here: [http://live.slovakradio.sk:8000/](http://live.slovakradio.sk:8000/) where the various stations have often a 32kbps, 128kbps, and 256kbps streams

**Describe the solution you'd like**
It would be great to introduce a bitrate/link choice for the stations, and not having to add them under different headings

**Describe alternatives you've considered**
Currently I have to name the stations as: Station 1 [32kbps], Station 1 [128kbps], Station 1 [256kbps], Station 2 [32kbps]. Instead, we should have Station 1, with 3 possible bitrates.

**Comment by y20k** [comment]
I like the idea. Actually I planned on implementing this, when I rewrote the app recently. The data structure ([Station.kt](https://github.com/y20k/transistor/blob/v4.0.5/app/src/main/java/org/y20k/transistor/core/Station.kt#L35)) can hold several stream addresses. But in the end I did not implement the UI for this. There are several problems I was not able to solve within the constraints I set myself for the app (=> mainly: single window app).

1. Playback
I was not sure how to implement a one-tap playback option, when a station can have several streams. Larger station tiles in the station list might be a way to go.

2. Adding / Editing Stations
The new search feature does not support several streams per station. Aside from "search" the other way to add stations would be tapping on an m3u/pls link. Here a (small?) percentage of playlist files contain multiple streams. In cases like this Transistor could simply add all streams in a playlist file. But then you should be able edit the name of individual streams. Lastly you could / should probably be able to add a stream to an existing station or enable users to edit streams completely manual (copy&paste).

All in all that would be way too much work given the few time I have to spare for working on Transistor. Maybe this feature would be good start for an external contributor.

There is a related issue (#206), which suggest a workflow for playback. It is linked to from Issue 48 ("[Previous discussions and feature requests #readmefirst](https://github.com/y20k/transistor/issues/48)"). Developers interested in contributing to this project should be able to find this feature request.
