### ISSUE TITLE
icons background

### ISSUE THREAD

**Issue by 532910** [y20k/transistor#293]
![image](https://user-images.githubusercontent.com/14617699/89496631-60273c00-d7c3-11ea-8eb5-5e7c431f6a7a.png)![image](https://user-images.githubusercontent.com/14617699/89496587-48e84e80-d7c3-11ea-9ff2-394ef4af90a2.png)

Do you really love these background gradient drops? The most icons has a flat or smooth gradient background.

**Comment by y20k** [comment]
Yes. That was a deliberate choice. Inspiration came from the [Reeder](https://apps.apple.com/us/app/reeder-4/id1449412357?ls=1) app. I am not considering any change here at the moment.

**Comment by 532910** [comment]
Hm, Reeder app's icon looks better due to background bands are more contrast to each other.

BTW, Escapepod icon has now shadow, but Transistor has it.

**Comment by y20k** [comment]
What do you like better. With or without drop shadow?
