### ISSUE TITLE
Notification resurrects itself and shows as playing when stopped and cannot be dismissed.

### ISSUE THREAD

**Issue by vigilvindex** [y20k/transistor#297]
**Describe the bug**
Notification resurrects itself and shows as playing when stopped. Pressing the stop button has no effect. Unable to swipe away to dismiss notification.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start app.
2. Play a station.
3. Stop station from notification and swipe to dismiss notification.
4. Wait until notification returns with above described behaviour.

**Expected behaviour**
After step 3 the notification should never resurrect itself to incorrectly display the apps current status as playing when it is stopped.

**Device:**
 - Device: Samsung Galaxy Note9 Exynos
 - OS: Android 10
 - Version N960FXXS6ETH4

**Comment by y20k** [comment]
see also #274

**Comment by y20k** [comment]
the update to [v4.0.6](https://github.com/y20k/transistor/releases/tag/v4.0.6) should fix the issue.

**Comment by vigilvindex** [comment]
4.0.5 still has the issue.
