### ISSUE TITLE
Support for FM radio (offline radio)

### ISSUE THREAD

**Issue by Mhowser** [y20k/transistor#300]
I haven't found any FOSS apps that can use the FM radio chip in some phones, it would be really cool if you could support them. I know NextRadio can do this, but they are not open source.

**Comment by y20k** [comment]
On the surface that might be a good idea. Who cares where the audio comes from, as long as it is radio, right? 

Thinking about it a bit longer... internet radio and FM radio have differences. That would have to show in the user interface at a lot of places. Station List, Player, Search, Error handling. Additionally there is no standard API to access FM chipsets in a device. Meaning: support for FM would require a lot of reverse engineering, plus access to real hardware for testing.

If Transistor was a bigger more complex app to begin with, adding FM radio would not be such a huge change. But Transistor is supposed to be a very lean app: Basically just a list of streams and a play button. I do not want the app to get any more complicated. Not for the users, and especially not for me. I am a hobby developer with not a lot of free time at my disposal. I probably could not handle the complexity that FM radio would bring to the app. 

I concur that there should be an FOSS app for FM radio, but that should/must be a different project.
