### ISSUE TITLE
Station manual add

### ISSUE THREAD

**Issue by Sergei-Alekseev** [y20k/transistor#301]
Cant add some stations. For exam Radio Ultra or Dark Bites.
Nothing is found.

Can you pls add an option to add station manually?
Name, icon, url.
Thanks.

**Comment by y20k** [comment]
@Sergei-Alekseev 

Sorry for the late answer. Could you please provide an example URL? (You should be able to add most stream addresses directly via copy and paste into the search field.)

**Comment by Sergei-Alekseev** [comment]
On October 19, 2020 15:35:42 y20k <notifications@github.com> wrote:
>
> @Sergei-Alekseev
> Sorry for the late answer. Could you please provide an example URL? (You 
> should be able to add most stream addresses directly via copy and paste 
> into the search field.)
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks.
I was confused by autosearch feature, excuse me.
