### ISSUE TITLE
Forward/Rewind within the downloaded buffer

### ISSUE THREAD

**Issue by Utini2000** [y20k/transistor#304]
**Is your feature request related to a problem? Please describe.**
I am comming from TuneIn and one great feature I am missing is to forward/rewind within the already downloaded buffer. This allowed me to basically skip advertisings on stations by just forwarding +10 or +30 seconds until the next song.

**Describe the solution you'd like**
A forward/rewind button (e.g. +30 or -30) next to the play/pause button

**Comment by y20k** [comment]
Hi @Utini2000 

I understand what what you want. But this is not a planned feature at the moment. Transistor is a hobby project. I am sticking with a very basic feature set for this app to keep the project manageable.
