### ISSUE TITLE
add several last played station to shortcuts

### ISSUE THREAD

**Issue by 532910** [y20k/transistor#307]
Please add more last station to shortcut list.

![image](https://user-images.githubusercontent.com/14617699/96420961-d6eaa780-11fe-11eb-8157-acf8e0d2229a.png)

**Comment by y20k** [comment]
Hi @532910 

I am not planning to implement this at the moment. I do not have enough free time at hand. A "solution" for most users, that want quick access to often used stations, would be: Place shortcuts of those station son the homescreen.

**Comment by 532910** [comment]
Shortcuts takes up screen space.

> I do not have enough free time at hand.

I don't ask you to fix this asap, but you can leave it open until better times, possibly someone else could PR.

For example https://github.com/brarcher/loyalty-card-locker, https://github.com/gsantner/markor and  https://github.com/android-password-store/Android-Password-Store has this feature.

![image](https://user-images.githubusercontent.com/14617699/96485290-39669680-1245-11eb-9ceb-02e6b6b9904c.png)

**Comment by y20k** [comment]
I added the tag `help wanted` and I referenced it in the section "Issues tagged with enhancement, help wanted" within the Issue 
[Previous discussions and feature requests #readmefirst](https://github.com/y20k/transistor/issues/48)

I know myself, I will very likely not implement this myself :nerd_face: But you are right. This feature could be implemented by someone else.
