### ISSUE TITLE
Import / Export function & Grid view

### ISSUE THREAD

**Issue by naderi** [y20k/transistor#311]
Thanks a lot for your great work. These two features are welcome:
- **Backup and Restore**
I would like to have an ability to export and import or backup and restore the Sender list to/from SD-card or Dropbox & co.
- **Grid view**
Grid view in Sender page helps if we have a long list of radio stations.

**Comment by y20k** [comment]
Hi @naderi 

**Backup/Restore** is a feature I would like to see, too. There is an issue covering this in [Previous discussions and feature requests #readmefirst](https://github.com/y20k/transistor/issues/48): 

- [[Feature Request] Import and export of station list / URLs etc](https://github.com/y20k/transistor/issues/126)

**Grid View**.... Mhh. I see the general appeal. But there are a couple of reasons against that:

- the current UI relies on swiping and long press actions. that would be hard to implement in a grid tile
- grid tiles have larger images but are not guaranteed to have good quality images
- the general philosophy behind the app: keep it simple (for the developer and user). I often rejected UI feature requests like manual sorting etc. in the past

So not to grid view. Sorry.
