### ISSUE TITLE
Playing problem: not the selected but a different radio station is being played

### ISSUE THREAD

**Issue by ralxxx** [y20k/transistor#313]
**Describe the bug**

- I have a list of various radio stations on my transistor installation.
- there's a strange behavior with the first 2 in the list: If I click on the first one, the first radio station starts playing. BUT if I click on the second one it is as well the first radio station playing. For stopping it works the same way.  
This behavior I can only observe for the first 2 in the list. 

**To Reproduce**
- The 2 radio stations I have in my list are "Deutschlandradio Nova" and FIP (French public radio)
- DLF Nova link: http://dradio-edge-3094-fra-ts-cdn.cast.addradio.de/dradio/nova/live/mp3/128/stream.mp3?_art=dj0yJmlwPTk1LjE3OS4xMzkuMTA2JmlkPWljc2N4bC16cTZlaHNhbmImdD0xNjA2MTgzNDk5JnM9Nzg2NmYyOWMjZWQ4YjFhMTIyNmY5OGUzMTdiMzkxOTE2OTJiMTY4OWI
- FIP: http://icecast.radiofrance.fr/fip-midfi.mp3

For now, I am not able to reprodruce the issue. After having deleted FIP and having reinstalled it, everything works as expected. 
I am still sending you a log file - in hope that helps. 

**Screenshots**

[181_2radiostations-2-logcat_11-26-2020_09-12-18.txt](https://github.com/y20k/transistor/files/5601543/181_2radiostations-2-logcat_11-26-2020_09-12-18.txt)

![180_2radiostations-1](https://user-images.githubusercontent.com/36100882/100328050-5de42a00-2fcc-11eb-9505-fe4171dd0241.jpg)

**Device:**
 - Device: Fairphone 3
 - OS: /e/OS
 - Version: Q 

**Additional context**

**Comment by mbomb007** [comment]
I have the same issue, but it's with any station, at least any of mine. I had 3, and as I started playing one, then I tapped to play another, but it wouldn't play any other station. After removing the one it was stuck on and playing another of my remaining 2, I was again unable to switch which was playing, even after restarting the app.

**Comment by y20k** [comment]
Hi @ralxxx ,

this issue seems to be very similar to #291 ("Cannot change station"). Can you confirm?

Cheers & have a nice week

**Comment by mbomb007** [comment]
Yes, that looks like the same issue.

**Comment by ralxxx** [comment]
> Hi @ralxxx ,
> 
> this issue seems to be very similar to #291 ("Cannot change station"). Can you confirm?
> 
> Cheers & have a nice week

Hi @y20k, not exactly the same behavior but it could be the same bug, yes.

**Comment by y20k** [comment]
I suspect the import from Transistor 3 has a flaw. But that is just a hunch. 

If anyone can report the steps to reliably recreate this bug ... that would help a lot.

**Comment by y20k** [comment]
I am closing this issue so that we do not have two discussions on the same/similar topic. Do not take this the wrong way. I am super glad you reported it!! THX
