### ISSUE TITLE
It's extremely hard to copy the track name

### ISSUE THREAD

**Issue by 532910** [y20k/transistor#314]
To copy the current track name to clipboard you need to hit exactly the inscription as the region around will collapse the bottom menu.

To reproduce, just swipe up the bottom menu and try to copy track name or streaming link.

Expected behavior: the hole square region (red highlighted on the screenshot below) must be used for copy action.

![image](https://user-images.githubusercontent.com/14617699/100560096-c6c9eb80-32c5-11eb-9705-47660c8cea5b.png)

Version 4.0.7 from F-Droid, Lineage OS 17.1

**Comment by y20k** [comment]
Good point. I increased the tap targets both for Currently Playing and Streaming Link. The fix will be part of v4.0.9.

![Screenshot from 2020-12-03 13-45-07](https://user-images.githubusercontent.com/9103935/101021710-8c37ab80-3570-11eb-977d-c993e36efd94.png)

**Comment by 532910** [comment]
Perhaps gaps should be completely removed and areas should be bigger:

![image](https://user-images.githubusercontent.com/14617699/101301714-bdeb9380-384a-11eb-9498-ce9bb999696d.png)

**Comment by y20k** [comment]
I considered your suggestion too. I would have had to change the layout quite significantly. Not the visible layout but the way it is constructed in background. Since the current change significantly improved the behavior already I did not walk the extra mile.

**Comment by y20k** [comment]
The fix has made it into the [v4.0.10](https://github.com/y20k/transistor/releases/tag/v4.0.10) release, that I published today. (v4.0.9 never came out - see: #325 :upside_down_face:)
