### ISSUE TITLE
Transistor One (3.x) - pls add add-new-station feature 

### ISSUE THREAD

**Issue by ralxxx** [y20k/transistor#315]
**Is your feature request related to a problem? Please describe.**
Not exactly

**Describe the solution you'd like**
I am aware that you actually stopped developing Transistor One (3.x) and that this version is only meant to help out users of older Android versions to still be able to use transistor. Still it is a really good and reliable piece of software. The only thing that actually is really missing is the add-new-station feature.  

**Describe alternatives you've considered**
Transistor 4.x but for the purpose described above it is too easy to do something unwanted. 

**Additional context**
I installed transistor 3.x on phones from some elder elder family members. It is simple, reliable and works well. Furthermore, they cannot 'break' anything easily, that's why they love the app. Even to delete stations it is rather complicated, so it cannot happen by mistake. Just the functionality to easily add a radio station is terribly missing.

**Comment by y20k** [comment]
Transistor 3 did not feature a search. I have no plans to backport this feature, although that would definitely be possible. The main reason for the rewrite of Transistor was back then the fact that the was v3 stored stations was broken. The search was just an add-on. But still, I simply do not have enough time (job, family ...). Sorry. Maybe someone else will find the time to do this.
I created an issue over at Transistor One (see https://github.com/y20k/transistorone/issues/1).
