### ISSUE TITLE
Google TV / Android TV availability

### ISSUE THREAD

**Issue by m-p-3** [y20k/transistor#316]
**Is your feature request related to a problem? Please describe.**
I've been using the app on my smartphone for some time, and I recently bought a new Chromecast with Google TV, so I figured it might be handy to have it available as an app there as well.

**Describe the solution you'd like**
Make it available on Google TV, and ensure it can be navigated with the remote.

**Comment by y20k** [comment]
Hi @m-p-3 

Sorry to disappoint, but I have no plans for porting the app to any other Android powered platforms, be it Android TV, Automotive OS or Wear OS. Two reasons:
- Porting is a lot of work :-)
- The mentioned platforms are not completely open source. The same reason why I am not adding [Google Cast support (#115)](https://github.com/y20k/transistor/issues/115)

**Comment by vlna** [comment]
Hi, I installed Transistor 4.0.16 from F-Droid to Android TV (v.9) Box and it works quite well. Only issue is to control Transistor with simple remote - there is not a full visual distiction to see where focus is (e.g. Play and Settings buttons have different background when focused) and it makes control hard.
