### ISSUE TITLE
Doesn't reconnect if stream fails

### ISSUE THREAD

**Issue by infozsoda** [y20k/transistor#32]
I listen to streams over Tor (Orbot), and sometimes its circuits fail. Or the Wi-Fi goes down and comes right up again. It would be nice if Transistor tried to reconnect aggressively (like once per second?) until the user stops the stream.

**Comment by y20k** [comment]
I noticed that problem too. I'll look into it.

**Comment by infozsoda** [comment]
Cool! I've gone through my logs (on CM13 / Android 6.0.1), and noticed that interrupted TCP connections don't seem to generate any error events, but always the following sequence (higher layer log messages elided):

`02-01 13:38:35.691  4386 20349 D NuPlayerDriver: notifyListener_l(0x4128b400), (200, 703, 0)`
(that's MEDIA_INFO_NETWORK_BANDWIDTH)

`02-01 13:38:35.692  4386 20349 D NuPlayerDriver: notifyListener_l(0x4128b400), (200, 701, 0)`
(that's MEDIA_INFO_BUFFERING_START)

`02-01 13:38:37.692  4386 20349 D NuPlayerDriver: notifyListener_l(0x4128b400), (200, 703, 0)`
(that's MEDIA_INFO_NETWORK_BANDWIDTH)

`02-01 13:38:37.692  4386 20349 D NuPlayerDriver: notifyListener_l(0x4128b400), (200, 702, 0)`
(that's MEDIA_INFO_BUFFERING_END)

`02-01 13:38:37.705  4386 20349 D NuPlayerDriver: notifyListener_l(0x4128b400), (6, 0, 0)`
(that's MEDIA_STARTED)

`02-01 13:38:40.098  4386 20349 D NuPlayerDriver: notifyListener_l(0x4128b400), (2, 0, 0)`
(that's MEDIA_PLAYBACK_COMPLETE)

Under the assumption that radio streams are infinite, I think it would work to just add this as a MediaPlayer.OnCompletionListener:

    mMediaPlayer.reset();
    mMediaPlayer.setDataSource(mStreamUri);
    mMediaPlayer.prepareAsync();

Maybe with a 1 second sleep to avoid hammering the server.

**Comment by y20k** [comment]
Oh. wow. Thanks. I'll give that a shot and implement it.

**Comment by infozsoda** [comment]
I just tested some more, a 1 second retry delay doesn't seem necessary:

The OnCompletionListener would only be called when something was actually played -- if you then attempt to reconnect, NuCacheSource2 would automatically make 10 connection attempts (seems like one per second) and if these fail, call OnErrorListener instead (which doesn't retry, so no danger of hammering).

**Comment by y20k** [comment]
I am testing as you write, too :-) you suggestion seems to work fine!

**Comment by y20k** [comment]
I did test your suggestion by switching of WiFi. I works really nice. 

I was aware of the problem before, but I was reluctant to fix it. I thought that required me to request additional permissions to monitor network status.

You solution is very elegant and lean. Thank you!!

**Comment by infozsoda** [comment]
Thank *you* for implementing it so quickly. I'm looking forward to testing all these new features!
