### ISSUE TITLE
I´m able to rename the station to zero characters.

### ISSUE THREAD

**Issue by jamal2362** [y20k/transistor#322]
**Describe the bug**
I can rename a station to zero characters.

**To Reproduce**
1. Rename a station to zero characters.
2. See the issue.

**Expected behavior**
Min length >1 character.

**Screenshots**
![Screenshot_20201207-202417](https://user-images.githubusercontent.com/15986930/101395638-83294000-38ca-11eb-848f-1a49d19e1d25.jpg)

**Device:**
 - Device: OnePlus 8 Pro
 - OS: OOS 11

**Comment by JonnyTech** [comment]
Just curious, but why would you want a nameless station?

**Comment by jamal2362** [comment]
I was just looking for bugs but it can happen that it is accidentally deleted. (Unintentionally)
It also damages the .json file.
A small change in the code will most likely prevent this.

**Comment by y20k** [comment]
Thx for the bug report. I will look into this.

**Comment by y20k** [comment]
The bug is fixed in [v4.0.10](https://github.com/y20k/transistor/releases/tag/v4.0.10). THX
