### ISSUE TITLE
Please try to tag in sync with version

### ISSUE THREAD

**Issue by licaon-kter** [y20k/transistor#325]
I'll fix it now for F-Droid but henceforth :)

Ref: https://github.com/y20k/transistor/blob/v4.0.8/app/build.gradle#L15
Ref: https://f-droid.org/wiki/index.php?title=org.y20k.transistor/lastbuild_80&oldid=284003

**Comment by y20k** [comment]
Upps. And thank you. The correct `versionName` would have been `v4.0.8` 💣

Sometimes the bug sits in front of the keyboard.

**Comment by y20k** [comment]
@licaon-kter 

The upcoming `versionName` will then be `v4.0.9`. Will that cause problems / should I skip straight to `v4.0.10`?

**Comment by licaon-kter** [comment]
Skip to v4.0.10 please :)

**Comment by y20k** [comment]
New version is [published](https://github.com/y20k/transistor/releases/tag/v4.0.10) and versionName is [v4.0.10](https://github.com/y20k/transistor/blob/v4.0.10/app/build.gradle#L15).
