### ISSUE TITLE
Shortcut 

### ISSUE THREAD

**Issue by Teonash65** [y20k/transistor#329]
Shortcuts of favorites on the desktop do not work.

 - Device: Samsung Galaxy S10 Lite 
 - OS: Android 11 
 - Nova Launcher Prime

**Comment by y20k** [comment]
Hi @Teonash65 
I tried to reproduce the problem on my device with Android 11 and Nova Launcher. But it seams to work. Here is what I did:
1. select "Place on Home screen" in Transistor
2. switch to Home screen
3. (kill Transistor)
4. tap on shortcut
(Works with and without step 3.)

**Comment by Teonash65** [comment]
Thanks! It works and I found the bug. 

Shortcut don't work, if I change the shortcut with a  logo. It's not a bug of your app. 
Sorry!

**Comment by y20k** [comment]
No problem. Take care
