### ISSUE TITLE
Track artist/title info

### ISSUE THREAD

**Issue by infozsoda** [y20k/transistor#33]
... would be amazing :)

**Comment by y20k** [comment]
I agree ^o^. I'll look into it. But please do not expect too much. I am working on this app only in my spare time (which is not much at the moment).

**Comment by y20k** [comment]
Okay. I did look into it. As far as I can judge there are two problems. 

I try to stick with the original Android toolkit. That means no external libraries. Android itself offers two methods that are relevant. 

1. [MediaPlayer.OnInfoListener](http://developer.android.com/reference/android/media/MediaPlayer.OnInfoListener.html)
In theory that should ensure that the app gets notified when metadata changes. I implemented such a listener, it works fine (e.g. for buffering updates). But the case MEDIA_INFO_METADATA_UPDATE never gets selected. Not good.

2. [MediaMetadataRetriever](http://developer.android.com/reference/android/media/MediaMetadataRetriever.html)
This method gets metadata from a media. I implemented it, and it works. But only for the metadata "METADATA_KEY_MIMETYPE". The important metadata like artist and title can not be retrieved through MediaMetadataRetriever. Also not good.

You can see the way I implemented it in one of the last [commits](https://github.com/y20k/transistor/commit/5ebcf239bd1e1cfc54a1409c0bca733d67a87c1f). 

Maybe there is another way, or maybe the next release of Android with enhance MediaMetadataRetriever and/or MediaPlayer.OnInfoListener. But for now: **no artist/title info.** Sorry. I would have been a nice feature.

**Comment by y20k** [comment]
I will add a "help wanted" flag. Maybe someone else has a good idea how to get to the metadata using just the Android SDK.

**Comment by y20k** [comment]
I don't know how to get the metadata from a stream using the basic Android libraries. I will close this issue but keep it in the previous issues list (#48).

**Comment by franciscot** [comment]
I don't understand code but if it helps:
https://stackoverflow.com/questions/11327954/how-to-extract-metadata-from-mp3

And another app but I'm afraid it use ffmpeg:
https://github.com/yomguy/servestream/tree/c5934bd79aafc388fe39c1fe65b849f5afd223f2/app/src/main/java/net/sourceforge/servestream/media

**Comment by y20k** [comment]
Thanks for your suggestion. I did try the first method utilizing Androids's own [MediaMetadataRetriever](http://developer.android.com/reference/android/media/MediaMetadataRetriever.html). Sadly it did not work out. See this [commit](https://github.com/y20k/transistor/commit/5ebcf239bd1e1cfc54a1409c0bca733d67a87c1f).
