### ISSUE TITLE
Support for more formats

### ISSUE THREAD

**Issue by dreimanis** [y20k/transistor#331]
![Screenshot_20210109-144426__01](https://user-images.githubusercontent.com/77197750/104092590-947cb800-528d-11eb-8136-c9ba5e82b946.jpg)
My local station supports many different streaming formats.
Transistor allows me to only use MP3.
I'm curious wether it would be possible to add more formats to Transistor.

**Comment by y20k** [comment]
AAC and OGG should work. But you are right MP3 streaming is almost the standard for internet radio.

**Comment by jamal2362** [comment]
Hi,

I don't understand the problem with the MP3 streams. 
They play correctly and I could not see anything negative so far?

Greetings
Jamal

**Comment by dreimanis** [comment]
Jamal,
there is absolutely no problem with the MP3 streams; what I wanted was to see whether support for additional codecs would be possible.
