### ISSUE TITLE
Not all stations from an M3U are added

### ISSUE THREAD

**Issue by jamal2362** [y20k/transistor#336]
**Describe the bug**
Not all stations from an M3U are added.

**To Reproduce**
1. Enter this address "https://www.energy.de/energy.m3u" in the search and press "Add"
2. Only the first Station will be added. But the M3U has over 40 Stations included.
3. See the error

**Expected behavior**
That it adds all from the m3u and not just the first station.
I have not tried a .pls file now, so I don't know if the error is known there too.

**Screenshots**
![Screenshot_20210121-123040](https://user-images.githubusercontent.com/15986930/105345527-aa22a380-5be4-11eb-8bd9-4e68fff46cda.jpg)

**Device:**
 - Device: OnePlus 8 Pro
 - OS: OOS 11 / Android 11
 - Version: Latest

**Comment by y20k** [comment]
@jamal2362 this bug is pretty similar to #337 and #330. I would like to consolidate the discussion and have it on #330, if that is okay.
