### ISSUE TITLE
Cannot import playlist from storage

### ISSUE THREAD

**Issue by pelya** [y20k/transistor#337]
I've tried to import a playlist from my desktop audio player, and found it complicated.

1. There's no 'Import playlist' button in Transistor. Master branch contains new code for 'Export playlist' button, so there should also be 'Import playlist' button.
2. I've copied my playlist.m3u file to my phone storage, and tried to open it with a file manager. It launched Transistor, but could not read the file (no SD card permission).
3. But that would not stop me from putting the playlist to my local web server. It's just 'sudo apt-get install apache2', copy file to `/var/www/html`, delete index.html, and done.
4. Unfortunately, Transistor cannot load playlist with several stations, only the last station remains.
5. So I've removed `#EXTM3U` header and split it into smaller playlists: `split -l 2 -d --additional-suffix=.m3u playlist.m3u playlist-split-`
6. Fortunately Transistor ignores `#EXTM3U` header, so it loads my split .m3u files with no issue
7. Open Firefox, Go to 192.168.0.100 (or whatever your web server address is). Click on the .m3u file. Click 'Open in app'. Repeat 26 times.

Well, my suggestion is at least to support playlists with multiple stations, I remember this worked some time ago with 'stream selection' dialog.

**Comment by y20k** [comment]
Although I know this issue is not exactly the same as #330, I would like to close this one. Lets keep the discussion in one place.

**Comment by y20k** [comment]
BTW. I realized it was your contribution (#175) that enabled the stream selection for playlists with multiple stream addresses. I should bring that back. It somehow got lost during the rewrite of the app (#251).

Probably as you suggested via an "Import playlist" feature. The dialog should feature a multi-select form so that users can import more than one stream.
