### ISSUE TITLE
Google Cast support / Android Sender

### ISSUE THREAD

**Issue by seb4web** [y20k/transistor#339]
I would like to stream on my Google Chromecast Audio device by using the share button. So I would appreciate the implementation of the Android Sender SDK.

**Comment by zynexiz** [comment]
Can recomend AirMusic, works on some non rooted devices to. Used it myself for a long time.

**Comment by y20k** [comment]
Hi @seb4web 

Thanks for the feature request. I hope you are not too disappointed, but there are no plans for Google Cast in the foreseeable future. See also #115
