### ISSUE TITLE
Problem with translating

### ISSUE THREAD

**Issue by jakubfabijan** [y20k/transistor#340]
I wanted to make Espernato translation on weblate so i added it, but after that it said that I "translated everything from 0 strings" and now it says the translation is complete but i didn't even started it :confused: 
![screenshot](https://user-images.githubusercontent.com/53099243/107622450-247c9b80-6c58-11eb-9060-65f653802f70.png)

**Comment by y20k** [comment]
Hi @jakubfabijan 
pretty cool that you want to help out with Esperanto! One thing to try: Just translate a single string and see what happens then.

**Comment by jakubfabijan** [comment]
![Screenshot_20210213-202439~2](https://user-images.githubusercontent.com/53099243/107859439-b5f73380-6e39-11eb-8f89-36c984616541.png)
Weblate says that there are no strings so I can't translate "single string"

**Comment by y20k** [comment]
Hi @jakubfabijan 
Okay. I see. I translated a single string here in the repository. (see [commit](https://github.com/y20k/transistor/commit/2f84600f1b69e0cdfc44238e9179edfe7531239e)). That seemed to have triggered an update at Weblate. There are now 193 strings available for translation.

**Comment by jakubfabijan** [comment]
Thank you :smiley:
