### ISSUE TITLE
User Interface enhancements

### ISSUE THREAD

**Issue by CrepeTF** [y20k/transistor#341]
**Is your feature request related to a problem? Please describe.**
The app currently, while, looks quite standard, it could be more contemporary.

**Describe the solution you'd like**
Tweaks to the interface, which could take place over a stretched out period of time.

**Describe alternatives you've considered**
N/a

**Additional context**
Here I've created a mock-up of what said UI could look like in the future, based on the current interface in Adobe XD:
![Screenshot_20210225-200223.jpg](https://user-images.githubusercontent.com/70870719/109210188-694e1980-77a4-11eb-9223-286e22a9f747.jpg)

**Comment by CrepeTF** [comment]
As I'm trying to learn Android development at the moment, I would be open to make PRs and such for some stuff

**Comment by CrepeTF** [comment]
I've created a fork WITH the changes [here](github.com/CrepeTF/Junction/)
It also has an apk should you want to see it for yourself

**Comment by jamal2362** [comment]
This stroke that is around "ADD NEW STATION" could also be applied to the station card, would certainly look good.

**Comment by CrepeTF** [comment]
It would look good, although I specifically chose not to since I think it looks 'cleaner' without.

As for the font at the top it is Product Sans, although that should be changed to something else.

**Comment by y20k** [comment]
Hi @CrepeTF 

I installed your fork on a test device and it looks pretty good already :+1: 

One thing you might want to know about me: I am pretty conservative in regards of changing the design and user interface of the app. I will probably keep the current design. But since your fork already has a new name and icon, the Junction can already stand on its own feet.

New design trends tend to stick with me a bit later than with others. But often they eventually do. So I might start copying ideas from Junction, if the license permits that and if that is okay for you.

**Comment by CrepeTF** [comment]
Sounds good to me @y20k, and I'm glad you liked my fork!

I totally understand and get wanting to keep the current design (and it does quite fit with the theme of the old transistor radios too!). It's very straight-to-the-point and simple to understand and I think that's already amazing.

If you ever feel the need to cherry-pick some ideas here and there from Junction please feel free to do so!

This project has been quite educational for me too, I have been looking around for a radio app for the past few days and Transistor's simplicity really resonated with me, so I really just pounced on the chance to get some practical Android dev-ing experience (and be able to use a killer radio app too).

I'm look forward to what you'll be able to bring to this app in the future.

(And thanks, I will be having a leer at the code from that pull you've linked at too  👀)
