### ISSUE TITLE
DLNA support

### ISSUE THREAD

**Issue by b-m-f** [y20k/transistor#343]
Hi there,

First of all thanks for the great app.

I'm currently lying in bed and want to start playback on my network connected receiver, but I'm too lazy to get the remote and just want to get my radio going ( Easier to go on Github and open a feature request ).

So far as to my motivation. 

I checked out the issues and found https://github.com/y20k/transistor/issues/115. Seems like you aren't opposed to this.

# How to do it?

## UI

I was thinking it might be nice to have a little stream icon in the radio overview when clicking on the bottom "now playing" section.

## Code 
Beats me, haven't worked in Kotlin yet.

I did some DLNA streaming  app a few years back though, and I believe that searching in a song was a pain. Since this isn't an issue here I would be happy to give it a go if you could point me to the correct part in the codebase.

If you still want this feature integrated that is :)

**Comment by y20k** [comment]
Hi @b-m-f 

You are right. I am interested in DLNA. I use it in my home stereo setup. I just was reluctant to try to implement it. Probably afraid of the expected workload.

I checked out how [UAMP](url) does implement Google Cast: In it's music service there is a [currentPlayer](https://github.com/android/uamp/blob/61b8f6aaad08ce04015b2f4d60a7071c51071c0f/common/src/main/java/com/example/android/uamp/media/MusicService.kt#L96). For local playback currentPlayer is a [SimpleExoPlayer](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/SimpleExoPlayer.html) - just like the one Transistor uses. For remote playback currentPlayer is a [CastPlayer](https://github.com/google/ExoPlayer/blob/e4939e85a0d5365aba0f074ad72f20081f1836a3/extensions/cast/src/main/java/com/google/android/exoplayer2/ext/cast/CastPlayer.java).

Transistor's [PlayerService](https://github.com/y20k/transistor/blob/v4.0.13/app/src/main/java/org/y20k/transistor/playback/PlayerService.kt) has some similarities to the UAMP [MusicService](https://github.com/android/uamp/blob/61b8f6aaad08ce04015b2f4d60a7071c51071c0f/common/src/main/java/com/example/android/uamp/media/MusicService.kt).

If I would implement DLNA for Transistor, I would try to build a class like CastPlayer which extends an ExoPlayer BasePlayer, for DLNA. That class can be hooked into Transistor's PlayerService the same way CastPlayer is used in UAMP's MusicService.

Hope that helps. 

> I did some DLNA streaming app a few years back

Oh that is interesting. I have been looking again and again for a good open source alternative to BubbleUPnP. Do you know of any?

**Comment by b-m-f** [comment]
Hi there!

Sorry for taking this long.

I had used https://github.com/4thline/cling to implement it.

As for this issue I switched to using Bluetooth for streaming the music as rewiring myself into Kotlin and Class based programming is a bit too much for me to take on right now.

Sorry to leave you hanging! But you have a big fan in your app with me. Great work  :)

**Comment by y20k** [comment]
No worries & thanks
