### ISSUE TITLE
Add DMR network Radio

### ISSUE THREAD

**Issue by Pantyhose-X** [y20k/transistor#351]
**Describe the solution you'd like**
Add Repeater Radio
1. https://brandmeister.network/
2. http://stats.allstarlink.org/

**Comment by y20k** [comment]
Hi @Pantyhose-X 
I hope I am not being ignorant. What is repeater radio? Can you point me to an article explaining it?
Cheers

**Comment by Pantyhose-X** [comment]
> Hi @Pantyhose-X
> I hope I am not being ignorant. What is repeater radio? Can you point me to an article explaining it?
> Cheers

https://wiki.brandmeister.network/index.php/What_is_BrandMeister
https://www.youtube.com/watch?v=aO8Wrzcfy3s

**Comment by y20k** [comment]
Hi @Pantyhose-X  
I currently do not see me building some kind of support for repeater radio into Transistor. The app is a small hobby project. I cannot spare a lot of time. Its sole purpose is playback of internet radio streams.
