### ISSUE TITLE
Add support for .m3u8 type playlists.

### ISSUE THREAD

**Issue by a-raccoon** [y20k/transistor#36]
Please add support for the .m3u8 playlist format, which open source players have more recently migrated to.

Here are some example station listings using the format.

http://mathewpeet.org/lists/BBC_radio_audio_streams/

Thank you.

**Comment by y20k** [comment]
m3u8 playlist files seem to be very similar to m3u files. Adding support for those should be fairly easy to implement.

Support for m3u8 formatted files can still mean that some of the files in the list you provided will not play. Radio One for example contains a link to:
http://as-hls-uk-live.edgesuite.net/pool_7/live/bbc_radio_one/bbc_radio_one.isml/bbc_radio_one-audio%3d320000.m3u8?dvr_window_length=24

Transistor will refuse to play that specific URL. It contains **.m3u8**. A playlist within a playlist? - Russian doll like. (My VLC has problems with this URL too, btw.) 

Nonetheless. Support for m3u8 in general seems to be a good idea (thank you for suggesting!). I will look into it.

**Comment by meonwax** [comment]
http://as-hls-uk-live.edgesuite.net/pool_7/live/bbc_radio_one/bbc_radio_one.isml/bbc_radio_one-audio%3d320000.m3u8?dvr_window_length=24 seems to be broken in general.

I only receive *HTTP 403 status* with content-type *text/html* and so does VLC.

**Comment by y20k** [comment]
Googleing for m3u8 brought up this site: http://www.addictradio.net/en/labs/ 

Here they have m3u8 playlists that play well in VLC. _Temporarily_ adding `application/vnd.apple.mpegurl; charset=utf-8` to the content types made Transistor start parsing the playlist. 

The resulting URL `http://hls2.addictradio.net/addictalternative_hls/playlist.m3u8?listeningSessionID=55ca2cdc1c6bade2_15567000_QIzTJizc_0000000Yk51&downloadSessionID=0` was not recognized as an audiofile. probably rightly so.

Wgetting this URL brought me another playlistfile containing this very similar URL
`http://hls2.addictradio.net/addictalternative_hls/playlist.m3u8?listeningSessionID=55ca2cdc1c6bade2_15567464_VbHhnzpR_00000004l51&downloadSessionID=0&listeningSessionID=55ca2cdc1c6bade2_15567000_QIzTJizc_0000000Yk51`

Short story: I do not know how to get a streaming URL that MediaPlayer accepts from those files. I suggest closing the issue for now - until m3u8 become more common. What do you think @meonwax?

**Comment by y20k** [comment]
I think I will not strip out the ability to add m3u8 for now. Parsing works in the sense that Transistor grabs the URL inside the m3u8 file. The URL then is checked by the `isAudioFile` method.

Problem is that in the cases that I did test there was no "valid" audio URL inside the m3u8. The app then shows an error. 

But since an error is shown anyway if someone puts in a random URL I think, I can leave check that in.

That is all I can do for now (not much, sorry).

**Comment by meonwax** [comment]
Cannot figure out how these m3u8 files actually work.
Here http://tools.ietf.org/html/draft-pantos-http-live-streaming-02 is the RFC.

I first thought they are simple m3u files with strict utf-8 encoding, but they seem to allow these `#EXT-X-STREAM-INF`-tags for nested playlists, as you already stated earlier.

VLC successfully plays this stream: http://hls1.addictradio.net/addictalternative_hls/playlist.m3u8
But my tests with cURL always returns the an m3u8 URI, even when i query the nested URI.

**Comment by y20k** [comment]
Hey @a-raccoon ,

I just wanted to let you know that there is progress on the m3u8 front. At least on my devices Transistor is able to play back some m3u8 streams that it refused to play before. See Issue #108. 

The addictradio.net stream that @meonwax mentioned still does not work - but some of the BBC streams you mentioned are now working. At #108 there is a Test-APK, if you are interested. 

If there are no mayor problems with the feature, it will be part of the next release.

**Comment by y20k** [comment]
FYI: The next version ([v2.1.6](https://github.com/y20k/transistor/releases/tag/v2.1.6)) features limited HLS/m3u8 support.
