### ISSUE TITLE
Notification drawer/lockscreen buttons don't work

### ISSUE THREAD

**Issue by econo202** [y20k/transistor#363]
- App version: 4.0.15 (F-Droid)
- System version: Android 10

---

Next & Previous buttons that appear in the notification drawer and on the lockscreen, when Transistor is playing, do not work.

Pressing them does not start next or previous stream. Instead it restarts the one that is currently playing.

Play/Stop & close buttons work as expected. 

I guess that it might be connected with this commit: https://github.com/y20k/transistor/commit/b1639f7efe468c6a2dc940468b62a0743a30cdcb

Version 4.0.14 (F-Droid) works as expected.

**Comment by econo202** [comment]
I guess that it might be connected with this commit: https://github.com/y20k/transistor/commit/b1639f7efe468c6a2dc940468b62a0743a30cdcb

**Comment by y20k** [comment]
Hi @econo202 

Thank you for bringing this bug to my attention!! You are right. I introduced the problem, while fixing #362.

**Comment by econo202** [comment]
Thank you for fixing it!
