### ISSUE TITLE
A very long pause before playback starts on VPN

### ISSUE THREAD

**Issue by bungabunga** [y20k/transistor#37]
I love your app for it's simplicity and an open source code!! Bravo! I've waited for this for years.

However,  I have one problem: I always connect to the internet through VPN. And if pressing on playback button when on VPN, I have to wait more then a minute for the playback to start.

It is happening only with Transistor. With "Radio FM" or "TuneIn" there are no such delays. Is there something you could do about it?

Thanks!

**Comment by y20k** [comment]
I thought I already answered this one - but I guess I missed it. Sry.

Transistor uses the basic Android [MediaPlayer](http://developer.android.com/reference/android/media/MediaPlayer.html) library for playback. The app just grabs a streaming URL and hands it to a MediaPlayer object - nothing more. That means that there are not too many points where I can tune the process.

"Radio FM" and "TuneIn" probably do not use the MediaPlayer for their playback. I could consider switching to another open audio library and see if its faster. But that is a lot of work ;-) and (more important) not the safest bet. Staying with the core Android toolkit will make this project more stable. And even if I decide to abandon it, the app will continue to run - at least in theory.

**Comment by y20k** [comment]
Just because I am curious: What kind of VPN are you using (OpenVPN, PPTP, Cisco) and which radio station is so slow to start? I want to try to reproduce the experience.

**Comment by bungabunga** [comment]
thanks for your answer, it seems very reasonable.

i use Bitmask VPN client, which is based on OpenVPN, with security enhancements and the service i use is riseup.net: 
https://play.google.com/store/apps/details?id=se.leap.bitmaskclient

it's the dame with every station i tried: 
1. http://www.radiostudent.si/stream/radio_studentHQ.m3u
2. http://mp3.rtvslo.si/ars

i don't have any other streaming problem with this VPN client/service.

thanks!

**Comment by y20k** [comment]
Okay. Thank you. I will look into it. But as I said: There is probably not too much for me do.

**Comment by y20k** [comment]
I have a VPN subscription with ProXPN. Trying out  http://www.radiostudent.si/stream/radio_studentHQ.m3u via a connection terminating in Miami worked just fine. Just the usual 5 - 10 seconds Transistor also takes without a VPN.

The logcat for Transistor does not show anything unusual. I am sorry, but I cannot help you right now.
