### ISSUE TITLE
Allow stations to be removed.

### ISSUE THREAD

**Issue by benpietras** [y20k/transistor#388]
**Is your feature request related to a problem? Please describe.**
Description of what the problem is. Example: I'm always frustrated when [...]

**Describe the solution you'd like**
Description of what you want to happen.

**Describe alternatives you've considered**
Description of any alternative solutions or features you've considered, if so.

**Additional context**

**Comment by y20k** [comment]
Hi @benpietras 
Does swipe to delete work for you?

**Comment by benpietras** [comment]
It does, yes.

Thanks! (I did google and read the wiki before I posted).

6 Jan 2022 22:44:59 y20k ***@***.***>:
