### ISSUE TITLE
Add "Edit station" to context menu along with new edit dialog

### ISSUE THREAD

**Issue by KaktusXY** [y20k/transistor#389]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when the station link occasionally changes and I have to remove the old station and add a new one.

**Describe the solution you'd like**
I created a sketch of how it could look (attached images).

Thanks for looking into it 😄 

![1](https://user-images.githubusercontent.com/58702689/149967042-32a3286d-72bb-4ea5-a907-972a7183778d.png)
![2](https://user-images.githubusercontent.com/58702689/149967046-64352273-b7df-4b0a-9c0e-a0c893e25960.png)

**Comment by Neppo-muk** [comment]
This looks great.
As a solution for the check, you could let the user listen to the link with a check button. The user can verify the link and check the quality.

**Comment by KaktusXY** [comment]
Looks awesome!

**Comment by hoshsadiq** [comment]
@y20k the edit streaming url doesn't seem to work. When I change the URL, the save changes button becomes disabled, when I undo the changes, it becomes enabled again.

**Comment by y20k** [comment]
@hoshsadiq Transistor performs a check in background to make sure that the new address is a streaming link - and not a m3u/pls playlist or the address of the radio stations website.

**Comment by hoshsadiq** [comment]
Would it make sense to let users do what they want (maybe a "I know what I'm doing checkbox")? If they really want to add a broken link that can't be played, it's up to them.

Of course if it turns out it's an easy fix, then keeping those checks makes sense.

**Comment by hoshsadiq** [comment]
@y20k by the way, I can open a new issue to track that if you like considering this issue is technically finished, so I don't want to further muddy this issue.

**Comment by y20k** [comment]
@hoshsadiq 

Yes. A new issue would be a good idea. The only thing might be: I am currently super-busy in my day job. I guess it might take some time until I come around to changing/improving the edit feature.
