### ISSUE TITLE
Random floating app icon on startup.

### ISSUE THREAD

**Issue by MintMain21** [y20k/transistor#391]
**Describe the bug**

After updating to the latest release through Fdroid, I find now that when loading the app, a random image of the app's icon appears on screen in front of the list of radio stations before dissapearing. I can only presume this is supposed to be part of some kind of splash screen, but the background dissapears too soon and the icon appears too late, so the effect looks awkward as a result.

**To Reproduce**
1. Upgrade to the latest release (4.0.18)
2. Launch the App.
3. Background will appear, then the list of stations will apear, and the rouge icon along with it.
4. Icon will abrubtly dissapear. As stated before, it feels like a splash screen that appears too late and awkwardly dissapears.

**Expected behavior**
Either a proper splash screen, or a logo-less transition from the app launcher to the app.

**Screenshots**
![Screenshot_20220122-015321.png](https://user-images.githubusercontent.com/91362684/150633822-e16b3b38-fa6c-4392-9a56-b7028100063a.png) ![Screenshot_20220122-015356.png](https://user-images.githubusercontent.com/91362684/150633828-69c50066-c792-440a-8f59-64ed2558b340.png)
![Screenshot_20220122-015647.png](https://user-images.githubusercontent.com/91362684/150633885-40b19a29-7f8c-4b2c-8a35-1e087d6bc8ca.png)

**Device:**
 - Device: LG Stylo 5
 - OS: Android 10
 - Transistor Version 4.0.18 

**Additional context**

This may be exclusive to the Fdroid release, and as a result absent from the APK on Github.

**Comment by y20k** [comment]
I noticed the issue too. I have an idea how I can fix that.
