### ISSUE TITLE
Response after copying Artist and Title Info 

### ISSUE THREAD

**Issue by Bullenwaechter** [y20k/transistor#397]
Thanks for this great little player! 

When copying Artist and Title data from a running stream into the clipboard (Zwischenablage) there is no response if the transaction was successful. Motsly Transistor does it right, but aconsiderable number of times not. Only after pasting the clipboards content into a document, I faced that actual data was not copied and an older content of the clipboard was active.

A little response after successful copying of the info would be great! Such as a short message like “copied” or a graphic response of the action.

**Comment by y20k** [comment]
Hi @Bullenwaechter 

Transistor should already indicate with a small toast message that text was copied to the clipboard.

![toast](https://user-images.githubusercontent.com/9103935/152047027-b3d2d6ea-0b9d-4ed3-823e-46ef5cf3382b.png)

**Comment by ShadyGaDa** [comment]
Yeah but how about copy all songs played in one go, maybe hundreds?!

**Comment by Bullenwaechter** [comment]
Hi
Thanks for your reply. I have installed Version 4.0.18 Andy Warhol (on Android 9 ), but I didn't get a response after copying. There is no popup note as shown in your screenshot. But copy process worked. 

Do you have an idea for this phenomen?

**Comment by Bullenwaechter** [comment]
I think I found the reason for my missing toast message:
In the smartphones   Android  -->  Settings  --> Apps & Notificatins  --> Transistor  -->  Notifications    the option "Shwo notifications" were deactivated.  After activations it works. But in my shone there is only a simple message without the graphic Trnsistor icon. But I get the wanted respose.

Thanks!
