### ISSUE TITLE
Cutting out throughout radio streams

### ISSUE THREAD

**Issue by Sanphobia** [y20k/transistor#402]
**Describe the bug**

Audio intermittently dropping out on stations, good connection speed (fibre 15mb/s wifi, or mobile data on 4g)

**To Reproduce**

1. stream radio station (all stations I have tested,
> http://deephouseradio.radioca.st:8589/deep
> http://91.121.236.34:8520/nz
> https://web-radio.co.uk/stream/8006
> https://radio123-gecko.radioca.st/radioactivefm
3. every so often stream cuts out and comes back again multiple times. (My phone's normally locked and screen turned off after I start streaming.)

**Expected behavior**
continuous streaming, no cut-outs.

**Screenshots**
If applicable, add screenshots to help explain.

**Device:**
 - Device: **Undisclosed**
 - OS: **[Android 9]**
 - Version [app version **4.1.0**]

**Additional context**

I've got a decent connection and relatively modern phone, its a flagship from mid 2017. 
The cutting out I believe does stop being so frequent, after a while, but its not pleasant starting off.

**Comment by Sanphobia** [comment]
Please note: I posted this as an independent issue from the others as I:

1. have a good connection
2. Use an OEM version of android

Apologies if I didn't see there was another issue posted earlier, that would be relevant to my case.

**Comment by Sanphobia** [comment]
Hi there, Thanks for the tip. It looks to be a certain problem with my manufacturers' settings (particularly bad), but it appears to be the same problem as others are describing. Thank you for your quick reply, and good luck with your development. Also, thanks for making this available on F-Droid too!

**Comment by Sanphobia** [comment]
One thing I should note, Newpipe seems to work just fine. without intervention. I don't know why that is, but there might be something to look into.

**Comment by JonnyTech** [comment]
> every so often stream cuts out and comes back again multiple times. (My phone's normally locked and screen turned off after I start streaming.)

Do you lock your device and turn the screen off with NewPipe too??

**Comment by Sanphobia** [comment]
> > every so often stream cuts out and comes back again multiple times. (My phone's normally locked and screen turned off after I start streaming.)
> 
> Do you lock your device and turn the screen off with NewPipe too??

Hi, yes. The only cut-out I get is with the app changing from video to background modes. and there is no cutout when the phone is locked.

**Comment by Sanphobia** [comment]
nor when the screen is turned off. On the same device, with no touching the battery optimisation settings.
