### ISSUE TITLE
Legacy Locale

### ISSUE THREAD

**Issue by the7thNightmare** [y20k/transistor#406]
**Describe the bug**
Indonesian language have two language codes (in and id), `in` is the old ones, in [this](https://stackoverflow.com/questions/44245959/android-generating-wrong-language-code-for-indonesia) and [this](https://developer.android.com/reference/java/util/Locale.html#Locale(java.lang.String)
) says that `in` is the one that is used in some older Android version (my phone is running Android 8 and still catch only the `in` ones, not the `id`).

**To Reproduce**
1. Change the phone locale to Indonesian Language
2. Open Transistor

**Expected behavior**
The locale in Transistor is changed to Indonesian

**Screenshots**
If applicable, add screenshots to help explain.

**Device:**
 - Device: not needed
 - OS: Android 8
 - Version: 4.1.0

**Additional context**
There is a string named values-in already (though it seems that is too old (2 years ago))

**Comment by y20k** [comment]
Hi @the7thNightmare 

Do you know where I can change the target file for a language in in Weblate?

**Comment by the7thNightmare** [comment]
I didn't really know how to do that, but one [discussion](https://github.com/WeblateOrg/weblate/discussions/7386#discussioncomment-237319) might help. The solution will be copy-paste the xml under strings-id to strings-in (which override the old xml) and delete the strings-id folder.

Also, I notice that @comradekingu is one of the project maintainer in Weblate, maybe you can help?

**Comment by comradekingu** [comment]
I am a Transistor admin at Hosted Weblate.
I think `id` is the better choice (but I could be wrong).
At least as far back as Android 10 (LineageOS 17.1) selecting Indonesia (Indonesia) works for
Transistor 4.1.0, which uses `id`.

Transistor 4.1.0 requires Android 7.1+, so we know at least users of 7.1 - 8 (any maybe 9) will benefit from populating "in".

@the7thNightmare 
I think a better solution is to copy the `id` XML to in XML, without deleting the `id`.

This will make Weblate complain that there are duplicate locales, but that shouldn't matter.
Android will ideally use id and then in as a fallback. In any event it doesn't matter so long as the two stringbases don't diverge.

Diverging string-bases is a problem for a later day, and a straight copy without further thought at least gives lots of users a great option. Then `in` can be deleted altogether once the requirements of Transistor exceeds that of support for `id`.
