### ISSUE TITLE
Is it possible to add a chromcast button?

### ISSUE THREAD

**Issue by Citypet** [y20k/transistor#409]
Is it possible to add a chromcast button, so that I can steam the radio station to a suitable speaker.

This button is also in e.g. Tunein and Radio Box.

Then it is possible to send the steam to a suitable speaker, such as the Google Mini, Sonos, JBL etc.

![proxy-image](https://user-images.githubusercontent.com/103965233/164312606-4d1bf142-5cab-4379-a69b-fdedc08b4f6a.png)

**Comment by y20k** [comment]
Hi @Citypet thanks for sharing your idea / wish. Actually this feature has been requested befor (see #115 and #48). See my comment there for the reason, why there is currently no plan to implement this feature.
