### ISSUE TITLE
m3u URL not working

### ISSUE THREAD

**Issue by ksbckr** [y20k/transistor#41]
Hey, first things first. Great app, really like the material interface. I was trying to add the following stream: http://www.sputnik.de/m3u/live.hi.m3u 
but the app keeps prompting that it can't find a stream. Opening the url in VLC works without any problems.

**Comment by y20k** [comment]
Hi there, 
thank you for your bug report!! Transistor reads m3u files line by line. The m3u you mentioned seems lack a new line character at the end. Transistor refuses to read the last line, which is the line that contains the actual raw streaming URL.

As a quick workaround just add the raw stream.
http://c22033-ls.i.core.cdn.streamfarm.net/UjIe753Ui9922033/22033mdr/live/app2128740352/w2128904195/live_de_128.mp3

I will look into the issue. Maybe there is an easy fix for this.

**Comment by ksbckr** [comment]
Ah ok, perfect. I was just building the project to give you some more input. Logcat wasn't quite helpful at first.

**Comment by y20k** [comment]
Hi there, 
if you are into JAVA... I am utilizing a simple Scanner to scan through the file line by line. If you have an suggestions how to make the scanner to read the last line even if there is no next-line character, please let my know.
Best wishes


```
// prepare scanner
Scanner in = new Scanner(fileContent);
String line;
while (in.hasNextLine()) {
    // get a line from file content
    line = in.nextLine();
    /* parsing "line"... */
}
```

**Comment by ksbckr** [comment]
Ok, so I thing I got the problem. It's not even getting to the parse part. Thing is, the matching of the content type fails:
Log says: `Content type is audio/x-mpegurl; charset=utf-8` 
while content type for m3u is defined as
`private static final String[] CONTENT_TYPES_M3U = {"audio/x-mpegurl"};`

So the following matching fails:
    /* Determines if given content type is a playlist */
    private boolean isPlaylist(String contentType) {
        for (String[] array : new String[][]{CONTENT_TYPES_PLS, CONTENT_TYPES_M3U}) {
            if (Arrays.asList(array).contains(contentType)) {
                return true;
            }
        }
        return false;
    }

Adding the charset works for my example. Gonna try something else later.

**Comment by y20k** [comment]
Hi there, 

I need to look into that. I did "solve" the problem by just adding a new line to
http://www.sputnik.de/m3u/live.hi.m3u
And then I put "live.hi.m3u" into the folder /Android/data/org.y20k.transistor/Collection
That did the trick. No parsing error. That lead me to the whole thing about the `Scanner`

PS. @meonwax: Do you think there is anything wrong with `isPlaylist(String contentType)` ?

**Comment by y20k** [comment]
@ksbckr: You were on the right track! Just adding the mime type you suggested solved the problem. I was totally on the wrong track with the whole Scanner thing. I will add mime-type to next release. Thank you!
