### ISSUE TITLE
Sleep timer button in Playback screen

### ISSUE THREAD

**Issue by y20k** [y20k/transistor#43]
(Note to my future self:) I got this suggestion via mail. I think adding a sleep button in the playback screen (ActionBar) seems to be a nice feature that does not add clutter or complexity. Not a feature for the next release but definitely worth considering.

**Comment by byteborg** [comment]
<3

**Comment by y20k** [comment]
The Sleep Timer should work like this: [Sleep Timer](https://github.com/y20k/transistor/wiki/Sleep-Timer) (Wiki)

**Comment by byteborg** [comment]
How about a simpler interaction: pushing the timer button toggles sleep timer on/off; long press opens dialog for duration. Default when toggled on is last selected duration.

**Comment by byteborg** [comment]
A great option for displaying timer state would be the status icon. So the visibility would be given without coupling to certain screens/dialogs and when the app is in background.

**Comment by byteborg** [comment]
Also the behaviour of killing the running timer when switching stations would be counter-intuitive, I think. When listening to a station with programming I suddenly don't want anymore, I'd just want to zap to a different station, without thinking too much about the timer...

**Comment by y20k** [comment]
FYI. The prototype of the sleep timer looks like this. The timer is tied to a station. It is not an app-wide timer. I thought about both possibilities and I think it is intuitive. But the whole thing is still work in progress and thus subject to change.

![2016-03-06 12 50 52](https://cloud.githubusercontent.com/assets/9103935/13554227/ae1ca040-e3a2-11e5-9104-2d131f20e8e1.png)
![2016-03-06 12 51 21](https://cloud.githubusercontent.com/assets/9103935/13554228/ae20e038-e3a2-11e5-9432-a414e5931975.png)

**Comment by y20k** [comment]
Thinking about it a bit more. You are probably right. The sleep timer should be attached to the App - not to a station. 

In that case the sleep timer icon should be on the list view. 

Then only concern then would be: How to respond to a tap on the icon when no station is playing. I tend to show a short notification that the sleep timer only could be turned on when a station is playing.

To cancel the timer you would still press cancel or press the stop button or dismiss the notification. Tapping repeatedly on the icon would increase the duration.

So the timer still would be very simple. It would just be attached to app instead of a station.

**Comment by y20k** [comment]
mission more or less accomplished in [v2.0.0](https://github.com/y20k/transistor/releases/tag/v2.0.0) - time to close this one

**Comment by byteborg** [comment]
You, sir, are my hero.

**Comment by y20k** [comment]
:+1:
