### ISSUE TITLE
Wrong entry is marked as playing when order changes

### ISSUE THREAD

**Issue by meonwax** [y20k/transistor#44]
I spotted a little bug:
When playing a stream and then renaming a station entry, so that the order of station changes, the wrong entry is marked as *playing*.

Steps to reproduce:
* Create a station and rename to *ABC*
* Create a station and rename to *DEF*
* Start playing Station *ABC*
* While playing, rename Station *DEF* to *AAA*

Then the wrong station is marked as *playing*.

**Comment by y20k** [comment]
I have an explanation why that happens (you probably too):

After a renaming action Transistor reloads the playlist. That reload has three parts:

1. A sorted list is being refilled with the stations found on storage
2. The number of the currently playing station is being fetched from Android `SharedPreferences`
3. Transistor marks the station in the list with the number from 2. as playing.

After step 1. the station has a different number than before the renaming. That change was not reflected in the `SharedPreferences`.

So much for the explanation. I guess this is a case where not using a database backfires, right? I do not have an obvious solution at hand for this. 

Maybe something along the lines of: After renaming the new index should be reported back and saved somehow.

I need to check that. Thank you for reporting!!!

**Comment by y20k** [comment]
I think it works now as intended.
