### ISSUE TITLE
Manual sorting of station entries

### ISSUE THREAD

**Issue by meonwax** [y20k/transistor#45]
Feature request:

Allow manual sorting of station entries.
This could possibly be done when longtapping and dragging the icon.
Every filename could be prepended with an index number on the filesystem to easily sort them when populating the list.

**Comment by y20k** [comment]
I need to think about this. 

My first reaction would be to reject the idea. In my opinion an alphabetic order is just fine and easy to understand. Every new feature comes at a cost.

But I must admit that my opinion is clouded by thought about the complexity that this feature would introduce under the hood. Right now the source code is pretty straight forward and easy to understand. That helps a lot with debugging. I would like to keep it simple.

But that aside. UI-wise: 
How would you handle the addition of a new station. On top, in alphabetical order? 
What if someone wants to go back to automatic sorting (without adding a settings page)?

**Comment by meonwax** [comment]
I came across this enhancement because i have quite a long list of stations.
To organize them, it would be nice to be able to change the order.
For example, i have several streams from *soma.fm* and *sport1.fm* in my list. I want them to appear based on my own liking.

> How would you handle the addition of a new station

A new Station could just be inserted at the end of the list. When we will use the suggested number-prefix naming scheme, we could easily add them at the end.
Of course we have to deal with manually created m3u-files in the app-directory by the user.

> What if someone wants to go back to automatic sorting

If you don't want to have settings, what about adding just two buttons in the action bar?
*sort-by-name* and *sort-by-manual-order*

Ok, as this is a feature request implicating the addition of code, this will add some small but manageable complexity.

**Comment by y20k** [comment]
I am still not convinced. 

When a user sees a list of names and icons, he/she implies that the list is sorted somehow. Alphabetical sorting is the most common sorting that is understood - without having to add an information somewhere what the criteria is.

Adding manual sort order is a power user feature, which is not easily understood. PocketCasts has it for example. Normal music players on the other hand often have lists of mp3 albums - always in alphabetical order. They solve the need to customize by adding playlists. I think that is too not an option.

Maybe "starring" a station would be a feature the app could go with. In this case there is still a UI problem. I guess the option menu could vanish in favor of a star symbol. Not sure that that would be a net win.

**Comment by meonwax** [comment]
> Alphabetical sorting is the most common sorting that is understood

Yes, that is true, but only for prepopulated lists. As this application comes with **zero** station entries, the user immediately understoods, that adding a new station just appends it at the end of the list.

The current sorting order doesn't necessarily need to be always indicated. If we have the two modes *alphabetically* and *custom*, it's only one fingertip to switch between them. Just add two buttons (or only one trigger) to the action bar.

Alternatively, we could only add one explicit *sort*-button that always rearranges a potential custom ordering into an alphabetical order.

I still think that custom sorting for a large list of radio stations is a must.

I have to implement quite the same feature for an other Android project. Perhaps i could implement it there and then we could discuss again of merging it into this project.

**Comment by y20k** [comment]
> I have to implement quite the same feature for an other Android project. Perhaps i could implement it there and then we could discuss again of merging it into this project.

That seems to be a reasonable suggestion! Do not feel discouraged by me arguing about this. I am interested how such a solution would look like. But I do not want people to work on stuff that I will possibly reject. Feel free to drop me a link to the project you mentioned so that I can check it out.

**Comment by meonwax** [comment]
> Do not feel discouraged by me arguing about this. I am interested how such a solution would look like. But I do not want people to work on stuff that I will possibly reject.

That's the reason we discuss it before ;)
No problem, your are the owner here.

I will provide a link as soon as i have implemented my solution.
