### ISSUE TITLE
load playlis files

### ISSUE THREAD

**Issue by irregularisnotrandom** [y20k/transistor#49]
Hi

It would be great if one could load playlist files as a file.

**Comment by y20k** [comment]
Thank you. I think that is a good idea. 

Right now there is only on [+] button and one input field. I would like to keep that. 

BUT: Transistor could be one of the Apps that appear when you try to open a file within a file explorer. I will look into that. Should be just a few additions to the [AndroidManifest.xml](https://github.com/y20k/transistor/blob/master/app/src/main/AndroidManifest.xml)

**Comment by irregularisnotrandom** [comment]
It does not ahow up in the list.

**Comment by y20k** [comment]
I know :-) - not yet. I will look into that.

**Comment by y20k** [comment]
Added the feature. Works fine for now. It will part of the next release. Thanks again for the suggestion.
