### ISSUE TITLE
show url

### ISSUE THREAD

**Issue by irregularisnotrandom** [y20k/transistor#50]
HI

It is impossible to see or edit the url once it is added. I thimk that it would be nice if one could at least copy the url to use in other apps.

**Comment by y20k** [comment]
Hi. Thanks for the suggestion! I see two issues here:

### 1. Editing the URL of a station.
The intended procedure for that would be: Just add the new URL via the [+] button and delete the old station. I do not see the need to add another way to archive that. Remember: one of the goals of this app is to stay simple and straight forward.

### 2. Getting the URL for use in another app
That is a power user feature. That does not mean it should not be implemented. I could imagine that a tap on the station name would copy the URL to the clipboard accompanied by a short message that is was copied.

I need to think about that.

**Comment by irregularisnotrandom** [comment]
When the radionlisten the app, it is not possible to see wwhere the strezm is coming from, let aline editing it

**Comment by irregularisnotrandom** [comment]
Sorry for the typos, editing does not work in my mobile browser. Basically when i play an item in the aapp i do not know wherenthe stream is ccoming from

**Comment by y20k** [comment]
If I under stood you correctly: Your want to see that stream URL. So I guess copying it to the clipboard with a small message that the URL http://xyz was copied would suffice, right?

**Comment by irregularisnotrandom** [comment]
Yeah sounds good. 

Here is a scenario where it can be helpful. listen some urls from online links, then try to copy the ones you like to your notepad app. It is not possible now.

**Comment by y20k** [comment]
Okay. I did add a "copy station" feature.  It should be part of the next release. That was just a few lines of code. Since this is something I would consider a power-user feature. I am not going to advertise it in release notes. There is also no hint in the UI on purpose.
You will need to tap on the station name in the player view (the one with the big play button).
