### ISSUE TITLE
Shoutcast and Xiph search

### ISSUE THREAD

**Issue by irregularisnotrandom** [y20k/transistor#51]
Hi

It will be great if we can search those online stations and add to the playlust and stream from.

**Comment by y20k** [comment]
Thank you for your suggestion. 

I did think about adding this feature way back when I developing the idea for Transistor. I did decide against that. 

I wanted very simple and independent app. That is why Transistor does only utilize the basic Android libraries - no external ones. And that is why there is no dependency on a third party web service. 

That makes Transistor more resilient and easier to maintain in the long run. I know that this also makes Transistor less convenient to use. But I think the market for radio apps is big enough for apps with different feature sets. There are a lot of apps out there that integrate Shoutcast.

**Comment by irregularisnotrandom** [comment]
actually there are not any open source app that integrates shoutcast as far as i know. All the apps on the app store spies on the users.
