### ISSUE TITLE
additive playlist (recently played stations)

### ISSUE THREAD

**Issue by irregularisnotrandom** [y20k/transistor#52]
Hi

It would be great if the app keeps the previously listened stations, the ones coming from other apps.

Open your browser. open shoutcast site, find a channel. Click in m3u to listened in the app. Stream a abit, stop it. Open shoutcast page again and stream another link. there is only one link in the app. You loose the previous link in this scenario.

**Comment by y20k** [comment]
Are you serious? ;-) The app should only store one link at a time? For this usecase you would not need my app at all. Just open the stream from the browser within the brower or within a mediaplayer app like vlc.

**Comment by irregularisnotrandom** [comment]
not sure if i articulated my message well. What j was saying that this app does not ztore the previously played radio stations. It would be nnice if there is a way to see the station history.

**Comment by y20k** [comment]
Ah, okay. I get it. That is indeed an interesting feature. The list of stations is sorted alphabetically right now. 

I see a problem here conceptually. The app's **main goal is to be simple and straight forward**. Any new feature must be carefully considered

Adding the ability to sort or the ability to create playlists would introduce a "complexity" that I do not like. There is another feature request here that suggested manual ordering (#45), which I am also reluctant to add.

My UI worries ("complexity") set aside for a second. This would also introduce the need to use a database to store the station history. Also something I do not want.

So, sorry to disappoint you. No "recently played stations" - at least for now
