### ISSUE TITLE
Translations: Chinese ~~and Spanish~~ anyone?

### ISSUE THREAD

**Issue by y20k** [y20k/transistor#54]
If there is anyone out there speaking Chinese ~~or Spanish~~, translations in those two languages would be the bomb! I think that could broaden the appeal of Transistor a lot. Since I do not see a feature in [Weblate](https://hosted.weblate.org/projects/transistor/strings/) to articulate that, I chose to open an issue here.

**Comment by franciscot** [comment]
I can translate to spanish. Where and how?

**Comment by y20k** [comment]
Wow. That would be great. The strings used in Transistor are also hosted on [Weblate](https://hosted.weblate.org/projects/transistor/strings/). Just head over there and start a translation. Any changes and additions will pushed automatically back to GitHub. The process is pretty straight forward.

**Comment by franciscot** [comment]
Spanish is done. I need some information in some strings to complete.

**Comment by y20k** [comment]
Hi franciscot, 

> need some information in some strings to complete.
how can I help you? What exactly do you want do know? 

Best wishes, have a nice weekend

**Comment by franciscot** [comment]
Thanks. 
Now it is finished.

**Comment by y20k** [comment]
Hi there. 

Thank you very much! Spanish is a very important language. I really appreciate your work. I put you / your GitHub handle on the translators list in [AUTHORS.md](https://github.com/y20k/transistor/blob/master/AUTHORS.md). The only way to get some kind of credit for your work right now.

The next release is probably due next weekend - depending on the amount of bugs in the rest of the code I find until then. Spanish will be the headline new "feature".

Best wishes.

**Comment by y20k** [comment]
I will close this issue for now. Maybe I will put up a separate request for Chinese in the future here or on some other channel. Great that we now have Spanish in any case!!!

**Comment by franciscot** [comment]
It's nice in Spanish now ;)
Let me know if you need more help in the future.

**Comment by y20k** [comment]
:+1:
