### ISSUE TITLE
Some links are not recognized

### ISSUE THREAD

**Issue by pelya** [y20k/transistor#56]
When opening .m3u link in a web browser from http://www.slayradio.org/ Transistor is not in the 'Open with' list. It also won't open the link if I copy-paste it into the app manually.

Full link: http://www.slayradio.org/tune_in.php/128kbps/slayradio.128.m3u

VLC opens and plays it fine. The server probably sends incorrect HTTP mime-type.

**Comment by y20k** [comment]
You were on the right track: The server sends a valid mime type (`audio/mpegurl`) that is not yet in the list of mime types that transistor checks for. I will add that in the next release. For now the only solution is to add the raw streaming URL that was in the m3u you posted:

http://relay1.slayradio.org:8000/

Thanks.
