### ISSUE TITLE
Resume play on audio jack plug-in 

### ISSUE THREAD

**Issue by meonwax** [y20k/transistor#59]
A feature request:

If i plug out my headphone, the playing stops.
This is fine (did you implemented it or is this the default behavior?).

It would be nice, if the playing of the same station just continues when i plug it in again. :headphones:

**Comment by y20k** [comment]
Thank you for that suggestion! 

Adding this feature might be handy. But I think most music player behave differently. 

I have nothing against "Think Different". I implemented a few non-standard behaviors for Transistor. "Swipe to stop" and "Longpress to play" for example.

But I need to think this through. I users could get possibly annoyed, it is maybe not worth the trade-off (see: "Swipe to stop" and "Dismiss all notifications ;-) )

**Comment by meonwax** [comment]
Many applications provide a settings option for 'resume on on audio jack plug-in'. I personally always check this :)
But since you do not want settings, you have to decide for a default behavior.

**Comment by y20k** [comment]
You are right. This would be a feature that I can add if Transistor has a Settings screen. I will keep this in mind. I will add this issue to the "Previous discussions and feature requests (#48)".

**Comment by epitron** [comment]
Shouldn't this issue's tag be, "mightfix"? :)
