### ISSUE TITLE
Bare bones tablet support

### ISSUE THREAD

**Issue by y20k** [y20k/transistor#60]
I somehow have the feeling that Google is not yet ready to give up tablets. My bet is that next I/O they will introduce better tablet support. Transistor should get a decent two-pane layout for bigger resolutions.

**Comment by y20k** [comment]
I started working on this. See: [Tablet Mode](https://github.com/y20k/transistor/wiki/Tablet-Mode) (Wiki)

**Comment by meonwax** [comment]
Wow! nice!

**Comment by y20k** [comment]
It will probably look like this (I really need to buy myself a tablet :-) )

![screenshot from 2016-03-21 21-48-22](https://cloud.githubusercontent.com/assets/9103935/13933731/fca7d1a4-efae-11e5-9872-46fe88eb9ba5.png)

**Comment by y20k** [comment]
mission more or less accomplished in [v2.0.0](https://github.com/y20k/transistor/releases/tag/v2.0.0) - time to close this one
