### ISSUE TITLE
can't add channels on Android 6

### ISSUE THREAD

**Issue by monkeyslut** [y20k/transistor#61]
I recently upgraded to Android 6 (omnirom), and ever since, I can't add stations. Transistor gives the "tried hard, but can't make sense" error message. These are links that I had in Transistor on Android 5, and I've tried .mp3 and .ogg versions. No go.
Ideas? How should I proceed to trace the bug?

**Comment by y20k** [comment]
Hi there, 

Thanks for reporting. Transistor stores its files in /Android/data/org.y20k.transistor/Collection. That is a directory it does not need to have special permissions to access. That is bahaviour that was introduces in [Android 4.4.](http://developer.android.com/about/versions/android-4.4.html#Behaviors).

Android 6 introduces a new permission system. For accessing anything else than the aforementioned directory Transistor should ask for permissions. E.g. when you change the station icon. I am running Android 6, too. Transistor still works even if I retract the "Storage" permission.

There are now a few things you could do (in that order, if possible):
1. Copy the complete the content of the error message (including the "Details") and paste it here (screenshot?)
2. Delete /Android/data/org.y20k.transistor/Collection and try again to add a station
3. Manually give Transistor a the storage Permission and try again to add a station

**Comment by monkeyslut** [comment]
Thanks for your quic answer!
It seems my ROM doesn't support the /emulated/0 path system, they've moved to /sdcard/ path instead. Transistor wants to use /emulated/0/Android/data/ directories, but those aren't mounted on my Omnirom system.
Quite annoying. I'm guessing that's where the issue is.
I'll post a screenshot later when I'm on my laptop. I tried the other things you suggested, but no change.
Strangely enough, the directories do get created whrn I try to add a station, and the Collection dir gets a .nomedia file.

**Comment by monkeyslut** [comment]
Ah crap. I successfully added another channel, ABC news gets added. So the problem is somewhere with the swedish radio lists, located here: http://sverigesradio.se/sida/gruppsida.aspx?programid=3756&grupp=10632
Now, what puzzles me is that transistor on android 5.1 could access these stations. Not sure what changed.

**Comment by y20k** [comment]
Hi there,

I tested the following station and I got an error too (yay!): http://sverigesradio.se/topsy/direkt/132-hi-mp3.m3u

Problem is that the mime type is not supported by the method that handles it (`audio/x-mpegurl; charset=iso-8859-1`) I will add it to the list of supported mime types. 

@meonwax: Right now the method checks if the given string matches one of the supported strings. `if (Arrays.asList(array).contains(contentType))` . Maybe we could introduce a `startsWith` so that we do not need to support all those charsets individually. What do you think?

Strange thing is: Adding those stations seemed to have worked before for you (@monkeyslut) before. Maybe you did not add stations for a while. The mime type check was not part of Transistor in the early days.

Best regards

**Comment by y20k** [comment]
Just one hint: Until the next release you can add the raw audio streams embedded within those m3us. For example: Sveriges Radio - http://http-live.sr.se/p1-mp3-192

**Comment by monkeyslut** [comment]
Yay! Thanks! But nah, I haven't been using the app for that long - just 6 months or so. I don't remember exactly, but I think I can check, if you want me to.

**Comment by y20k** [comment]
The mime type check is pretty new. It was added three weeks ago in [version 1.2.0](https://github.com/y20k/transistor/releases/tag/v1.2.0). Thats why you did not experience any problems with Android 5.1 I guess.

**Comment by meonwax** [comment]
> Right now the method checks if the given string matches one of the supported strings. if (Arrays.asList(array).contains(contentType)) . Maybe we could introduce a startsWith so that we do not need to support all those charsets individually. What do you think?

Yes, that would solve the issue, but i think neither `array.contains()` which actually resolves to `String.equals()` here nor `startsWith()` is smart enough to deal with all potential combinations of mime-type strings, charsets and whatever.

Perhaps a smart regex would fit better?

**Comment by y20k** [comment]
I am not familiar with `List.contains(Object o)` ([Java Documentation](http://docs.oracle.com/javase/7/docs/api/java/util/List.html#contains%28java.lang.Object%29)))

(Thinking aloud:) Since the original Array is an Array if Strings the List also is a List of Strings. `Object o` in this case would be a String too. 

At which position would you suggest to add a regex? 

Can I delegate this issue to you (if you have the time for that)?

**Comment by meonwax** [comment]
I can have a look into that, but since i currently have very little time, it will have to wait until next week.
If that is ok for you...

**Comment by y20k** [comment]
Same here. Very little time :-) There is NO pressure at all. We will ship it when it's ready. 

I am working on an easy to use sleep timer. Turns out: Not that easy to implement, when short on time. But as with the mime type check, no pressure on the sleep timer development right now. Transistor is more or less quite stable as it is.

**Comment by meonwax** [comment]
Ok. Than you can assign it to me.

**Comment by glitchphan** [comment]
Wanted to note that I had this issue with the two stations I wanted this app for. One is pulsradio.com, the link to the playlist is at the top under the Winamp and iTunes icons. The whole playlist gave me the error, and the first URL inside of it that I copy/pasted out gave the error, but then the second one I manually copy/pasted out worked. Same experience with the other station.

**Comment by y20k** [comment]
Hi there. Thanks for reporting this issue. I looked at the [m3u-file](https://www.pulsradio.com/pls/puls-adsl.m3u) in question. Transistors Log says: `Content type of given file is null`. Transistor only downloads files of a certain mime type. Those mime types have to be set by the hosting server.

I think we will be able to fix the problem that @monkeyslut reported earlier. But if the server answers with a `null` mime type... I guess that would be a problem.

**Comment by y20k** [comment]
While I was looking at issue here, I had an idea for the charset problem. @meonwax: We could just cut the contentType String cut after the fist `;`

`contentType = contentType.substring(0, contentType.indexOf(";"));`

**Comment by meonwax** [comment]
Yes that could be fine.
As i stated earlier, i think about applying a regular expression that captures the effective content-type and charset in separate capture groups and assigns them to variables.
Than we could check the *cleaned* and *trimmed* content-type string against a whitelist and we also have the option to take the content type in account. That could be important for exotic non-UTF-8 streams.

Empty content-type header is a problem though, so we don't know if it is a valid audio stream, a  playlist file or complete rubbish.
We could check the first bytes that we receive to guess the content type by [magic byte signatures](https://en.wikipedia.org/wiki/List_of_file_signatures) or similar.
Perhaps there is a nice library that can do that for us.

**Comment by y20k** [comment]
Okay. Then I will leave the `contentType = contentType.substring(0, contentType.indexOf(";")); ` in for now. I does not hurt and the method does its job a bit better then before. I like you solution better, we should switch to it, when ready. But no hurry.

> Empty content-type header is a problem though

I agree. I propose to wait if there are a more complaints. It is mainly the server's fault (although the user does not care who's fault it is) - so you cannot call it a bug of transistor.

I was thinking of making the error handling a bit more transparent. It would be nice if one could see the mime type in the error message.

**Comment by monkeyslut** [comment]
I think it might be possible to talk to the people at the server, they're usually fairly communicative. How should I describe the error? I'm not that well versed in codexes & standards & stuff...

**Comment by meonwax** [comment]
I implemented the RegEx thingy: #64

**Comment by meonwax** [comment]
I identified another issue:

The reason, why we receive a content-type of `null` from [this URL](https://www.pulsradio.com/pls/puls-adsl.m3u) is, because the server certificate isn't accepted as by the Android system. Perhaps the root-CA is not trusted in the Android trust store.

On my linux box, the `curl` utility also complains about this HTTPS-URL.

However, in *chromium*, the certificate seems valid.

**Comment by y20k** [comment]
I don't know a lot about webserver certs. On [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=pulsradio.com) test Pulsradio does not score well.

> The reason, why we receive a content-type of null from this URL is, because the server certificate isn't accepted as by the Android system. Perhaps the root-CA is not trusted in the Android trust store.
> On my linux box, the curl utility also complains about this HTTPS-URL.
> However, in chromium, the certificate seems valid. 

@meonwax: Oh. That is interesting. I thought that the server just did not send any mime type (admittedly very unlikely)

@monkeyslut: If you want to talk to the server admins you could refer them to this issue or just drop them the above explanation.

**Comment by y20k** [comment]
Uups. Closed this by mistake. But thinking about it ... the issue seems to be fixed for now.  I think we will deal with exotic charsets and wrong mime types in the future, if there are complaints.

**Comment by meonwax** [comment]
I found a [small library](https://github.com/j256/simplemagic) that could do the magic byte content-type guessing for us.
If we encounter a real server that doesn't send a content-type, we could implement it using this library.

**Comment by y20k** [comment]
:+1:
