### ISSUE TITLE
Reconnect to the stream...

### ISSUE THREAD

**Issue by epitron** [y20k/transistor#65]
Hi!

Transistor is a great little app. I like it a lot!

I have a small issue though, which I think would be easy to remedy. 

I tend to listen to Transistor while travelling, and the stream often disconnects at some point in my journey. It would be nice if Transistor automatically tried to reconnect when this happens.

The most annoying instance of this occurs every time I leave my house with Transistor playing. When I get about 50 feet from my house, the wifi signal drops out, and the phone switches to 3G mode. Since the IP address has changed, the stream disconnects. Since it's freezing cold outside, it's pretty irritating to have to take off my gloves, take out my phone, and, with frozen fingers, unlock it, open the app, and press the big play button.

Every... single... time....

:)

I'd love if it either could detect when the network went up/down, or if it just kept trying to reconnect every 5 seconds or something. (Ideally both!)

**Comment by y20k** [comment]
Hi there,

the app actually has a method that should reconnect on signal loss. (see [PlayerService.java/onCompletion](https://github.com/y20k/transistor/blob/master/app/src/main/java/org/y20k/transistor/PlayerService.java#L188) and [Issue 32](https://github.com/y20k/transistor/issues/32)). 

On my device the reconnect works well. Strange that you have problems. I wonder how to debug this. I am testing the feature like this: 1. start playback 2. turn off wifi. -> the stream reconnects.

Best wishes

**Comment by epitron** [comment]
Thanks for the quick reply!

Hmmm...  maybe the problem is that there's no network at all for a short period of time (while it's doing the handover from the wifi to the 3G).

What happens if `initializeMediaPlayer()` can't connect at all? Does the `onCompletion()` event still fire? Or is there an `onCouldntConnect()` event?

**Comment by y20k** [comment]
The `onCompletion` method is/was a clever way to avoid asking for an extra permission to monitor network connectivity. In my experience it really works well. If I put my phone in airplane mode (also "no network at all") until the stream stops and then wait 30 seconds... after reactivating connectivity the stream continues to play. 

So the main problem with this bug will be for me to find a way to recreate it.

**Comment by epitron** [comment]
Oh! Maybe the issue is that I'm using NetGuard as an on-phone firewall: 
https://f-droid.org/repository/browse/?fdfilter=netguard&fdid=eu.faircode.netguard

It pretends to be a VPN, so it might not be sending the proper network up/down events to the client applications.

That could explain why the audio stops, but Transistor still thinks it's playing (the "Play" button stays in "Playing" mode, and the little "Play" light stays green).

What happens if a TCP connection just stops receiving packets? Does Transistor have a timeout?

**Comment by y20k** [comment]
Transistor is actually just built on top of Androids native [MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer.html) library. All the networking stuff, like buffering, reconnect intervals etc., is handled by MediaPlayer. So there is no timeout coded into the app itself.

Your firewall/vpn configuration seems to be rather rare. It would be helpful for me to know, if the problems persist even without the firewall. Maybe you could turn on and off Airplane mode during playback (with the firewall turned off) as a test and report back your findings.

**Comment by y20k** [comment]
Since I don't know how to fix your problem, I am closing the issue for now. Sorry, that I could not help.
