### ISSUE TITLE
Pre-built some Radio Station with transistor

### ISSUE THREAD

**Issue by lovebdsobuj** [y20k/transistor#68]
Add some built-in Radio Station.

and If possible add [BASS][] Library.

[BASS][] is an audio library for use in software on several platforms. Its purpose is to provide developers with powerful and efficient sample, stream (MP3, MP2, MP1, OGG, WAV, AIFF, custom generated, and more via OS codecs and add-ons), MOD music (XM, IT, S3M, MOD, MTM, UMX), MO3 music (MP3/OGG compressed MODs), and recording functions. All in a compact DLL that won't bloat your distribution.

**BASS** is available for many different platforms
[BASS]: http://www.un4seen.com/

**Comment by y20k** [comment]
Hi there,

> Add some built-in Radio Station.

thank you for your suggestion. I agree that the on-boarding experience is not the best. Transistor has no search, and it has no selection of stations built in. 

Transistor has not that many users but they are scattered all over the globe. I think it is impossible to compile a selection for a (small but) worldwide user base. 

And search: That would tie transistor to a 3rd party. I simple do not want that. See:  [Previous discussions and feature requests](https://github.com/y20k/transistor/issues/48) and [Shoutcast and Xiph search](https://github.com/y20k/transistor/issues/51).

A solution could be to point users to a non-commercial radio station listing from the add dialog - or maybe start such a listing over here in the project wiki.

> If possible add BASS Library.

Transistor is supposed to be a very simple and independent app. That is why it does only utilize the basic Android libraries - no external ones. Sticking with pure Android makes long term maintenance and debugging easier for me. So even if BASS or FFmpeg for Android maybe superior in one or many ways, I guess I will stick with Android MediaPlayer for the foreseeable future.

Best regards
Christian

**Comment by lovebdsobuj** [comment]
I want to fork this repo and want to add some built-in radio station. 
Do you help me?

**Comment by lovebdsobuj** [comment]
@Stuttgart, I need your help.
I want to create a new app using your (`transistor`) source code.

I want to stream 10 radio station only.

How to add stream url,icon in java class to make Radio Station list?

**Comment by y20k** [comment]
I am not sure what would be the best way. 

- I would pack the icon files somewhere in the /app/src/main/res folder. 
- And in [CollectionAdapter](https://github.com/y20k/transistor/blob/master/app/src/main/java/org/y20k/transistor/helpers/CollectionAdapter.java) I would hard code the LinkedList<String> stationNames.

Since you want a static list of stations the cleaner way would be: Grab Transistors PlayerService (or grab another player service example from GitHub) and start over with a simple MainActivity that only displays a XML Layoutfile with the hard coded 10 stations. That would be way easier in the long run for you.

A starting point for understanding what the PlayerService does would be:
http://developer.android.com/guide/topics/media/mediaplayer.html

Have fun.

PS. If you publish your app drop me a note. (And: If possible please use another name and icon for it to prevent confusion.)

**Comment by lovebdsobuj** [comment]
Certainly, I'll change App name, Icon and tell you about that also app developer credit will be kept to you.

>grab another player service example from GitHub

How to grab play list from GitHub?

**Comment by y20k** [comment]
Oh. I guess I did not put it right. I meant: 

If you want a cleaner start than forking transitor, you should only 

1) take Transistor's [PlayerService](https://github.com/y20k/transistor/blob/master/app/src/main/java/org/y20k/transistor/PlayerService.java) or another (probably better) Playback Service (eg. [MusicService.java](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/MusicService.java) from [Googlesamples@Github](https://github.com/googlesamples/android-UniversalMusicPlayer)) and 

2) write a very simple MainActivity that just displays a XML layoutfile with the ten stations you want to use. The layout file can be visually created in Android Studio

**Comment by lovebdsobuj** [comment]
Very well said. :+1: 

Anyway, after opening `transistor` app, app will download 10 radio station file from internet and place them to `/Android/data/org.y20k.transistor/Collection`.

**Comment by y20k** [comment]
Okay. If you want to use more of Transistor than the PlayerService you should do as suggested before:

> - I would pack the icon files somewhere in the /app/src/main/res folder. 
> - And in [CollectionAdapter](https://github.com/y20k/transistor/blob/master/app/src/main/java/org/y20k/transistor/helpers/CollectionAdapter.java) I would hard code the LinkedList<String> stationNames.

Downloading stations from the internet should not be necessary. 

But if that is the way you want to do it. Transistor has class called [StationFetcher.java](https://github.com/y20k/transistor/blob/master/app/src/main/java/org/y20k/transistor/helpers/StationFetcher.java). You could check if the collection folder is empty and if so you could run StationFetcher for the URLs you want to have added.

Happy coding.

**Comment by lovebdsobuj** [comment]
> - I would pack the icon files somewhere in the `/app/src/main/res` folder.
> - And in `CollectionAdapter` I would hard code the `LinkedList` `stationNames`.

If you don't feel bother, then please, example me your blockquote's.

**Comment by y20k** [comment]
> If you don't feel bother, then please, example me your blockquote's.  

That is probably a bit complicated to explain using this forum here. Can I instead suggest a few online resources? Maybe those classes are a bit too "easy" / too much focussed on beginners. If so, please do not feel offended. I did take those courses myself, and I found them VERY helpful.

Android knowledge
https://classroom.udacity.com/courses/ud837/
https://classroom.udacity.com/courses/ud853/

Java knowledge
https://www.udemy.com/java-tutorial/

**Comment by lovebdsobuj** [comment]
I added this code in `MainActivityFragment` and now downloading radio station when application start
```
final String Radio1= "http://live.kcsb.org/KCSB_128.m3u";
final String Radio2= "http://live.kcsb.org/KCSB_24.m3u";

// download radio station

StationFetcher stationFetcher1 = new StationFetcher(Uri.parse(Radio1.trim()), mActivity);
stationFetcher1.execute();

StationFetcher stationFetcher2 = new StationFetcher(Uri.parse(Radio2.trim()), mActivity);
stationFetcher2.execute();
```

**Comment by y20k** [comment]
:+1:  You would need to do a check for duplicates. The stationFetcher should only need to do its work once.

**Comment by lovebdsobuj** [comment]
Is there any variable that can I use in if function.
Like, 
```
if (StationList == null) {
StationFetcher stationFetcher1 = new StationFetcher(Uri.parse(Radio1.trim()), mActivity); 
stationFetcher1.execute();
} 
```

**Comment by y20k** [comment]
to get the Collection folder: 
```
StorageHelper storageHelper = new StorageHelper(mActivity);
File folder = storageHelper.getCollectionDirectory();
```

to check if this folder is empty 
```
if (folder != null && folder.exists() && folder.isDirectory() && folder.list().length == 0) {
    // folder exists and is empty
}
```

You also might want to have a look at first part (= constructor) of [Collection.java](https://github.com/y20k/transistor/blob/master/app/src/main/java/org/y20k/transistor/core/Collection.java). There the case that the collection folder does not exist is being handled.

As for the rest: You need to find your own solutions. Do not take that personal - I just think you will learn more that way.
