### ISSUE TITLE
HTML translations

### ISSUE THREAD

**Issue by franciscot** [y20k/transistor#69]
Please, Is it possible separate the text from the HTML?
Because the translator can add a bug, for example changing HTML's tags.
Also it's a bit difficult translate the text mixed with HTML and so big.

**Comment by y20k** [comment]
**I agree 100%**. Those string.xml files are messy. I need to rework the Infosheet activity first. That will take some time though. But I guess there is no way around it.

**Comment by y20k** [comment]
@franciscot: I did rewrite the InfosheetActivity to get rid of those HTML strings (see [see commit](https://github.com/y20k/transistor/commit/360f3ee3935aa05da36196c8bf6ed88b2949621a)). 

There is one **drawback**: Translators must update their translations themselves. I did try to copy over those strings from HTML ... But I do not know all those languages. Copying strings blindly bears the a lot of potential for mistakes.

**Comment by y20k** [comment]
@franciscot: I am not sure how to communicate this change. The only thing I could come up with was to put a comment under one of the new strings in Weblate. 
https://hosted.weblate.org/translate/transistor/strings/de/?sid=1ba1deb4-f5e6-11e5-ae43-5254000d9bae&offset=4#comments
Any additional ideas?

**Comment by franciscot** [comment]
I was notified about new strings from weblate and I read your reply on  github.
Later I read your comment in weblate after I already did my translations, because it's not easy to find the comments. 
I assume you are the administrator  of your project in weblate, if its possible, you could send a email/message to all translators from the weblate service.

I don't know what else.

Thanks for your effort.

**Comment by franciscot** [comment]
Sorry, You are right. I recieved an email from weblate with your comment.

**Comment by y20k** [comment]
**Important Note**

Today I did remove the legacy HTML strings within strings.xml ([commit d5685fc](https://github.com/y20k/transistor/commit/d5685fc25bd071a0bed9358c0885282fd3938e76)). If you are looking for the old HTML strings. They still can be found here in their respective "values" folders here: [/app/src/main/res](https://github.com/y20k/transistor/tree/1e51dd8666194353427ca074f2092b6c20cfacd6/app/src/main/res)
