### ISSUE TITLE
I can't add URL begin with MMS://

### ISSUE THREAD

**Issue by c3star** [y20k/transistor#75]
Most of my radio station's URL is started with MMS://, it can be played by MX player. But I can't add it to this app.... Is there a roadmap to support this kind of URL? Thanks

**Comment by y20k** [comment]
Hi there,

Thanks for your request! We had a similar discussion about that issue before (see #7). It boils down to this as far as I remember: MMS:// is not supported by the MediaPlayer library I am using for playback in Transistor. If your question is not answered by #7 please come back and specify your request - e.g. with a specific URL.

Best regards + have a nice day
