### ISSUE TITLE
Metadata can be ""

### ISSUE THREAD

**Issue by y20k** [y20k/transistor#80]
I am not sure if this is a bug, or not. 

`shoutcastProxyReaderLoop` (in [MetadataHelper.java](https://github.com/y20k/transistor/blob/master/app/src/main/java/org/y20k/transistor/helpers/MetadataHelper.java)) sometimes sends a zero character string to `handleMetadataString`. 

For example when handling BBC Radio 1 (http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio1_mf_p).

**Comment by y20k** [comment]
Not really a problem. I'll close this one. 

@pelya : Maybe this is still of some interest for you?

**Comment by pelya** [comment]
No, it's okay. You can get any random bunch of bytes from internet, the
important thing is that you don't crash.
