### ISSUE TITLE
Missing resource

### ISSUE THREAD

**Issue by krt16s** [y20k/transistor#81]
````
:app:compileReleaseJavaWithJavac/home/krt/src/fdroiddata/build/org.y20k.transistor/app/src/main/java/org/y20k/transistor/helpers/NotificationHelper.java:104: error: cannot find symbol
        builder.addAction (R.drawable.ic_stop_black_36dp, context.getString(R.string.notification_stop), stopActionPendingIntent);
                                     ^
  symbol:   variable ic_stop_black_36dp
  location: class drawable
1 error
 FAILED
````

**Comment by y20k** [comment]
I am on vacation right now. I will fix it next week.

**Comment by y20k** [comment]
I did add the missing resource. Thanks for pointing me to it!!

I did a test built. It now runs fine. I did unpublish and re-publish v2.0.1 That should solve the issue (hopefully). 

Best regards

**Comment by krt16s** [comment]
Yep, builds (however, versioncode and version have been bumped), thanks for fixing!

**Comment by y20k** [comment]
corrected the version# and name. gradle files for the next version did slip through.
