### ISSUE TITLE
Radio stations not playing anymore (regression)

### ISSUE THREAD

**Issue by lillet23** [y20k/transistor#86]
First of all, many thanks for this great app!

I've updated from version 2.0.0 to version 2.0.1, and some radio stations won't play anymore (BBC and ERT streams, mainly).
I'm on Cyanogenmod 13.

Two examples:

BBC Radio 1
http://as-hds-ww-live.edgesuite.net/pool_7/live/bbc_radio_one/bbc_radio_one.isml/bbc_radio_one-audio=96000.m3u8

ERT Proto Programma (Greek Radio)
http://ep.ert.gr:1935/LiveRadioAthens/_definst_/proto/playlist.m3u8

**Comment by y20k** [comment]
Hi there, 

m3u8 containers are not (or should not be :-)) supported by transistor at the moment (see Issue #36)
Can you test this URL for BBC One? It works on my device:
http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio1_mf_p
Does it work on your phone?

Best regards

PS. For ERT Proto I did not find a fitting m3u or pls right away. Maybe you will find some of your stations here https://www.internet-radio.com/stations/greek/

**Comment by lillet23** [comment]
Thanks for your fast answer.
The link you've provided works for me (versions 2.0.0 and 2.0.1).

Both links I've provided in my previous message are actually working on version 2.0.0.
Updating to 2.0.1 broke that. Can't understand why (m3u8 containers shouldn't be supported, right?)

I don't know if it's related, but VLC won't play them too.

Transistor shows that green light on top right corner when I tap the station, but there is no sound at all.

**Comment by y20k** [comment]
> Both links I've provided in my previous message are actually working on version 2.0.0.

This is really strange. I did not change anything in the audioprocessing and/or the M3U or PLS handling. M3U and PLS are text files that contain the "real" streaming URL. Most M3U8 I did encounter (including the one you mentioned) have a weird format which does not contain a working streaming URL. For more info I please read this post: [Add support for .m3u8 type playlists.](https://github.com/y20k/transistor/issues/36)

**Comment by y20k** [comment]
As I see it, this issue is more or less a duplicate (see #36). M3U8 will not be supported in the foreseeable future. Sorry. Thank you for the feedback!! Please do not feel discouraged - and come back if you find another bug.

**Comment by lillet23** [comment]
Great, I'll be waiting for m3u8 full support :-)
Keep the good work going, your app is really great !
xx
