### ISSUE TITLE
Unable to add somafm

### ISSUE THREAD

**Issue by jordanl** [y20k/transistor#9]
Sample URLs listed at http://somafm.com/groovesalad/directstreamlinks.html

For example, if I try to add "http://somafm.com/groovesalad.pls" I get a "Download started" popup, but no further response from transistor.

**Comment by benediktg** [comment]
Try typing in (or pasting) the .pls URL manually using the "+" button in Transistor, this worked for me.

**Comment by y20k** [comment]
Sorry for responding late. Adding this station produces this error:

```
Unable to write PlaylistFile /storage/emulated/0/Android/data/org.y20k.transistor/files/Collection/SomaFM: Groove Salad (#1 128k mp3): A nicely chilled plate of ambient/downtempo beats and grooves..m3u
```

I need to strip out certain characters (e.g. ":" and "/"). I will fix that. Thank you for the bug report.

**Comment by y20k** [comment]
I added a [line](https://github.com/y20k/transistor/commit/9581c9c2cb82bf1216188578bb1f715db0882d0c) that strips out ":" and "/" and it worked fine with the station you mentioned. It will be in the next release. Thanks again for reporting the bug.

**Comment by y20k** [comment]
Version 1.1.6 is out. You should be able to add http://somafm.com/groovesalad.pls
