### ISSUE TITLE
After one start of stream app doesn't allow to change stream -> disconnect

### ISSUE THREAD

**Issue by Transitor** [y20k/transistor#98]
For switching streams I have to kill the process and restart it as nothing happens when I change the station. Every time the app tries to connect for < 1sec and then the connection is canceled. It's a Samsung with Android 5.1.1. Newest Update doesn't change this.

**Comment by y20k** [comment]
Hi there, thanks for reporting. 

This sounds like a really serious bug! On my test device and in the emulators, that I am running, I could not reproduce the issue. Those cases are not easy to debug. So I cannot promise that I can fix this - but I will try. First I need a bit more information on this one.

1. which phone model
2. which version of Android 5.1.1 (Samsung or Google or Cyanogen or ...)
3. the URLs of two example stations that you are not able switch
4. does the problem also occur, when stopping the last station before starting the next one
5. does the problem also occur, when initiating the stopping/starting in the main list view of stations (using "long-press")

**Comment by Transitor** [comment]
Thx :-)

1. Samsung A5 2016
2. Samsung Stock
3. Every Stream  I had (~10 different ogg, mp3, Examples: BBC Radio 4, Antenne Bayern, Deutschlandfunk)
4./5. Yes to both: checked everything: status light changed to orange for < 1 sec and over. Only one start of stream possible, then restart necesssary. Sometimes it needs another restart.

**Comment by y20k** [comment]
Hey @Transitor ,

I have some of the stations you mentioned in my list, too. You are using a current generation phone and a new version of Android. That is all good on the one hand. But that means I should see a similar behavior on my phone, too. I will run a test using an emulator tomorrow. Let's hope I can reproduce the problem somehow. Problematic in this case, too: There is no one special way the error occurs.

(I will post my emulator results here.)

**Comment by y20k** [comment]
Hey @Transitor ,

Today I did try to reproduce the issue using an emulated Nexus 4 with Android 5.1.1. I did try several combinations of starting, stopping and restarting stations. I did try BBC 4 and Deutschlandfunk. Sadly I was not able to reproduce your issue. 

My problem now is that I do not have a clue, what could have caused the issue.

In your case I would suggest to use another radio player. I am sorry. :crying_cat_face:

**Comment by Transitor** [comment]
Ok, maybe an update might help in the future...

**Comment by Transitor** [comment]
Ha, ha :-). No issues any more with the new update. Thx!!!

**Comment by Transitor** [comment]
Ok, problem still exists but less often. .
